### ISSUE TITLE
Unable to activate sigh-0.4.1

### ISSUE THREAD

**Issue by cakl** [KrauseFx/fastlane#103]
Today I updated to fastlane x.x.16 and sigh 0.41. After the update I get the following error:

```
xenon:project admin$ fastlane
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:2007:in `raise_if_conflicts': Unable to activate sigh-0.4.1, because fastlane_core-0.2.1 conflicts with fastlane_core (>= 0.3.0) (Gem::LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1176:in `activate'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1212:in `block in activate_dependencies'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1198:in `each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1198:in `activate_dependencies'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1180:in `activate'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_gem.rb:48:in `gem'
	from /usr/bin/fastlane:22:in `<main>'
```
Is this an issue or what did I wrong?

**Comment by KrauseFx** [comment]
That was my mistake. Can you run `sudo gem update fastlane`

**Comment by cakl** [comment]
- Nothing to update 

and still the same error (but thx for the awesome response time)

**Comment by KrauseFx** [comment]
Sorry, maybe `sudo gem update fastlane_core`? Sorry about the troubles :disappointed:

**Comment by cakl** [comment]
I tried ```sudo gem update``` and waiting on ```Updating cert``` since 20 minutes. Hope that helps. No problem for the troubles, thanks for your support.

**Comment by KrauseFx** [comment]
20 minutes is far too long. Cancel it and try again please.

**Comment by cakl** [comment]
```sudo gem update``` helped.
