### ISSUE TITLE
fastlane crashes with gem conflcit

### ISSUE THREAD

**Issue by champo** [KrauseFx/fastlane#109]
Just updated to fastlane 0.1.19 and running it I got:

```
$ fastlane prod --env monits
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:2007:in `raise_if_conflicts': Unable to activate frameit-0.2.0, because commander-4.3.0 conflicts with commander (~> 4.2.0) (Gem::LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1176:in `activate'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1212:in `block in activate_dependencies'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1198:in `each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1198:in `activate_dependencies'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1180:in `activate'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_gem.rb:48:in `gem'
	from /usr/bin/fastlane:22:in `<main>'
```

**Comment by champo** [comment]
Turns out `gem update fastlane` doesn't update all the tools it depends on. Updating everything got it working.

**Comment by KrauseFx** [comment]
That's weird, it **should** update the other tools. What tool didn't update? `sigh` or `cert`? The dependency I added should make use of the latest version: https://github.com/KrauseFx/fastlane/blob/master/fastlane.gemspec#L36

Do you know what's wrong?

**Comment by champo** [comment]
I got that error with frameit, snapshot and pem. I then got tired and simply updated every tool in the fastlane family.

**Comment by KrauseFx** [comment]
Thanks, I hope to get everything fixed with the next release :+1:

**Comment by powtac** [comment]
I get the same error 

```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:2007:in `raise_if_conflicts': Unable to activate fastlane_core-0.46.3, because commander-4.4.0 conflicts with commander (= 4.3.5) (Gem::LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1176:in `activate'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1212:in `block in activate_dependencies'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1198:in `each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1198:in `activate_dependencies'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1180:in `activate'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_gem.rb:48:in `gem'
	from /usr/local/bin/fastlane:22:in `<main>'
```

after running `gem cleanup`... after upgrading to the latest fastlane.

**Comment by KrauseFx** [comment]
@powtac can you try again, we just pushed a fix 👍

**Comment by powtac** [comment]
After running `sudo gem update` fastlane is working again.

**Comment by TKBurner** [comment]
@powtac  Awesome! Really glad to hear you are up and running. Hope you have an excellent week! 👍
