### ISSUE TITLE
fastlint init crash

### ISSUE THREAD

**Issue by cybertk** [KrauseFx/fastlane#144]
Output and stack

```
password has been deleted.
You will have to re-run the recent command to use the new username/password.
DEBUG [2015-03-24 11:38:06.92]: [Transporter Output]: DBG-X: The error code is: -20101
FATAL [2015-03-24 11:38:06.92]: Transporter transfer failed.
WARN [2015-03-24 11:38:06.92]:
ERROR [2015-03-24 11:38:06.92]: Your Apple ID or password was entered incorrectly. (-20101)
FATAL [2015-03-24 11:38:06.92]: Return status of iTunes Transporter was 1: Your Apple ID or password was entered incorrectly. (-20101)
ERROR [2015-03-24 11:38:06.92]: Your Apple ID or password was entered incorrectly. (-20101)
Return status of iTunes Transporter was 1: Your Apple ID or password was entered incorrectly. (-20101)
FATAL [2015-03-24 11:38:06.92]: Could not download metadata from iTunes Connect! It's probably related to your password or your internet connection.
FATAL [2015-03-24 11:38:06.92]: Error occured with the setup program! Reverting changes now!
INFO [2015-03-24 11:38:06.92]: Deleting the 'fastlane' folder
/Users/quanlong/.rvm/gems/ruby-2.1.5/gems/deliver-0.8.0/lib/deliver/app_metadata.rb:302:in `read': No such file or directory @ rb_sysopen - /tmp/956389856.itmsp//metadata.xml (Errno::ENOENT)
	from /Users/quanlong/.rvm/gems/ruby-2.1.5/gems/deliver-0.8.0/lib/deliver/app_metadata.rb:302:in `parse_package'
	from /Users/quanlong/.rvm/gems/ruby-2.1.5/gems/deliver-0.8.0/lib/deliver/app_metadata.rb:66:in `initialize'
	from /Users/quanlong/.rvm/gems/ruby-2.1.5/gems/deliver-0.8.0/lib/deliver/app.rb:113:in `new'
	from /Users/quanlong/.rvm/gems/ruby-2.1.5/gems/deliver-0.8.0/lib/deliver/app.rb:113:in `metadata'
	from /Users/quanlong/.rvm/gems/ruby-2.1.5/gems/deliver-0.8.0/lib/deliver/deliverfile/deliverfile_creator.rb:59:in `create_based_on_identifier'
	from /Users/quanlong/.rvm/gems/ruby-2.1.5/gems/deliver-0.8.0/lib/deliver/deliverfile/deliverfile_creator.rb:31:in `create'
	from /Users/quanlong/.rvm/gems/ruby-2.1.5/gems/fastlane-0.3.0/lib/fastlane/setup.rb:80:in `ask_to_enable_other_tools'
	from /Users/quanlong/.rvm/gems/ruby-2.1.5/gems/fastlane-0.3.0/lib/fastlane/setup.rb:18:in `run'
	from /Users/quanlong/.rvm/gems/ruby-2.1.5/gems/fastlane-0.3.0/bin/fastlane:45:in `block (2 levels) in run'
	from /Users/quanlong/.rvm/gems/ruby-2.1.5/gems/commander-4.3.0/lib/commander/command.rb:179:in `call'
	from /Users/quanlong/.rvm/gems/ruby-2.1.5/gems/commander-4.3.0/lib/commander/command.rb:179:in `call'
	from /Users/quanlong/.rvm/gems/ruby-2.1.5/gems/commander-4.3.0/lib/commander/command.rb:154:in `run'
	from /Users/quanlong/.rvm/gems/ruby-2.1.5/gems/commander-4.3.0/lib/commander/runner.rb:421:in `run_active_command'
	from /Users/quanlong/.rvm/gems/ruby-2.1.5/gems/commander-4.3.0/lib/commander/runner.rb:81:in `run!'
	from /Users/quanlong/.rvm/gems/ruby-2.1.5/gems/commander-4.3.0/lib/commander/delegates.rb:15:in `run!'
	from /Users/quanlong/.rvm/gems/ruby-2.1.5/gems/fastlane-0.3.0/bin/fastlane:60:in `run'
	from /Users/quanlong/.rvm/gems/ruby-2.1.5/gems/fastlane-0.3.0/bin/fastlane:64:in `<top (required)>'
	from /Users/quanlong/.rvm/gems/ruby-2.1.5/bin/fastlane:23:in `load'
	from /Users/quanlong/.rvm/gems/ruby-2.1.5/bin/fastlane:23:in `<main>'
```

**Comment by KrauseFx** [comment]
To set up your account, try starting with `deliver` first by running `deliver init`. Does your password contain any special characters? Are you behind a firewall?

**Comment by cybertk** [comment]
It's succeed after rerun `fastlane init`

**Comment by irvene2000** [comment]
I realize what the problem was now. I named the project "fastlane" and the script was getting confused because it tried to generate a fastlane folder and found the project folder there instead.
