### ISSUE TITLE
for_lane doesn't seem to be implemented?

### ISSUE THREAD

**Issue by earltedly** [KrauseFx/fastlane#170]
At the bottom of [Advanced.md](https://github.com/KrauseFx/fastlane/blob/5862df881fe27f21e5c74d812e3616d327b5edda/Advanced.md) it gives an example of using `for_lane` to specify different app_identifiers for each lanes. I'm attempting to use this but I get the following error when I try and run fastlane.

Appfile:
```
app_identifier "com.12345.1234-staging"
apple_id "earltedly@gmail.com" # Your Apple email address

for_lane :staging do
  app_identifier "com.12345.1234-staging"
end
```
Error:
```
 {:ENVIRONMENT=>nil, :LANE_NAME=>:staging}
FATAL [2015-04-02 15:29:12.11]: undefined method `for_lane' for #<CredentialsManager::AppfileConfig:0x007fe71ae31418>
FATAL [2015-04-02 15:29:12.12]: fastlane finished with errors
/Library/Ruby/Gems/2.0.0/gems/credentials_manager-0.1.3/lib/credentials_manager/appfile_config.rb:26:in `eval': undefined method `for_lane' for #<CredentialsManager::AppfileConfig:0x007fe71ae31418> (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/credentials_manager-0.1.3/lib/credentials_manager/appfile_config.rb:26:in `eval'
	from /Library/Ruby/Gems/2.0.0/gems/credentials_manager-0.1.3/lib/credentials_manager/appfile_config.rb:26:in `block in initialize'
	from /Library/Ruby/Gems/2.0.0/gems/credentials_manager-0.1.3/lib/credentials_manager/appfile_config.rb:25:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/credentials_manager-0.1.3/lib/credentials_manager/appfile_config.rb:25:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/credentials_manager-0.1.3/lib/credentials_manager/appfile_config.rb:7:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/credentials_manager-0.1.3/lib/credentials_manager/appfile_config.rb:7:in `try_fetch_value'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-0.4.7/lib/sigh/options.rb:28:in `available_options'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.4.2/lib/fastlane/actions/sigh.rb:25:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.4.2/lib/fastlane/fast_file.rb:82:in `block (2 levels) in method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.4.2/lib/fastlane/actions/actions_helper.rb:29:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.4.2/lib/fastlane/fast_file.rb:81:in `block in method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.4.2/lib/fastlane/fast_file.rb:80:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.4.2/lib/fastlane/fast_file.rb:80:in `method_missing'
	from (eval):31:in `block (2 levels) in parse'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.4.2/lib/fastlane/runner.rb:18:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.4.2/lib/fastlane/runner.rb:18:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.4.2/lib/fastlane/runner.rb:12:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.4.2/lib/fastlane/runner.rb:12:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.4.2/lib/fastlane/lane_manager.rb:29:in `block in cruise_lanes'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.4.2/lib/fastlane/lane_manager.rb:28:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.4.2/lib/fastlane/lane_manager.rb:28:in `cruise_lanes'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.4.2/bin/fastlane:32:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.2/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.2/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.2/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.2/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.2/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.2/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.4.2/bin/fastlane:60:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.4.2/bin/fastlane:64:in `<top (required)>'
	from /usr/bin/fastlane:23:in `load'
	from /usr/bin/fastlane:23:in `<main>'
```

**Comment by earltedly** [comment]
Aha, I just had a poke around and the method is present in the master branch on CredentialManager but it's not installed on my local machine. I'm guessing the latest fastlane gem doesn't include that code yet?

**Comment by KrauseFx** [comment]
Ohhh, nice catch, I'll make sure the latest version is released right now.

**Comment by earltedly** [comment]
That’s brilliant - thank you.

Btw, I saw you speak at NSConference. I’ve finally had the chance to check out fastlane. Looks really good so far - nice work :)

**Comment by KrauseFx** [comment]
Thanks @earltedly! 

I just pushed the update, please update using `sudo gem update credentials_manager`

Let me know if that solves your problem. Also, thanks to @fabiomassimo

**Comment by earltedly** [comment]
I've updated and it's no longer terminating with an except. It doesn't seem to be applying the `app_identifier` I specify in the `for_lane` block though.

If I remove the `app_identifier` line from outside the`for_lane` block (leaving the one inside), then fastlane prompts me for the bundle identifier when it tries to run `sigh`.

```
INFO [2015-04-02 16:07:34.48]: -------------------------------------------------
INFO [2015-04-02 16:07:34.48]: --- Step: Verifying required fastlane version ---
INFO [2015-04-02 16:07:34.48]: -------------------------------------------------
INFO [2015-04-02 16:07:34.48]: fastlane version valid
INFO [2015-04-02 16:07:34.48]: Driving the lane 'staging'
INFO [2015-04-02 16:07:34.49]: ------------------
INFO [2015-04-02 16:07:34.49]: --- Step: sigh ---
INFO [2015-04-02 16:07:34.49]: ------------------
INFO [2015-04-02 16:07:36.90]: Login into iOS Developer Center
INFO [2015-04-02 16:07:46.94]: Login successful
INFO [2015-04-02 16:07:47.63]: Fetching all available provisioning profiles...
INFO [2015-04-02 16:07:48.38]: Checking if profile is available. (45 profiles found)
The bundle identifier of your app: 
```

**Comment by fabiomassimo** [comment]
@KrauseFx did you deploy https://github.com/KrauseFx/fastlane/pull/156?

**Comment by KrauseFx** [comment]
@fabiomassimo I did. Wasn't I supposed to?

**Comment by fabiomassimo** [comment]
No, it's fine. I just wanted to be sure about that, because latest release of fastlane (0.4.2) was made before my PR got accepted.

**Comment by KrauseFx** [comment]
Yes, not many users will receive the update, only for new installations and for users who actively update the `credentials_manager`.

**Comment by KrauseFx** [comment]
Sorry @earltedly, you'll have to wait for the next `fastlane` release to use this feature...

**Comment by earltedly** [comment]
@KrauseFx that's ok - thanks for trying. Any idea when the next release might get pushed out?

**Comment by KrauseFx** [comment]
Hopefully today

**Comment by KrauseFx** [comment]
Here we go: https://github.com/KrauseFx/fastlane/releases/tag/0.5.0
Please update using `sudo gem update fastlane`

**Comment by walsht** [comment]
I am getting a similar issue, I tried uninstalling and reinstalling both fastlane and deliver and getting these undefined method when calling help
```
$ deliver --help
undefined method `app' for #<CredentialsManager::AppfileConfig:0x007fc53a9beb80>
undefined method `app' for #<CredentialsManager::AppfileConfig:0x007fc53a91daf0>
undefined method `app' for #<CredentialsManager::AppfileConfig:0x007fc53a91c5d8>
  deliver
```

**Comment by KrauseFx** [comment]
@walsht there is no such method `app`. Please share your `Appfile` and use the available options `apple_id` and `app_identifier`

**Comment by walsht** [comment]
```
app_identifier ENV['BUNDLE_ID'] 
apple_id ENV['APPLE_LOGIN_EMAIL'] 
app ENV['APPLE_ID']
```

**Comment by walsht** [comment]
After removing app I don't get the error.  Thanks.

**Comment by KrauseFx** [comment]
@walsht where do you have the `app` from? Is it somewhere in the documentation
