### ISSUE TITLE
'sh' isn't available in custom actions

### ISSUE THREAD

**Issue by duemunk** [KrauseFx/fastlane#193]
The `sh`doesn't seem to work from custom/own actions.
 
1. I made a `fastlane new_action`
2. Uncommented the line with `sh "shellcommand ./path"`
3. Got the error `undefined method 'sh' for Fastlane::Actions::TestyAction:Class`

**Stack trace**
```console
duemunk$ fastlane shtest
INFO [2015-04-14 16:37:42.58]: Successfully loaded custom action '/Users/duemunk/Gits/bemyeyes-ios/fastlane/actions/testy.rb'.
INFO [2015-04-14 16:37:42.60]: -------------------------------------------------
INFO [2015-04-14 16:37:42.60]: --- Step: Verifying required fastlane version ---
INFO [2015-04-14 16:37:42.60]: -------------------------------------------------
INFO [2015-04-14 16:37:42.60]: fastlane version valid
INFO [2015-04-14 16:37:42.60]: Driving the lane 'shtest'
INFO [2015-04-14 16:37:42.60]: -------------------
INFO [2015-04-14 16:37:42.60]: --- Step: testy ---
INFO [2015-04-14 16:37:42.60]: -------------------
My Ruby Code!
INFO [2015-04-14 16:37:42.60]: Variable Dump:
INFO [2015-04-14 16:37:42.60]: {:ENVIRONMENT=>nil, :LANE_NAME=>:shtest}
FATAL [2015-04-14 16:37:42.60]: undefined method `sh' for Fastlane::Actions::TestyAction:Class
FATAL [2015-04-14 16:37:42.61]: fastlane finished with errors
/Users/duemunk/Gits/bemyeyes-ios/fastlane/actions/testy.rb:11:in `run': undefined method `sh' for Fastlane::Actions::TestyAction:Class (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.7.0/lib/fastlane/fast_file.rb:82:in `block (2 levels) in method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.7.0/lib/fastlane/actions/actions_helper.rb:29:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.7.0/lib/fastlane/fast_file.rb:81:in `block in method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.7.0/lib/fastlane/fast_file.rb:80:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.7.0/lib/fastlane/fast_file.rb:80:in `method_missing'
	from (eval):30:in `block (2 levels) in parse'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.7.0/lib/fastlane/runner.rb:19:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.7.0/lib/fastlane/runner.rb:19:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.7.0/lib/fastlane/runner.rb:13:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.7.0/lib/fastlane/runner.rb:13:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.7.0/lib/fastlane/lane_manager.rb:45:in `block in cruise_lanes'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.7.0/lib/fastlane/lane_manager.rb:44:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.7.0/lib/fastlane/lane_manager.rb:44:in `cruise_lanes'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.7.0/bin/fastlane:32:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.0/lib/commander/command.rb:179:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.0/lib/commander/command.rb:179:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.0/lib/commander/command.rb:154:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.0/lib/commander/runner.rb:421:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.0/lib/commander/runner.rb:81:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.0/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.7.0/bin/fastlane:79:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.7.0/bin/fastlane:85:in `<top (required)>'
	from /usr/bin/fastlane:23:in `load'
	from /usr/bin/fastlane:23:in `<main>'
```

**Fastfile**
```ruby
lane :shtest do
  testy
end
```

**Actions/testy.rb**
```ruby
module Fastlane
  module Actions
    module SharedValues
      TESTY_CUSTOM_VALUE = :TESTY_CUSTOM_VALUE
    end

    class TestyAction < Action
      def self.run(params)
        puts "My Ruby Code!"
        # puts "Parameter Path: #{params[:first]}"
        sh "shellcommand ./path"

        # Actions.lane_context[SharedValues::TESTY_CUSTOM_VALUE] = "my_val"
      end



      #####################################################
      # @!group Documentation
      #####################################################

      def self.description
        "A short description with <= 80 characters of what this action does"
      end

      def self.available_options
        # Define all options your action supports. 
        # The environment variable (last parameters) is optional, remove it if you don't need it
        # You can add as many parameters as you want
        [
          ['path', 'Describe what this parameter is useful for', 'ENVIRONMENT_VARIABLE_NAME'],
          ['second', 'Describe what this parameter is useful for']
        ]
      end

      def self.output
        # Define the shared values you are going to provide
        # Example
        [
          ['TESTY_CUSTOM_VALUE', 'A description of what this value contains']
        ]
      end

      def self.author
        # So no one will ever forget your contribution to fastlane :) You are awesome btw!
        '[Your GitHub Name]'
      end
    end
  end
end
```

**Comment by KrauseFx** [comment]
Ha, I was just updating the template, but haven't updated the super class. This was already implemented but not release yet. Could you try by downloading the latest version and running `sudo bundle install` and `sudo rake install`?

**Comment by duemunk** [comment]
That works fine!

**Comment by KrauseFx** [comment]
Okay, great to hear, so just `sh` works now?

**Comment by duemunk** [comment]
Yep. Thanks!
