### ISSUE TITLE
[Feature] Run fastlane with dynamic folder name

### ISSUE THREAD

**Issue by iamjason** [KrauseFx/fastlane#195]
Is it be possible to add an optional command line parameter to run fastlane from a different folder?

eg:
```
fastlane deploy "./fastlane_app1"
fastlane deploy "./fastlane_app2"
```
I believe ``` FOLDER_NAME ``` is the variable that needs to be dynamic:
https://github.com/KrauseFx/fastlane/blob/master/lib/fastlane/fastlane_folder.rb#L3

Any help would be appreciated!

**Comment by KrauseFx** [comment]
Yes, I assume so. If you have different folders, why don't you `cd fastlane_app1 && fastlane`?

**Comment by iamjason** [comment]
Thanks for the fast response!  I don't think I make the problem clear with my question.  Maybe if I explain the problem, you'll have a better alternative. 

I have one workspace that has four apps/schemes.  All apps have different bundle IDs, assets, metadata, etc, but share a lot of code. So, the file structure is something like:

./TheApps.xcworkspace
./fastlane_app1
./fastlane_app1qa
./fastlane_app2
./fastlane_app2qa

Right now, I'm just renaming folder of the app that I need to build.  Which I can feel isn't the right solution.  Does that make sense?

**Comment by KrauseFx** [comment]
If you plan on extending this to a number x of apps, your solution is absolutely not scalable. 

But anyway, back to your problem: why don't you just do something like this:

Appfile
```ruby
app_identifier ENV["APP_IDENTIFIER"]
...
```

and call `fastlane` like this: ```APP_IDENTIFIER=com.krausefx.app fastlane beta`

**Comment by KrauseFx** [comment]
You can do that for all options of course.

**Comment by dhagerty9009** [comment]
Though the passing of command line arguments could be interesting. Let's say you have different actions to deploy different version numbers of your app, like so:

```ruby
lane :major do
    increment_version_number 'major'
    # other lane actions
end

lane :minor do
    increment_version_number 'minor'
    # other lane actions
end

lane :patch do
    increment_version_number 'patch'
    # other lane actions
end
```

It would be nice to condense these into one action since the only differences are the arguments passed to the `increment_version_number` action. The lane could be called via `fastlane deploy major`, and this could allow for some interesting other options if it could be expanded to other actions.

**Comment by iamjason** [comment]
@KrauseFx First off, the new fastlane updates look great!

I believe I'm passing the EVN variables correctly, but I am obviously missing something.  The ipa Action in the lane doesn't pass the correct variables.  eg output:  ``` set -o pipefail && ipa build -c "Release" --verbose | xcpretty ``` 

I've put together a basic example project: https://github.com/iamjason/fastlane-multiple-app-example

Thanks again for your suggestions!

**Comment by iamjason** [comment]
I'm definitely getting closer!  I'm currently having an issue with ``` deliver :skip_deploy, :force ```

Found here: https://github.com/iamjason/fastlane-multiple-app-example/blob/master/fastlane/Fastfile#L18

The part of the error message that looks important: ``` No value or block passed to method 'apple_id' ```

More detailed error information: https://gist.github.com/iamjason/d9519c3bb8d7e78e3728

**Comment by KrauseFx** [comment]
First off, there is a built-in `sigh` action you can use. 
The error message you linked is caused by not providing a value on the `apple_id` block in your `Appfile`.

**Comment by KrauseFx** [comment]
I'll take a closer look later today.

**Comment by iamjason** [comment]
Again thanks for your help on this!

Today, after updating all gems ``` sudo gem update ```...  I'm running into a new error.  I tried on another machine, for a sanity check, and got the same message.

``` 
➜  fastlane-multiple-app-example git:(maven-test) ✗ sudo gem update
Updating installed gems
Nothing to update
➜  fastlane-multiple-app-example git:(maven-test) ✗ ./build_App2.sh
INFO [2015-04-16 13:31:46.73]: -------------------------------------------------
INFO [2015-04-16 13:31:46.73]: --- Step: Verifying required fastlane version ---
INFO [2015-04-16 13:31:46.73]: -------------------------------------------------
INFO [2015-04-16 13:31:46.73]: fastlane version valid
INFO [2015-04-16 13:31:46.73]: Driving the lane 'deploy'
INFO [2015-04-16 13:31:46.73]: -----------------
INFO [2015-04-16 13:31:46.73]: --- Step: ipa ---
INFO [2015-04-16 13:31:46.73]: -----------------
DEBUG [2015-04-16 13:31:46.73]: set -o pipefail && ipa build -w "BothApps.xcworkspace" -c "Release" -s "App2" -d "fastlane/_build_app2" --verbose | xcpretty
INFO [2015-04-16 13:31:46.73]: [SHELL COMMAND]: set -o pipefail && ipa build -w "BothApps.xcworkspace" -c "Release" -s "App2" -d "fastlane/_build_app2" --verbose | xcpretty
INFO [2015-04-16 13:31:47.53]: Variable Dump:
INFO [2015-04-16 13:31:47.53]: {:ENVIRONMENT=>nil, :LANE_NAME=>:deploy}
FATAL [2015-04-16 13:31:47.53]: Exit status of command 'set -o pipefail && ipa build -w "BothApps.xcworkspace" -c "Release" -s "App2" -d "fastlane/_build_app2" --verbose | xcpretty' was 256 instead of 0. 

FATAL [2015-04-16 13:31:48.16]: fastlane finished with errors
/usr/local/lib/ruby/gems/2.1.0/gems/fastlane-0.9.0/lib/fastlane/actions/actions_helper.rb:71:in `sh_no_action': Exit status of command 'set -o pipefail && ipa build -w "BothApps.xcworkspace" -c "Release" -s "App2" -d "fastlane/_build_app2" --verbose | xcpretty' was 256 instead of 0.  (RuntimeError)
	from /usr/local/lib/ruby/gems/2.1.0/gems/fastlane-0.9.0/lib/fastlane/actions/actions_helper.rb:50:in `sh'
	from /usr/local/lib/ruby/gems/2.1.0/gems/fastlane-0.9.0/lib/fastlane/actions/ipa.rb:76:in `run'
	from /usr/local/lib/ruby/gems/2.1.0/gems/fastlane-0.9.0/lib/fastlane/fast_file.rb:104:in `block (2 levels) in method_missing'
	from /usr/local/lib/ruby/gems/2.1.0/gems/fastlane-0.9.0/lib/fastlane/actions/actions_helper.rb:29:in `execute_action'
	from /usr/local/lib/ruby/gems/2.1.0/gems/fastlane-0.9.0/lib/fastlane/fast_file.rb:103:in `block in method_missing'
	from /usr/local/lib/ruby/gems/2.1.0/gems/fastlane-0.9.0/lib/fastlane/fast_file.rb:102:in `chdir'
	from /usr/local/lib/ruby/gems/2.1.0/gems/fastlane-0.9.0/lib/fastlane/fast_file.rb:102:in `method_missing'
	from (eval):5:in `block (2 levels) in parse'
	from /usr/local/lib/ruby/gems/2.1.0/gems/fastlane-0.9.0/lib/fastlane/runner.rb:19:in `call'
	from /usr/local/lib/ruby/gems/2.1.0/gems/fastlane-0.9.0/lib/fastlane/runner.rb:19:in `block in execute'
	from /usr/local/lib/ruby/gems/2.1.0/gems/fastlane-0.9.0/lib/fastlane/runner.rb:13:in `chdir'
	from /usr/local/lib/ruby/gems/2.1.0/gems/fastlane-0.9.0/lib/fastlane/runner.rb:13:in `execute'
	from /usr/local/lib/ruby/gems/2.1.0/gems/fastlane-0.9.0/lib/fastlane/lane_manager.rb:45:in `block in cruise_lanes'
	from /usr/local/lib/ruby/gems/2.1.0/gems/fastlane-0.9.0/lib/fastlane/lane_manager.rb:44:in `each'
	from /usr/local/lib/ruby/gems/2.1.0/gems/fastlane-0.9.0/lib/fastlane/lane_manager.rb:44:in `cruise_lanes'
	from /usr/local/lib/ruby/gems/2.1.0/gems/fastlane-0.9.0/bin/fastlane:32:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.1.0/gems/commander-4.3.2/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.1.0/gems/commander-4.3.2/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.1.0/gems/commander-4.3.2/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.1.0/gems/commander-4.3.2/lib/commander/runner.rb:428:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.1.0/gems/commander-4.3.2/lib/commander/runner.rb:68:in `run!'
	from /usr/local/lib/ruby/gems/2.1.0/gems/commander-4.3.2/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.1.0/gems/fastlane-0.9.0/bin/fastlane:111:in `run'
	from /usr/local/lib/ruby/gems/2.1.0/gems/fastlane-0.9.0/bin/fastlane:117:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
➜  fastlane-multiple-app-example git:(maven-test) ✗ 
```

**Comment by KrauseFx** [comment]
What happens when you execute ` set -o pipefail && ipa build -w "BothApps.xcworkspace" -c "Release" -s "App2" -d "fastlane/_build_app2" --verbose | xcpretty`?

**Comment by iamjason** [comment]
It hangs for less than a second and returns to the command line prompt.

**Comment by iamjason** [comment]
Looking deeper, this second problem was seems like cocoapods corrupted the workspace and the scheme no longer existed.  Running: ``` ipa build -w "BothApps.xcworkspace" -c "Release" -s "App2" -d "fastlane/_build_app2" --verbose ```  Returned a valuable error message ``` Scheme App2 not found ```
Rebuilding the workspace fixes that issue.  Sorry for the tangent...

However, I'm still getting the ``` FATAL [2015-04-16 16:55:45.08]: App is missing information (apple_id not given)
FATAL [2015-04-16 16:55:45.73]: fastlane finished with errors ```

With this image:

![error1429217744](https://cloud.githubusercontent.com/assets/442302/7191199/b61058c6-e459-11e4-9328-74d301bb1a87.png)

**Comment by iamjason** [comment]
So, if the ``` apple_id ``` isn't getting passed correctly, here is where I _think_ I'm passing the ENV value:
https://github.com/iamjason/fastlane-multiple-app-example/blob/master/build_App1.sh#L1

And here is where I _think_ I'm using the value passed:
https://github.com/iamjason/fastlane-multiple-app-example/blob/master/fastlane/Appfile#L1

Do both of those look ok to you?

**Comment by KrauseFx** [comment]
Can you run it without the `| xcpretty` in the end?

**Comment by iamjason** [comment]
Yeah, it the ``` ipa ``` step is now working with out any errors, the current problem is with the ``` deliver ```

Here is a snippet from the where it's erroring out currently:

``` INFO [2015-04-16 17:44:12.65]: ---------------------
INFO [2015-04-16 17:44:12.65]: --- Step: deliver ---
INFO [2015-04-16 17:44:12.65]: ---------------------
INFO [2015-04-16 17:44:13.86]: Skipping submission of app update
INFO [2015-04-16 17:44:14.05]: Got all information needed to deploy a new update ('1.0.7') for app 'com.mavenclinic.ForumQA'
INFO [2015-04-16 17:44:15.63]: Logging into iTunesConnect
INFO [2015-04-16 17:44:25.77]: Successfully logged into iTunesConnect
INFO [2015-04-16 17:44:26.57]: Variable Dump:
INFO [2015-04-16 17:44:26.57]: {:ENVIRONMENT=>nil, :LANE_NAME=>:deploy, :IPA_OUTPUT_PATH=>"/Users/jason/fastlane-multiple-app-example/fastlane/_build_app1/App1.ipa", :DSYM_OUTPUT_PATH=>"/Users/jason/fastlane-multiple-app-example/fastlane/_build_app1/App1.app.dSYM.zip"}
FATAL [2015-04-16 17:44:26.57]: App is missing information (apple_id not given)
FATAL [2015-04-16 17:44:27.29]: fastlane finished with errors
/usr/local/lib/ruby/gems/2.1.0/gems/fastlane_core-0.5.2/lib/fastlane_core/itunes_connect/itunes_connect_helper.rb:33:in `verify_app': App is missing information (apple_id not given) (FastlaneCore::ItunesConnect::ItunesConnectGeneralError)
	from /usr/local/lib/ruby/gems/2.1.0/gems/deliver-0.9.1/lib/deliver/itunes_connect/itunes_connect_reader.rb:45:in `get_live_version'
	from /usr/local/lib/ruby/gems/2.1.0/gems/deliver-0.9.1/lib/deliver/itunes_connect/itunes_connect_new_version.rb:11:in `create_new_version!'
	from /usr/local/lib/ruby/gems/2.1.0/gems/deliver-0.9.1/lib/deliver/app.rb:152:in `create_new_version!'
	from /usr/local/lib/ruby/gems/2.1.0/gems/deliver-0.9.1/lib/deliver/deliver_process.rb:141:in `verify_app_on_itunesconnect'
	from /usr/local/lib/ruby/gems/2.1.0/gems/deliver-0.9.1/lib/deliver/deliver_process.rb:37:in `run'
	from /usr/local/lib/ruby/gems/2.1.0/gems/deliver-0.9.1/lib/deliver/deliverer.rb:133:in `finished_executing_deliver_file'
	from /usr/local/lib/ruby/gems/2.1.0/gems/deliver-0.9.1/lib/deliver/deliverfile/deliverfile.rb:31:in `initialize'
	from /usr/local/lib/ruby/gems/2.1.0/gems/deliver-0.9.1/lib/deliver/deliverer.rb:85:in `new'
	from /usr/local/lib/ruby/gems/2.1.0/gems/deliver-0.9.1/lib/deliver/deliverer.rb:85:in `initialize'
	from /usr/local/lib/ruby/gems/2.1.0/gems/fastlane-0.9.0/lib/fastlane/actions/deliver.rb:21:in `new'
	from /usr/local/lib/ruby/gems/2.1.0/gems/fastlane-0.9.0/lib/fastlane/actions/deliver.rb:21:in `block in run'
	from /usr/local/lib/ruby/gems/2.1.0/gems/fastlane-0.9.0/lib/fastlane/actions/deliver.rb:19:in `chdir'
	from /usr/local/lib/ruby/gems/2.1.0/gems/fastlane-0.9.0/lib/fastlane/actions/deliver.rb:19:in `run'
	from /usr/local/lib/ruby/gems/2.1.0/gems/fastlane-0.9.0/lib/fastlane/fast_file.rb:104:in `block (2 levels) in method_missing'
	from /usr/local/lib/ruby/gems/2.1.0/gems/fastlane-0.9.0/lib/fastlane/actions/actions_helper.rb:29:in `execute_action'
	from /usr/local/lib/ruby/gems/2.1.0/gems/fastlane-0.9.0/lib/fastlane/fast_file.rb:103:in `block in method_missing'
	from /usr/local/lib/ruby/gems/2.1.0/gems/fastlane-0.9.0/lib/fastlane/fast_file.rb:102:in `chdir'
	from /usr/local/lib/ruby/gems/2.1.0/gems/fastlane-0.9.0/lib/fastlane/fast_file.rb:102:in `method_missing'
	from (eval):18:in `block (2 levels) in parse'
	from /usr/local/lib/ruby/gems/2.1.0/gems/fastlane-0.9.0/lib/fastlane/runner.rb:19:in `call'
	from /usr/local/lib/ruby/gems/2.1.0/gems/fastlane-0.9.0/lib/fastlane/runner.rb:19:in `block in execute'
	from /usr/local/lib/ruby/gems/2.1.0/gems/fastlane-0.9.0/lib/fastlane/runner.rb:13:in `chdir'
	from /usr/local/lib/ruby/gems/2.1.0/gems/fastlane-0.9.0/lib/fastlane/runner.rb:13:in `execute'
	from /usr/local/lib/ruby/gems/2.1.0/gems/fastlane-0.9.0/lib/fastlane/lane_manager.rb:45:in `block in cruise_lanes'
	from /usr/local/lib/ruby/gems/2.1.0/gems/fastlane-0.9.0/lib/fastlane/lane_manager.rb:44:in `each'
	from /usr/local/lib/ruby/gems/2.1.0/gems/fastlane-0.9.0/lib/fastlane/lane_manager.rb:44:in `cruise_lanes'
	from /usr/local/lib/ruby/gems/2.1.0/gems/fastlane-0.9.0/bin/fastlane:32:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.1.0/gems/commander-4.3.2/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.1.0/gems/commander-4.3.2/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.1.0/gems/commander-4.3.2/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.1.0/gems/commander-4.3.2/lib/commander/runner.rb:428:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.1.0/gems/commander-4.3.2/lib/commander/runner.rb:68:in `run!'
	from /usr/local/lib/ruby/gems/2.1.0/gems/commander-4.3.2/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.1.0/gems/fastlane-0.9.0/bin/fastlane:111:in `run'
	from /usr/local/lib/ruby/gems/2.1.0/gems/fastlane-0.9.0/bin/fastlane:117:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'  ```

**Comment by KrauseFx** [comment]
You still haven't provided an `apple_id` in your `Appfile`. Are you sure you're setting one?

**Comment by iamjason** [comment]
See my note here: https://github.com/KrauseFx/fastlane/issues/195#issuecomment-93840233

I think I'm passing the ``` apple_id ``` with the env variable, but I'm not sure how to debug that.

https://github.com/iamjason/fastlane-multiple-app-example/blob/master/fastlane/Appfile#L1

**Comment by KrauseFx** [comment]
Okay, after further investigation, it's your `Deliverfile`, where you define a new `apple_id` without providing a value.

**Comment by iamjason** [comment]
:+1:  That seemed to be the issue!  Thanks again for all of your help.

With that said... I don't entirely understand the _why_ here, because I define it as the same ENV variable in both the ``` Appfile ``` and ``` Deliverfile ```.  But, removing it from the ``` Deliverfile ``` fixed all issues.  So, if there is an explanation shorter than "learn ruby" I'd be interested... Otherwise, don't worry about it.  :+1:

**Comment by KrauseFx** [comment]
Sorry, I can't tell you, if you share your previous `Deliverfile`, I might be able to help.
