### ISSUE TITLE
rescue in method_missing'

### ISSUE THREAD

**Issue by shams-ahmed** [KrauseFx/fastlane#197]
version: fastlane 0.9.0
command: fastlane beta

```
FATAL [2015-04-15 23:47:42.92]: Could not find method 'successful'. Check out the README for more details: https://github.com/KrauseFx/fastlane
FATAL [2015-04-15 23:47:43.18]: fastlane finished with errors
/Library/Ruby/Gems/2.0.0/gems/fastlane-0.9.0/lib/fastlane/fast_file.rb:91:in `rescue in method_missing': Could not find method 'successful'. Check out the README for more details: https://github.com/KrauseFx/fastlane (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.9.0/lib/fastlane/fast_file.rb:87:in `method_missing'
	from (eval):51:in `block (2 levels) in parse'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.9.0/lib/fastlane/runner.rb:24:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.9.0/lib/fastlane/runner.rb:24:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.9.0/lib/fastlane/runner.rb:13:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.9.0/lib/fastlane/runner.rb:13:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.9.0/lib/fastlane/lane_manager.rb:45:in `block in cruise_lanes'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.9.0/lib/fastlane/lane_manager.rb:44:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.9.0/lib/fastlane/lane_manager.rb:44:in `cruise_lanes'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.9.0/bin/fastlane:32:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.2/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.2/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.2/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.2/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.2/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.2/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.9.0/bin/fastlane:111:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.9.0/bin/fastlane:117:in `<top (required)>'
	from /usr/bin/fastlane:23:in `load'
	from /usr/bin/fastlane:23:in `<main>'
➜  ios git:(master) ✗ 
```

**Comment by KrauseFx** [comment]
Please share your Fastfile, as you seem to access a variable there, that does not exist.

**Comment by kcharwood** [comment]
I'm seeing the same thing here.

**Comment by kcharwood** [comment]
My current fastfile (scrubbed). Note my project file I am referencing is 2 folders deep from the top level of the repo where the fastlane folder is, but I'm properly referencing its path.

```ruby
# Customise this file, documentation can be found here:
# https://github.com/krausefx/fastlane#customise-the-fastfile

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
# opt_out_usage

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "0.9.0"

before_all do
  ENV["SLACK_URL"] = "SCRUBBED"

  # sh "./customShellScript.sh"
  # increment_build_number

end

desc "Runs all the tests"
lane :test do
  # snapshot
  run_tests
	slack({
	  message: "Successfully executed tests",
	  success: true,
	  channel: 'SCRUBBED'
	})
end

desc "In House Beta Enterprise Distribution"
lane :inhouse do
  build_app
  #hockey
end

lane :appstore do
  # insert your code here
end

after_all do |lane|
  slack({
    message: "FASTLANE SETUP TEST",
    success: true,
    channel: 'SCRUBBED'
  })
end


error do |lane, exception|
  # Something bad happened
  message = 'Fastlane build failed to complete',
  slack({
  	message: message,
  	success: false,
  	channel: 'SCRUBBED',
    payload: {
      'Exception' => exception.to_s,
      'Build Date' => Time.new.to_s,
    },
  })
end

# Functions to encapsulate common operations
def run_tests  
  xctool :test, [
      "--project", "'SCRUBBED.xcodeproj'",
      "--scheme", "'SCRUBBED'",
      "--configuration", "Debug",
      "--sdk", "iphonesimulator",
      "--arch", "i386"
    ].join(" ")
end

def build_app  
  ipa({
    project: "SCRUBBED.xcodeproj",
    configuration: "Release",
    scheme: "SCRUBBED"
  })
end
```

**Comment by kcharwood** [comment]
And of course, now it works for me... :)

**Comment by KrauseFx** [comment]
Yes, the posted `Fastfile` looks correct. Before that, you seem to have accessed `successful` somewhere, but it wasn't defined. I'll try to make the error message more clear.

**Comment by KrauseFx** [comment]
Oh, sorry, these were 2 different projects/profiles. @shams-ahmed please share your `Fastfile` and I can help you.

**Comment by shams-ahmed** [comment]
@KrauseFx 

```
# Customise this file, documentation can be found here:
# https://github.com/krausefx/fastlane#customise-the-fastfile

# Change the syntax highlighting to Ruby

# All lines starting with a # are ignored when running `fastlane`

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "0.7.0"

before_all do
  ENV["SLACK_URL"] = " https://hooks.slack.com/services/my_api_code"

  # sh "./customShellScript.sh"

  # cocoapods

  # increment_build_number

  ipa

  # xctool
end

lane :test do
  snapshot
end

lane :beta do
  # snapshot
  sigh
  deliver :skip_deploy, :beta
  # sh "your_script.sh"
end

lane :deploy do
  snapshot
  sigh
  deliver :skip_deploy, :force
  # frameit
end

lane :inhouse do
  # insert your code here
end

# You can define as many lanes as you want

after_all do |lane|
  This block is called, only if the executed lane was successful
  slack({
    message: "Successfully deployed new App Update for myFits",
    success: true,
    channel: 'announcement'
  })
end


error do |lane, exception|
  # Something bad happened
end

**Comment by KrauseFx** [comment]
Check out your `after_all` block, the first line is **not** a comment: 

```This block is called, only if the executed lane was successful```

change it to 

```# This block is called, only if the executed lane was successful```

**Comment by KrauseFx** [comment]
In related news: https://github.com/KrauseFx/fastlane/commit/fb812c9177db2e72dc359704f3a08b5d47d46b69
