### ISSUE TITLE
fastlane init might be missing dependency multi_json (?)

### ISSUE THREAD

**Issue by hannesoid** [KrauseFx/fastlane#20]
When running fastlane-0.1.1 'fastlane init' the first time I had a gem error. After installing multi_json gem it worked.

```
/Users/hannes/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/dependency.rb:315:in `to_specs': Could not find 'multi_json' (~> 1.0) among 75 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/Users/hannes/.rvm/gems/ruby-2.1.5:/Users/hannes/.rvm/gems/ruby-2.1.5@global', execute `gem env` for more information
	from /Users/hannes/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1313:in `block in activate_dependencies'
	from /Users/hannes/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1302:in `each'
	from /Users/hannes/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1302:in `activate_dependencies'
	from /Users/hannes/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1284:in `activate'
	from /Users/hannes/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1316:in `block in activate_dependencies'
	from /Users/hannes/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1302:in `each'
	from /Users/hannes/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1302:in `activate_dependencies'
	from /Users/hannes/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1284:in `activate'
	from /Users/hannes/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1316:in `block in activate_dependencies'
	from /Users/hannes/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1302:in `each'
	from /Users/hannes/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1302:in `activate_dependencies'
	from /Users/hannes/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1284:in `activate'
	from /Users/hannes/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_gem.rb:60:in `block in gem'
	from /Users/hannes/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_gem.rb:59:in `synchronize'
	from /Users/hannes/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_gem.rb:59:in `gem'
	from /Users/hannes/.rvm/rubies/ruby-2.1.5/bin/fastlane:22:in `<main>'
	from /Users/hannes/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
	from /Users/hannes/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by KrauseFx** [comment]
Thanks, this is added, seems to be caused by `rvm`, since you're the first to run into this issue.
All the other dependencies and gems worked fine?
