### ISSUE TITLE
Hockey error: 'ipa' value must be a String!

### ISSUE THREAD

**Issue by xareelee** [KrauseFx/fastlane#209]
The fastlane version is `0.12.1`.

I follow [the documentation for fastlane actions](https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md#hockeyapp) to build a lane for beta testing:

```rb
platform :ios do

  lane :inhouse do
    # the ipa has been built already...
    hockey({
      api_token: "XXXXXXXXX",
      ipa: "./XXXXXX.ipa",
      notes: "Test HockeyApp deployment"
    })
    # ...
  end

end
```

After performing `fastlane inhouse`, it shows an error message `'ipa' value must be a String!`.

I ensure the value of `ipa` is a string, and I have no idea about why this error could happen.

**Comment by KrauseFx** [comment]
Could you please share the full output when running `fastlane inhouse`?

**Comment by xareelee** [comment]
Yeah, sure. Sorry about that.

```
/Users/Xaree/.rvm/gems/ruby-2.2.0@global/gems/fastlane_core-0.6.0/lib/fastlane_core/configuration/config_item.rb:49:in `is_valid?': 'ipa' value must be a String! (RuntimeError)
	from /Users/Xaree/.rvm/gems/ruby-2.2.0@global/gems/fastlane_core-0.6.0/lib/fastlane_core/configuration/config_item.rb:39:in `verify!'
	from /Users/Xaree/.rvm/gems/ruby-2.2.0@global/gems/fastlane_core-0.6.0/lib/fastlane_core/configuration.rb:116:in `set'
	from /Users/Xaree/.rvm/gems/ruby-2.2.0@global/gems/shenzhen-0.13.2/lib/shenzhen/plugins/hockeyapp.rb:23:in `upload_build'
	from /Users/Xaree/.rvm/gems/ruby-2.2.0@global/gems/fastlane-0.12.1/lib/fastlane/actions/hockey.rb:39:in `run'
	from /Users/Xaree/.rvm/gems/ruby-2.2.0@global/gems/fastlane-0.12.1/lib/fastlane/fast_file.rb:112:in `block (2 levels) in method_missing'
	from /Users/Xaree/.rvm/gems/ruby-2.2.0@global/gems/fastlane-0.12.1/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Users/Xaree/.rvm/gems/ruby-2.2.0@global/gems/fastlane-0.12.1/lib/fastlane/fast_file.rb:94:in `block in method_missing'
	from /Users/Xaree/.rvm/gems/ruby-2.2.0@global/gems/fastlane-0.12.1/lib/fastlane/fast_file.rb:93:in `chdir'
	from /Users/Xaree/.rvm/gems/ruby-2.2.0@global/gems/fastlane-0.12.1/lib/fastlane/fast_file.rb:93:in `method_missing'
	from (eval):77:in `block (3 levels) in parse'
	from /Users/Xaree/.rvm/gems/ruby-2.2.0@global/gems/fastlane-0.12.1/lib/fastlane/runner.rb:34:in `call'
	from /Users/Xaree/.rvm/gems/ruby-2.2.0@global/gems/fastlane-0.12.1/lib/fastlane/runner.rb:34:in `block in execute'
	from /Users/Xaree/.rvm/gems/ruby-2.2.0@global/gems/fastlane-0.12.1/lib/fastlane/runner.rb:24:in `chdir'
	from /Users/Xaree/.rvm/gems/ruby-2.2.0@global/gems/fastlane-0.12.1/lib/fastlane/runner.rb:24:in `execute'
	from /Users/Xaree/.rvm/gems/ruby-2.2.0@global/gems/fastlane-0.12.1/lib/fastlane/lane_manager.rb:33:in `cruise_lane'
	from /Users/Xaree/.rvm/gems/ruby-2.2.0@global/gems/fastlane-0.12.1/bin/fastlane:39:in `block (2 levels) in run'
	from /Users/Xaree/.rvm/gems/ruby-2.2.0@global/gems/commander-4.3.2/lib/commander/command.rb:178:in `call'
	from /Users/Xaree/.rvm/gems/ruby-2.2.0@global/gems/commander-4.3.2/lib/commander/command.rb:178:in `call'
	from /Users/Xaree/.rvm/gems/ruby-2.2.0@global/gems/commander-4.3.2/lib/commander/command.rb:153:in `run'
	from /Users/Xaree/.rvm/gems/ruby-2.2.0@global/gems/commander-4.3.2/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/Xaree/.rvm/gems/ruby-2.2.0@global/gems/commander-4.3.2/lib/commander/runner.rb:68:in `run!'
	from /Users/Xaree/.rvm/gems/ruby-2.2.0@global/gems/commander-4.3.2/lib/commander/delegates.rb:15:in `run!'
	from /Users/Xaree/.rvm/gems/ruby-2.2.0@global/gems/fastlane-0.12.1/bin/fastlane:118:in `run'
	from /Users/Xaree/.rvm/gems/ruby-2.2.0@global/gems/fastlane-0.12.1/bin/fastlane:124:in `<top (required)>'
	from /Users/Xaree/.rvm/rubies/ruby-2.2.0/bin/fastlane:23:in `load'
	from /Users/Xaree/.rvm/rubies/ruby-2.2.0/bin/fastlane:23:in `<main>'
	from /Users/Xaree/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/Xaree/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by JaniJegoroff** [comment]
I see the same issue with versions 0.12.0 and 0.12.1. 
IPA is uploaded successfully to iTunesConnect but to HockeyApp.

**Comment by KrauseFx** [comment]
Thanks, I just fixed the issue and will publish a new release in a few minutes :+1:

**Comment by KrauseFx** [comment]
Please update using `sudo gem update fastlane` and let me know if that fixes your problem :+1: 

Sorry for the troubles.

**Comment by JaniJegoroff** [comment]
Fixed! :+1:

**Comment by xareelee** [comment]
Just update it and it works well. Thanks for your great job! :+1:

**Comment by KrauseFx** [comment]
Yeah! Great to hear, and thanks again for reporting.

:rocket:
