### ISSUE TITLE
Error when running fastlane

### ISSUE THREAD

**Issue by barrettj** [KrauseFx/fastlane#215]
I get the following error when attempting to run fastlane:

```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:2007:in `raise_if_conflicts': Unable to activate cupertino-1.3.3, because highline-1.6.21 conflicts with highline (>= 1.7.1) (Gem::LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1176:in `activate'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1212:in `block in activate_dependencies'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1198:in `each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1198:in `activate_dependencies'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1180:in `activate'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_gem.rb:48:in `gem'
	from /usr/bin/fastlane:22:in `<main>'
```

This after doing a sudo gem update fastlane (I was previously running 0.5 I believe)

**Comment by KrauseFx** [comment]
Can you run `sudo gem update`, which will update all your dependencies?

**Comment by barrettj** [comment]
That seems to have fixed it, thanks!
