### ISSUE TITLE
Error when loading custom actions

### ISSUE THREAD

**Issue by jhuggart** [KrauseFx/fastlane#217]
I defined a few custom actions. None of them are working after upgrading to fastlane 0.12.3.

I get a `NoMethodError: undefined method 'action_name' for Fastlane::Actions::MyCustomAction::Class`
whenever I try to run the action.

Here is the stack trace:
```
FATAL [2015-04-20 13:29:20.09]: fastlane finished with errors
(eval):100:in `block (2 levels) in parse': undefined method `any?' for nil:NilClass (NoMethodError)
        from gemset_dir/fastlane-0.12.3/lib/fastlane/runner.rb:50:in `call'
        from gemset_dir/fastlane-0.12.3/lib/fastlane/runner.rb:50:in `block in execute'
        from gemset_dir/fastlane-0.12.3/lib/fastlane/runner.rb:45:in `chdir'
        from gemset_dir/fastlane-0.12.3/lib/fastlane/runner.rb:45:in `rescue in execute'
        from gemset_dir/fastlane-0.12.3/lib/fastlane/runner.rb:8:in `execute'
        from gemset_dir/fastlane-0.12.3/lib/fastlane/lane_manager.rb:33:in `cruise_lane'
        from gemset_dir/fastlane-0.12.3/bin/fastlane:39:in `block (2 levels) in run'
        from gemset_dir/commander-4.3.2/lib/commander/command.rb:178:in `call'
        from gemset_dir/commander-4.3.2/lib/commander/command.rb:178:in `call'
        from gemset_dir/commander-4.3.2/lib/commander/command.rb:153:in `run'
        from gemset_dir/commander-4.3.2/lib/commander/runner.rb:428:in `run_active_command'
        from gemset_dir/commander-4.3.2/lib/commander/runner.rb:68:in `run!'
        from gemset_dir/commander-4.3.2/lib/commander/delegates.rb:15:in `run!'
        from gemset_dir/fastlane-0.12.3/bin/fastlane:118:in `run'
        from gemset_dir/fastlane-0.12.3/bin/fastlane:124:in `<top (required)>'
        from bin_dir/fastlane:23:in `load'
        from bin_dir/fastlane:23:in `<main>'
        from bin_dir/ruby_executable_hooks:15:in `eval'
        from bin_dir/ruby_executable_hooks:15:in `<main>'
```

Do I need to modify my actions in some way so that they work with the latest release? Thanks!

**Comment by jhuggart** [comment]
Looks like I just need to inherit from the Fastlane::Action class.

**Comment by KrauseFx** [comment]
I'll update `fastlane` to not crash if that happens :+1:

**Comment by KrauseFx** [comment]
The stack trace you posted is actually an error on your `Fastfile`

**Comment by jhuggart** [comment]
Oh yeah, you're right. It looks like it's swallowing the exception that I posted. The stack trace is caused by calling .any on a nil object in the error lane. Not inheriting from Fastlane::Action in my custom actions is still an issue though.

**Comment by KrauseFx** [comment]
Yep, just pushed a fix :+1:

**Comment by jhuggart** [comment]
Awesome. Thanks!
