### ISSUE TITLE
`raise_if_conflicts': can't activate mime-types

### ISSUE THREAD

**Issue by eytanbiala** [KrauseFx/fastlane#224]
I just upgraded to fastlane 0.12.0 and made the necessary migrations for the new config system.
When I try to run a lane now, I am seeing this error:

```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1995:in `raise_if_conflicts': can't activate mime-types-2.4.3, already activated mime-types-1.25.1 (Gem::LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1176:in `activate'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems.rb:204:in `block in finish_resolve'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems.rb:203:in `each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems.rb:203:in `finish_resolve'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/rdoc.rb:14:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/commands/update_command.rb:9:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.12.4/lib/fastlane/actions/update_fastlane.rb:2:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.12.4/lib/fastlane/actions/actions_helper.rb:96:in `block in load_default_actions'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.12.4/lib/fastlane/actions/actions_helper.rb:95:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.12.4/lib/fastlane/actions/actions_helper.rb:95:in `load_default_actions'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.12.4/lib/fastlane.rb:21:in `<module:Fastlane>'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.12.4/lib/fastlane.rb:18:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.12.4/bin/fastlane:5:in `<top (required)>'
	from /usr/bin/fastlane:23:in `load'
	from /usr/bin/fastlane:23:in `<main>
```

I'm not too familiar with Ruby, but do I need to downgrade a gem to make fastlane work?

**Comment by KrauseFx** [comment]
Can you try: `sudo gem update`

**Comment by eytanbiala** [comment]
Sorry should have mentioned I tried doing that, everything is up to date:
```
Updating installed gems
Nothing to update
```

**Comment by eytanbiala** [comment]
I ran `sudo gem cleanup` to remove old gem versions, and then fastlane worked :+1:

**Comment by robwithhair** [comment]
I had the same issue giving me the following error.  `sudo gem cleanup` also seems to have fixed it for me.

```
buildserver:iOS robwithhair$ fastlane deploy
/Library/Ruby/Site/2.0.0/rubygems/specification.rb:2100:in `check_version_conflict': can't activate mime-types-2.5, already activated mime-types-1.25.1 (Gem::LoadError)
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:1276:in `activate'
	from /Library/Ruby/Site/2.0.0/rubygems.rb:216:in `block in finish_resolve'
	from /Library/Ruby/Site/2.0.0/rubygems.rb:215:in `each'
	from /Library/Ruby/Site/2.0.0/rubygems.rb:215:in `finish_resolve'
	from /Library/Ruby/Site/2.0.0/rubygems/rdoc.rb:14:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:121:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:121:in `require'
		from /Library/Ruby/Site/2.0.0/rubygems/commands/update_command.rb:9:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:121:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:121:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.12.5/lib/fastlane/actions/update_fastlane.rb:2:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:121:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:121:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.12.5/lib/fastlane/actions/actions_helper.rb:96:in `block in load_default_actions'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.12.5/lib/fastlane/actions/actions_helper.rb:95:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.12.5/lib/fastlane/actions/actions_helper.rb:95:in `load_default_actions'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.12.5/lib/fastlane.rb:21:in `<module:Fastlane>'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.12.5/lib/fastlane.rb:18:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.12.5/bin/fastlane:5:in `<top (required)>'
	from /usr/bin/fastlane:23:in `load'
	from /usr/bin/fastlane:23:in `<main>'
```

Thanks for your post.  @KrauseFx sorry to bother you Felix.
