### ISSUE TITLE
Fasten lane_manager No live threads left Deadlock?

### ISSUE THREAD

**Issue by doozMen** [KrauseFx/fastlane#240]
Hei I get stage error above. This is after updating to fastlane 0.12.5. I updated all the gems but not sure what the problem is.

```
/Library/Ruby/Gems/2.0.0/gems/fastlane-0.12.5/lib/fastlane/lane_manager.rb:57:in `join': No live threads left. Deadlock? (fatal)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.12.5/lib/fastlane/lane_manager.rb:57:in `finish_fastlane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.12.5/lib/fastlane/lane_manager.rb:43:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.12.5/bin/fastlane:39:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.3/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.3/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.3/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.3/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.3/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.3/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.12.5/bin/fastlane:118:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.12.5/bin/fastlane:124:in `<top (required)>'
	from /usr/bin/fastlane:23:in `load'
	from /usr/bin/fastlane:23:in `<main>'

```

**Comment by KrauseFx** [comment]
Fixed with the next version, thanks for reporting :+1:

**Comment by doozMen** [comment]
Thanks man will try Tomorrow.

**Comment by bkockx** [comment]
Fix was not working for us. I created a pull request with a new fix.
https://travis-ci.org/KrauseFx/fastlane/builds/61267159

**Comment by KrauseFx** [comment]
Thank you @bkockx :+1:
