### ISSUE TITLE
can't activate mime-types-2.5, already activated mime-types-1.25.1 (Gem::LoadError)

### ISSUE THREAD

**Issue by brookstalley** [KrauseFx/fastlane#249]
Did a gem update and got fasten 0.12.5; pretty sure this was working before.

The full error trace is:

```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1995:in `raise_if_conflicts': can't activate mime-types-2.5, already activated mime-types-1.25.1 (Gem::LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1176:in `activate'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems.rb:204:in `block in finish_resolve'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems.rb:203:in `each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems.rb:203:in `finish_resolve'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/rdoc.rb:14:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/commands/update_command.rb:9:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.12.5/lib/fastlane/actions/update_fastlane.rb:2:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.12.5/lib/fastlane/actions/actions_helper.rb:96:in `block in load_default_actions'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.12.5/lib/fastlane/actions/actions_helper.rb:95:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.12.5/lib/fastlane/actions/actions_helper.rb:95:in `load_default_actions'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.12.5/lib/fastlane.rb:21:in `<module:Fastlane>'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.12.5/lib/fastlane.rb:18:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.12.5/bin/fastlane:5:in `<top (required)>'
	from /usr/bin/fastlane:23:in `load'
	from /usr/bin/fastlane:23:in `<main>'
```

**Comment by eytanbiala** [comment]
Try `sudo gem cleanup`. See #224

**Comment by brookstalley** [comment]
How did I miss that? Sorry for the dupe, and yep that fixed it.

**Comment by eytanbiala** [comment]
No problem, glad it worked!
