### ISSUE TITLE
Login not working

### ISSUE THREAD

**Issue by iMstr** [KrauseFx/fastlane#266]
Fastlane worked fine till a hour ago we saw the login to fail while the password is correct. The debug gave us the following error:
`DEBUG [2015-05-06 19:20:06.35]: Couldn't find element '.homepageWrapper.ng-scope' after waiting for quite some time`

**Comment by KrauseFx** [comment]
Strange: https://github.com/KrauseFx/produce/issues/35

Have you tried turning it off and on again? Not sure what's causing this random error.

**Comment by iMstr** [comment]
Will try, we noticed the terminal was using a lot of memory after running fastlane like 40 times. Even when all windows were closed it stayed. Maybe something in there caused this.

**Comment by iMstr** [comment]
Still there :disappointed:
```
INFO [2015-05-06 19:44:20.07]: Logging into iTunesConnect
DEBUG [2015-05-06 19:44:50.03]: ["/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.7.2/lib/fastlane_core/itunes_connect/itunes_connect_login.rb:42:in `login'", "/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.7.2/lib/fastlane_core/itunes_connect/itunes_connect.rb:62:in `initialize'", "/Library/Ruby/Gems/2.0.0/gems/produce-0.2.1/lib/produce/manager.rb:8:in `new'", "/Library/Ruby/Gems/2.0.0/gems/produce-0.2.1/lib/produce/manager.rb:8:in `start_producing'", "/Library/Ruby/Gems/2.0.0/gems/fastlane-1.0.1/lib/fastlane/actions/produce.rb:28:in `block in run'", "/Library/Ruby/Gems/2.0.0/gems/fastlane-1.0.1/lib/fastlane/actions/produce.rb:22:in `chdir'", "/Library/Ruby/Gems/2.0.0/gems/fastlane-1.0.1/lib/fastlane/actions/produce.rb:22:in `run'", "/Library/Ruby/Gems/2.0.0/gems/fastlane-1.0.1/lib/fastlane/fast_file.rb:112:in `block (2 levels) in method_missing'", "/Library/Ruby/Gems/2.0.0/gems/fastlane-1.0.1/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'", "/Library/Ruby/Gems/2.0.0/gems/fastlane-1.0.1/lib/fastlane/fast_file.rb:94:in `block in method_missing'", "/Library/Ruby/Gems/2.0.0/gems/fastlane-1.0.1/lib/fastlane/fast_file.rb:93:in `chdir'", "/Library/Ruby/Gems/2.0.0/gems/fastlane-1.0.1/lib/fastlane/fast_file.rb:93:in `method_missing'", "(eval):33:in `block (2 levels) in parse'", "/Library/Ruby/Gems/2.0.0/gems/fastlane-1.0.1/lib/fastlane/runner.rb:34:in `call'", "/Library/Ruby/Gems/2.0.0/gems/fastlane-1.0.1/lib/fastlane/runner.rb:34:in `block in execute'", "/Library/Ruby/Gems/2.0.0/gems/fastlane-1.0.1/lib/fastlane/runner.rb:24:in `chdir'", "/Library/Ruby/Gems/2.0.0/gems/fastlane-1.0.1/lib/fastlane/runner.rb:24:in `execute'", "/Library/Ruby/Gems/2.0.0/gems/fastlane-1.0.1/lib/fastlane/lane_manager.rb:33:in `cruise_lane'", "/Library/Ruby/Gems/2.0.0/gems/fastlane-1.0.1/bin/fastlane:39:in `block (2 levels) in run'", "/Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'", "/Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'", "/Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:153:in `run'", "/Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/runner.rb:428:in `run_active_command'", "/Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/runner.rb:68:in `run!'", "/Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/delegates.rb:15:in `run!'", "/Library/Ruby/Gems/2.0.0/gems/fastlane-1.0.1/bin/fastlane:118:in `run'", "/Library/Ruby/Gems/2.0.0/gems/fastlane-1.0.1/bin/fastlane:124:in `<top (required)>'", "/usr/bin/fastlane:23:in `load'", "/usr/bin/fastlane:23:in `<main>'"]
DEBUG [2015-05-06 19:44:50.03]: Couldn't find element '.homepageWrapper.ng-scope' after waiting for quite some time
The file /Volumes/Data/Apps/sfdja/fastlane/Error1430934290.png does not exist.
```

**Comment by KrauseFx** [comment]
I wonder why you don't get a screenshot. I'll take a closer look later.

**Comment by iMstr** [comment]
3 days later it magicly started to work! Thanks anyway.

**Comment by KrauseFx** [comment]
:+1:

**Comment by kylejm** [comment]
I'm having a similar issue to this now @KrauseFx. It worked this morning but now I keep getting:

```
Couldn't find element '.ng-scope' after waiting for quite some time
```
Is this some issue that's cause by a state that iTunes Connect temporarily gets into??


Here's all the other stuff that was spat out if that helps:

```ruby
[18:57:47]: ["/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fastlane_core-0.15.0/lib/fastlane_core/itunes_connect/itunes_connect_login.rb:41:in `login'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fastlane_core-0.15.0/lib/fastlane_core/itunes_connect/itunes_connect.rb:62:in `initialize'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/deliver-0.13.1/lib/deliver/app.rb:49:in `new'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/deliver-0.13.1/lib/deliver/app.rb:49:in `rescue in initialize'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/deliver-0.13.1/lib/deliver/app.rb:44:in `initialize'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/deliver-0.13.1/lib/deliver/deliver_process.rb:80:in `new'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/deliver-0.13.1/lib/deliver/deliver_process.rb:80:in `app'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/deliver-0.13.1/lib/deliver/deliver_process.rb:385:in `trigger_ipa_upload'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/deliver-0.13.1/lib/deliver/deliver_process.rb:48:in `run'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/deliver-0.13.1/lib/deliver/deliverer.rb:135:in `finished_executing_deliver_file'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/deliver-0.13.1/lib/deliver/deliverfile/deliverfile.rb:31:in `initialize'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/deliver-0.13.1/lib/deliver/deliverer.rb:87:in `new'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/deliver-0.13.1/lib/deliver/deliverer.rb:87:in `initialize'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fastlane-1.21.0/lib/fastlane/actions/deliver.rb:21:in `new'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fastlane-1.21.0/lib/fastlane/actions/deliver.rb:21:in `block in run'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fastlane-1.21.0/lib/fastlane/actions/deliver.rb:17:in `chdir'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fastlane-1.21.0/lib/fastlane/actions/deliver.rb:17:in `run'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fastlane-1.21.0/lib/fastlane/runner.rb:142:in `block (2 levels) in execute_action'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fastlane-1.21.0/lib/fastlane/actions/actions_helper.rb:37:in `execute_action'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fastlane-1.21.0/lib/fastlane/runner.rb:128:in `block in execute_action'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fastlane-1.21.0/lib/fastlane/runner.rb:127:in `chdir'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fastlane-1.21.0/lib/fastlane/runner.rb:127:in `execute_action'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fastlane-1.21.0/lib/fastlane/fast_file.rb:124:in `method_missing'", "(eval):48:in `block (3 levels) in parse'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fastlane-1.21.0/lib/fastlane/lane.rb:36:in `call'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fastlane-1.21.0/lib/fastlane/lane.rb:36:in `call'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fastlane-1.21.0/lib/fastlane/runner.rb:51:in `block in execute'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fastlane-1.21.0/lib/fastlane/runner.rb:46:in `chdir'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fastlane-1.21.0/lib/fastlane/runner.rb:46:in `execute'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fastlane-1.21.0/lib/fastlane/lane_manager.rb:43:in `cruise_lane'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fastlane-1.21.0/lib/fastlane/command_line_handler.rb:31:in `handle'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fastlane-1.21.0/bin/fastlane:34:in `block (2 levels) in run'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:71:in `run!'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fastlane-1.21.0/bin/fastlane:123:in `run'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fastlane-1.21.0/bin/fastlane:129:in `<top (required)>'", "/Users/kylejm/.rbenv/versions/2.2.0/bin/fastlane:23:in `load'", "/Users/kylejm/.rbenv/versions/2.2.0/bin/fastlane:23:in `<main>'"]
[18:58:07]: ["/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fastlane_core-0.15.0/lib/fastlane_core/itunes_connect/itunes_connect_login.rb:42:in `login'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fastlane_core-0.15.0/lib/fastlane_core/itunes_connect/itunes_connect.rb:62:in `initialize'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/deliver-0.13.1/lib/deliver/app.rb:49:in `new'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/deliver-0.13.1/lib/deliver/app.rb:49:in `rescue in initialize'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/deliver-0.13.1/lib/deliver/app.rb:44:in `initialize'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/deliver-0.13.1/lib/deliver/deliver_process.rb:80:in `new'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/deliver-0.13.1/lib/deliver/deliver_process.rb:80:in `app'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/deliver-0.13.1/lib/deliver/deliver_process.rb:385:in `trigger_ipa_upload'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/deliver-0.13.1/lib/deliver/deliver_process.rb:48:in `run'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/deliver-0.13.1/lib/deliver/deliverer.rb:135:in `finished_executing_deliver_file'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/deliver-0.13.1/lib/deliver/deliverfile/deliverfile.rb:31:in `initialize'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/deliver-0.13.1/lib/deliver/deliverer.rb:87:in `new'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/deliver-0.13.1/lib/deliver/deliverer.rb:87:in `initialize'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fastlane-1.21.0/lib/fastlane/actions/deliver.rb:21:in `new'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fastlane-1.21.0/lib/fastlane/actions/deliver.rb:21:in `block in run'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fastlane-1.21.0/lib/fastlane/actions/deliver.rb:17:in `chdir'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fastlane-1.21.0/lib/fastlane/actions/deliver.rb:17:in `run'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fastlane-1.21.0/lib/fastlane/runner.rb:142:in `block (2 levels) in execute_action'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fastlane-1.21.0/lib/fastlane/actions/actions_helper.rb:37:in `execute_action'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fastlane-1.21.0/lib/fastlane/runner.rb:128:in `block in execute_action'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fastlane-1.21.0/lib/fastlane/runner.rb:127:in `chdir'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fastlane-1.21.0/lib/fastlane/runner.rb:127:in `execute_action'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fastlane-1.21.0/lib/fastlane/fast_file.rb:124:in `method_missing'", "(eval):48:in `block (3 levels) in parse'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fastlane-1.21.0/lib/fastlane/lane.rb:36:in `call'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fastlane-1.21.0/lib/fastlane/lane.rb:36:in `call'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fastlane-1.21.0/lib/fastlane/runner.rb:51:in `block in execute'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fastlane-1.21.0/lib/fastlane/runner.rb:46:in `chdir'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fastlane-1.21.0/lib/fastlane/runner.rb:46:in `execute'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fastlane-1.21.0/lib/fastlane/lane_manager.rb:43:in `cruise_lane'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fastlane-1.21.0/lib/fastlane/command_line_handler.rb:31:in `handle'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fastlane-1.21.0/bin/fastlane:34:in `block (2 levels) in run'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:71:in `run!'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fastlane-1.21.0/bin/fastlane:123:in `run'", "/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fastlane-1.21.0/bin/fastlane:129:in `<top (required)>'", "/Users/kylejm/.rbenv/versions/2.2.0/bin/fastlane:23:in `load'", "/Users/kylejm/.rbenv/versions/2.2.0/bin/fastlane:23:in `<main>'"]
```

**Comment by KrauseFx** [comment]
@kylejm I assume your error message came from the `deliver` project?

**Comment by kylejm** [comment]
Yes :)

**Comment by alexargo** [comment]
I'm getting this in codes as well:

```codes -x download 25
[01:14:19]: Logging into iTunesConnect
[01:14:46]: ["/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.15.0/lib/fastlane_core/itunes_connect/itunes_connect_login.rb:41:in `login'", "/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.15.0/lib/fastlane_core/itunes_connect/itunes_connect.rb:62:in `initialize'", "/Library/Ruby/Gems/2.0.0/gems/codes-0.2.2/lib/codes/codes_runner.rb:4:in `new'", "/Library/Ruby/Gems/2.0.0/gems/codes-0.2.2/lib/codes/codes_runner.rb:4:in `run'", "/Library/Ruby/Gems/2.0.0/gems/codes-0.2.2/bin/codes:43:in `block (2 levels) in run'", "/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'", "/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'", "/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'", "/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'", "/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'", "/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'", "/Library/Ruby/Gems/2.0.0/gems/codes-0.2.2/bin/codes:78:in `run'", "/Library/Ruby/Gems/2.0.0/gems/codes-0.2.2/bin/codes:85:in `<top (required)>'", "/usr/bin/codes:23:in `load'", "/usr/bin/codes:23:in `<main>'"]
[01:15:07]: ["/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.15.0/lib/fastlane_core/itunes_connect/itunes_connect_login.rb:42:in `login'", "/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.15.0/lib/fastlane_core/itunes_connect/itunes_connect.rb:62:in `initialize'", "/Library/Ruby/Gems/2.0.0/gems/codes-0.2.2/lib/codes/codes_runner.rb:4:in `new'", "/Library/Ruby/Gems/2.0.0/gems/codes-0.2.2/lib/codes/codes_runner.rb:4:in `run'", "/Library/Ruby/Gems/2.0.0/gems/codes-0.2.2/bin/codes:43:in `block (2 levels) in run'", "/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'", "/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'", "/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'", "/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'", "/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'", "/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'", "/Library/Ruby/Gems/2.0.0/gems/codes-0.2.2/bin/codes:78:in `run'", "/Library/Ruby/Gems/2.0.0/gems/codes-0.2.2/bin/codes:85:in `<top (required)>'", "/usr/bin/codes:23:in `load'", "/usr/bin/codes:23:in `<main>'"]
[01:15:07]: Couldn't find element '.ng-scope' after waiting for quite some time
/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.15.0/lib/fastlane_core/itunes_connect/itunes_connect_login.rb:55:in `rescue in login': Error logging in user admin@astarsoftware.com with the given password. Make sure you entered them correctly. (FastlaneCore::ItunesConnect::ItunesConnectLoginError)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.15.0/lib/fastlane_core/itunes_connect/itunes_connect_login.rb:40:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.15.0/lib/fastlane_core/itunes_connect/itunes_connect.rb:62:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/codes-0.2.2/lib/codes/codes_runner.rb:4:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/codes-0.2.2/lib/codes/codes_runner.rb:4:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/codes-0.2.2/bin/codes:43:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/codes-0.2.2/bin/codes:78:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/codes-0.2.2/bin/codes:85:in `<top (required)>'
	from /usr/bin/codes:23:in `load'
	from /usr/bin/codes:23:in `<main>'
```

**Comment by alexargo** [comment]
Also getting this error in latest version of deliver.

**Comment by aloifolia** [comment]
@KrauseFx I am seeing the same error message as @alexargo does, here (also, for deliver). I get this screenshot:
![fastlane](https://cloud.githubusercontent.com/assets/1295054/9516598/f49b8db4-4ca9-11e5-8c34-5eddcfdd890c.png)

**Comment by JohannesNevels** [comment]
I also experience the same issue!

**Comment by sandman4sure** [comment]
same issue here! Same screenshot as well.

**Comment by zeroel** [comment]
@KrauseFx I also get a same error message as @aloifolia and @alexargo. Deliver were working fine yesterday.
Please help to fix, Thanks!

**Comment by gamlin777** [comment]
I'm getting this issue as well. It's definitely not a login credentials issue either.

**Comment by KrauseFx** [comment]
Sorry for the troubles. I'm working on a new version of `deliver` https://github.com/KrauseFx/deliver/pull/259 which fixes all these problems by upgrading to `spaceship`.

If you only want to upload a binary, you can always use the new [pilot](https://github.com/fastlane/pilot) tool :+1:

**Comment by KrauseFx** [comment]
Moving further discussion to https://github.com/KrauseFx/deliver/issues/315

**Comment by KrauseFx** [comment]
Please update using `sudo gem update fastlane_core` @alexargo @gamlin777 @zeroel @sandman4sure @JohannesNevels

**Comment by aloifolia** [comment]
@KrauseFx It works now, thank you!

**Comment by KrauseFx** [comment]
https://github.com/KrauseFx/deliver/releases/tag/1.0.0.beta :rocket:
