### ISSUE TITLE
Reference XCode variable in actions

### ISSUE THREAD

**Issue by sarunw** [KrauseFx/fastlane#27]
I used to have run script created in build phase which reference XCode variable like $INFOPLIST_FILE. If I want to move this code to custom action, can I still reference these variable?

**Comment by KrauseFx** [comment]
Sorry, I don't quite understand this. You want to create your own action? Or you want to run your existing shell script?

**Comment by sarunw** [comment]
I want to move my existing script to actions, but in my script contains XCode variable can ruby code in actions access them?

**Comment by KrauseFx** [comment]
Are you talking about an `xcodebuild` command? Can you share your existing script?

**Comment by kdawgwilk** [comment]
I am trying to do the same thing and I couldn't get it to work so I tried to move it to an external script but it fails with permission denied

I try running:

```sh "./ipa.sh"```

which contains:

```
/usr/bin/xcrun -sdk iphoneos PackageApplication -v "${RELEASE_BUILDDIR}/${APPLICATION_NAME}.app" -o "${BUILD_HISTORY_DIR}/${APPLICATION_NAME}.ipa" --sign "${DEVELOPER_NAME}" --embed "${PROVISONING_PROFILE}"
```

in my fastlane actions for my lane and i get 

```
[SHELL COMMAND]: ./ipa.sh
INFO [2015-02-06 11:43:31.74]: Variable Dump:
INFO [2015-02-06 11:43:31.74]: {:LANE_NAME=>:beta, :START_TIME=>2015-02-06 11:42:01 -0700, :BUILD_NUMBER=>0, :SIGH_PROFILE_PATH=>"/path/to/app.mobileprovision"}
FATAL [2015-02-06 11:43:31.74]: Permission denied - fork failed
FATAL [2015-02-06 11:43:31.75]: fastlane finished with errors
```

**Comment by kdawgwilk** [comment]
Heres the trace where the error occurred
```
/Users/user/.rvm/gems/ruby-2.2.0@global/gems/fastlane-0.1.7/lib/fastlane/actions/actions_helper.rb:60:in `spawn': Permission denied - fork failed (Errno::EACCES)
	from /Users/user/.rvm/gems/ruby-2.2.0@global/gems/fastlane-0.1.7/lib/fastlane/actions/actions_helper.rb:60:in `sh_no_action'
	from /Users/user/.rvm/gems/ruby-2.2.0@global/gems/fastlane-0.1.7/lib/fastlane/fast_file.rb:60:in `block in sh'
	from /Users/user/.rvm/gems/ruby-2.2.0@global/gems/fastlane-0.1.7/lib/fastlane/actions/actions_helper.rb:29:in `execute_action'
	from /Users/user/.rvm/gems/ruby-2.2.0@global/gems/fastlane-0.1.7/lib/fastlane/fast_file.rb:59:in `sh'
	from (eval):24:in `block (2 levels) in parse'
	from /Users/user/.rvm/gems/ruby-2.2.0@global/gems/fastlane-0.1.7/lib/fastlane/runner.rb:13:in `call'
	from /Users/user/.rvm/gems/ruby-2.2.0@global/gems/fastlane-0.1.7/lib/fastlane/runner.rb:13:in `block in execute'
	from /Users/user/.rvm/gems/ruby-2.2.0@global/gems/fastlane-0.1.7/lib/fastlane/runner.rb:12:in `chdir'
	from /Users/user/.rvm/gems/ruby-2.2.0@global/gems/fastlane-0.1.7/lib/fastlane/runner.rb:12:in `execute'
	from /Users/user/.rvm/gems/ruby-2.2.0@global/gems/fastlane-0.1.7/lib/fastlane/lane_manager.rb:15:in `block in cruise_lanes'
	from /Users/user/.rvm/gems/ruby-2.2.0@global/gems/fastlane-0.1.7/lib/fastlane/lane_manager.rb:14:in `each'
	from /Users/user/.rvm/gems/ruby-2.2.0@global/gems/fastlane-0.1.7/lib/fastlane/lane_manager.rb:14:in `cruise_lanes'
	from /Users/user/.rvm/gems/ruby-2.2.0@global/gems/fastlane-0.1.7/bin/fastlane:31:in `block (2 levels) in run'
	from /Users/user/.rvm/gems/ruby-2.2.0@global/gems/commander-4.2.1/lib/commander/command.rb:180:in `call'
	from /Users/user/.rvm/gems/ruby-2.2.0@global/gems/commander-4.2.1/lib/commander/command.rb:180:in `call'
	from /Users/user/.rvm/gems/ruby-2.2.0@global/gems/commander-4.2.1/lib/commander/command.rb:155:in `run'
	from /Users/user/.rvm/gems/ruby-2.2.0@global/gems/commander-4.2.1/lib/commander/runner.rb:421:in `run_active_command'
	from /Users/user/.rvm/gems/ruby-2.2.0@global/gems/commander-4.2.1/lib/commander/runner.rb:81:in `run!'
	from /Users/user/.rvm/gems/ruby-2.2.0@global/gems/commander-4.2.1/lib/commander/delegates.rb:8:in `run!'
	from /Users/user/.rvm/gems/ruby-2.2.0@global/gems/fastlane-0.1.7/bin/fastlane:59:in `run'
	from /Users/user/.rvm/gems/ruby-2.2.0@global/gems/fastlane-0.1.7/bin/fastlane:63:in `<top (required)>'
	from /Users/user/.rvm/rubies/ruby-2.2.0/bin/fastlane:23:in `load'
	from /Users/user/.rvm/rubies/ruby-2.2.0/bin/fastlane:23:in `<main>'
	from /Users/user/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/user/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by KrauseFx** [comment]
Mh, not sure why it complains about the `$`. Maybe you can just run `puts system("your command")` instead of the `sh`?

**Comment by almassapargali** [comment]
Ok, there is a way of getting those variables from command like using following command:
```
xcodebuild -workspace Appease.xcworkspace -scheme Previews -showBuildSettings
```
and you'll get this:
![screen shot 2015-03-07 at 12 12 59 am](https://cloud.githubusercontent.com/assets/1816725/6530903/111edf28-c45f-11e4-9607-57dad1a96f55.png)

Though, I'm not convinced that `fastlane` should handle this. If all you need is $INFOPLIST_FILE, I'd suggest declare it inside that script (yep it's hardcode, but do we move infoplist around often?).

Hey, @kdawgwilk, maybe use `fastlane` actions to get an ipa?

**Comment by KrauseFx** [comment]
What's the current status here? I'll close the issue for now, feel free to re-open if you're still experiencing problems.
