### ISSUE TITLE
`fastlane lanes` fails

### ISSUE THREAD

**Issue by ide** [KrauseFx/fastlane#293]
Running `fastlane lanes` with the most recent version of fastlane fails with the following error. (This was in a directory that didn't have fastlane set up yet.)

```
ide:~$ fastlane --version
fastlane 1.1.0

ide:~$ fastlane lanes
/Library/Ruby/Gems/2.0.0/gems/fastlane-1.1.0/bin/fastlane:70:in `join': no implicit conversion of nil into String (TypeError)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.1.0/bin/fastlane:70:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.1.0/bin/fastlane:118:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.1.0/bin/fastlane:124:in `<top (required)>'
	from /usr/bin/fastlane:23:in `load'
	from /usr/bin/fastlane:23:in `<main>'
```

**Comment by KrauseFx** [comment]
Thanks @ide, I pushed a fix. It's only not working if you are in a directory with no `Fastfile`, right?

**Comment by ide** [comment]
Yes, it's fine if there's an empty Fastfile.
