### ISSUE TITLE
Fastlane + Jenkins issue

### ISSUE THREAD

**Issue by Nicorhns** [KrauseFx/fastlane#297]
Hi!

I'm running into a small problem using Fastlane (1.2.0) on Jenkins. I can't get the fastlane to build my project on Jenkins before manually creating an archive in Xcode first.

Example lane:
lane :BetaDevelop do
    increment_build_number
    commit_version_bump
    add_git_tag
    push_to_git_remote
    ipa({
        workspace: WORKSPACE_NAME,
        scheme: PROJECT_NAME,
        configuration:"BetaDevelop",
        ipa: IPA_NAME,
        clean: true,
        archive: true
    })

    hockey({
       api_token: HOCKEY_API_TOKEN,
       ipa: IPA_NAME,
       notify: "0",
       status: "1",
       notes: ""
    })
    splunk({
       api_key: SPLUNK_API_KEY,
       api_token: SPLUNK_API_TOKEN,
       ipa: IPA_NAME
    })
    clean_build_artifacts
end

Full Jenkins output:
https://gist.github.com/Nicorhns/555552bfc34efca2177d

**Comment by KrauseFx** [comment]
Please run
```
krausefx-ipa build -w "Project_Name.xcworkspace" -s "Project_Name" -c "BetaProduction" --ipa "Project_Name.ipa" --clean --archive --verbose
``` 

or 

```
krausefx-ipa build -w "Project_Name.xcworkspace" -s "Project_Name" -c "BetaProduction" --ipa "Project_Name.ipa" --clean --archive --verbose | xcpretty
```

The error is a build error. Probably related to code signing.

**Comment by Nicorhns** [comment]
Hi @KrauseFx,

Thanks for your fast response!
The commands you suggest seem to be exactly the same as the one my Fastlane installation produces.
Without changing anything, the lane runs perfectly fine after opening the project in Xcode on Jenkins and creating an archive first.

**Comment by reich** [comment]
Hi,

same thing here. 
Local on my machine can fastlane build an app, but if i try to build an app with Jenkins using the same configuration as on my mac, i see the error:

```
A build error occured. This can have many reasons, usually
it has something to do with code signing. The `ipa` action
uses `shenzhen` under the hood: https://github.com/nomad/shenzhen
```
Im sure, that this is not a code signing issue. Hint from @Nicorhns did the trick (thx!). I just opened a project (.xcodeproj) with Xcode and the error was gone.

Full output:
```
[15:00:24]: -----------------
[15:00:24]: --- Step: ipa ---
[15:00:24]: -----------------
[15:00:24]: set -o pipefail && krausefx-ipa build -c "Release" -s "Template" --clean --archive -m "./Certs/app.mobileprovision" --xcconfig "./xcconfigs/ReleaseConfig.xcconfig" --verbose | xcpretty
[15:00:24]: [SHELL COMMAND]: set -o pipefail && krausefx-ipa build -c "Release" -s "Template" --clean --archive -m "./Certs/app.mobileprovision" --xcconfig "./xcconfigs/ReleaseConfig.xcconfig" --verbose | xcpretty
[15:00:25]: -------------------------------------------------------
[15:00:25]: Original Error:
[15:00:25]:  => Exit status of command 'set -o pipefail && krausefx-ipa build -c "Release" -s "Template" --clean --archive -m "./Certs/app.mobileprovision" --xcconfig "./xcconfigs/ReleaseConfig.xcconfig" --verbose | xcpretty' was 256 instead of 0. 

[15:00:25]: A build error occured. This can have many reasons, usually
[15:00:25]: it has something to do with code signing. The `ipa` action
[15:00:25]: uses `shenzhen` under the hood: https://github.com/nomad/shenzhen
[15:00:25]: The command that was used by fastlane:
[15:00:25]: krausefx-ipa build -c "Release" -s "Template" --clean --archive -m "./Certs/app.mobileprovision" --xcconfig "./xcconfigs/ReleaseConfig.xcconfig" --verbose | xcpretty
[15:00:25]: -------------------------------------------------------
[15:00:25]: [SHELL COMMAND]: echo A build error occured, this is usually related to code signing. Take 
/Library/Ruby/Gems/2.0.0/gems/fastlane-1.3.0/lib/fastlane/actions/ipa.rb:94:in `rescue in run': A build error occured, this is usually related to code signing. Take a look at the error above (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.3.0/lib/fastlane/actions/ipa.rb:66:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.3.0/lib/fastlane/fast_file.rb:112:in `block (2 levels) in method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.3.0/lib/fastlane/actions/actions_helper.rb:51:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.3.0/lib/fastlane/fast_file.rb:94:in `block in method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.3.0/lib/fastlane/fast_file.rb:93:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.3.0/lib/fastlane/fast_file.rb:93:in `method_missing'
	from (eval):179:in `block (3 levels) in parse'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.3.0/lib/fastlane/runner.rb:35:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.3.0/lib/fastlane/runner.rb:35:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.3.0/lib/fastlane/runner.rb:25:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.3.0/lib/fastlane/runner.rb:25:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.3.0/lib/fastlane/lane_manager.rb:33:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.3.0/bin/fastlane:39:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.3.0/bin/fastlane:118:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.3.0/bin/fastlane:124:in `<top (required)>'
	from /usr/bin/fastlane:23:in `load'
	from /usr/bin/fastlane:23:in `<main>'
[15:00:25]: Variable Dump:
[15:00:25]: {:DEFAULT_PLATFORM=>:ios, :ENVIRONMENT=>nil, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios abc", :SIGH_PROFILE_PATH=>"/Users/jenkinsuser/.jenkins/jobs/Autodeploy TEST/workspace/Certs/app.mobileprovision", :SIGH_UDID=>"ed913a85-dd97-429e-b744-d67db6b1db8e"}
[15:00:25]: A build error occured, this is usually related to code signing. Take a look at the error above
[15:00:25]: fastlane finished with errors
Build step 'Shell ausführen' marked build as failure
Finished: FAILURE
```

**Comment by KrauseFx** [comment]
So that's an issue of the way Jenkins launches threads, right? When you manually run `fastlane` it works? 

Are you running Jenkins as its own user or admin user?

**Comment by Nicorhns** [comment]
Could it have something to do with provisioning profiles being set in xcconfig's instead of in the project file directly?
I don't have access to our Jenkins atm, so can't check.

**Comment by reich** [comment]
Hi,

well, it was not problem of Jenkins/Fastlane or setting provisioning profile in xcconfig. Scheme in Xcode was not shared -> shenzhen couldn't find the scheme, same thing with xcodebuild and xctool. If i run Xcode on Jenkins server, then .xcscheme will be created, therefore hint from @Nicorhns works.

**Comment by Nicorhns** [comment]
Aha, that does seem to fix the problem! Thx @reich !
@KrauseFx, issue can be closed, thanks again for your great work on Fastlane.
