### ISSUE TITLE
sigh 0.2.2 update breaks fastlane

### ISSUE THREAD

**Issue by jingx23** [KrauseFx/fastlane#30]
```
FATAL [2015-02-04 21:53:16.42]: uninitialized constant Sigh::DeveloperCenter::Phantomjs
FATAL [2015-02-04 21:53:16.42]: fastlane finished with errors
/Library/Ruby/Gems/2.0.0/gems/sigh-0.2.2/lib/sigh/developer_center.rb:45:in `block in initialize': uninitialized constant Sigh::DeveloperCenter::Phantomjs (NameError)
	from /Library/Ruby/Gems/2.0.0/gems/capybara-2.4.4/lib/capybara/session.rb:79:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/capybara-2.4.4/lib/capybara/session.rb:79:in `driver'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-0.2.2/lib/sigh/developer_center.rb:52:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.6/lib/fastlane/actions/sigh.rb:21:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.6/lib/fastlane/actions/sigh.rb:21:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.6/lib/fastlane/fast_file.rb:81:in `block (2 levels) in method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.6/lib/fastlane/actions/actions_helper.rb:28:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.6/lib/fastlane/fast_file.rb:80:in `block in method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.6/lib/fastlane/fast_file.rb:79:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.6/lib/fastlane/fast_file.rb:79:in `method_missing'
	from (eval):21:in `block (2 levels) in parse'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.6/lib/fastlane/runner.rb:17:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.6/lib/fastlane/runner.rb:17:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.6/lib/fastlane/runner.rb:11:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.6/lib/fastlane/runner.rb:11:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.6/lib/fastlane/lane_manager.rb:15:in `block in cruise_lanes'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.6/lib/fastlane/lane_manager.rb:14:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.6/lib/fastlane/lane_manager.rb:14:in `cruise_lanes'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.6/bin/fastlane:31:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.2.0/lib/commander/command.rb:180:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.2.0/lib/commander/command.rb:180:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.2.0/lib/commander/command.rb:155:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.2.0/lib/commander/runner.rb:421:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.2.0/lib/commander/runner.rb:81:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.2.0/lib/commander/delegates.rb:8:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.6/bin/fastlane:59:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.6/bin/fastlane:63:in `<top (required)>'
	from /usr/bin/fastlane:23:in `load'
	from /usr/bin/fastlane:23:in `<main>'
```

**Comment by KrauseFx** [comment]
That's strange, is this the full output? What command did you use?

**Comment by jingx23** [comment]
Ehm of course sry:
Reproduction info:
I updated sigh (sudo gem update sigh)
my beta lane looks like this:

lane :beta do
    sigh
    deliver :skip_deploy, :beta
end

You see i run sigh without additional parameters.

The complete output looks like this:
    
fastlane beta
INFO [2015-02-04 21:53:13.29]: Driving the lane 'beta'
INFO [2015-02-04 21:53:13.29]: Step: sigh
INFO [2015-02-04 21:53:16.42]: Variable Dump:
INFO [2015-02-04 21:53:16.42]: {:LANE_NAME=>:beta}
FATAL [2015-02-04 21:53:16.42]: uninitialized constant Sigh::DeveloperCenter::Phantomjs
FATAL [2015-02-04 21:53:16.42]: fastlane finished with errors
/Library/Ruby/Gems/2.0.0/gems/sigh-0.2.2/lib/sigh/developer_center.rb:45:in `block in initialize': uninitialized constant Sigh::DeveloperCenter::Phantomjs (NameError)
  from /Library/Ruby/Gems/2.0.0/gems/capybara-2.4.4/lib/capybara/session.rb:79:in `call'
  from /Library/Ruby/Gems/2.0.0/gems/capybara-2.4.4/lib/capybara/session.rb:79:in `driver'
  from /Library/Ruby/Gems/2.0.0/gems/sigh-0.2.2/lib/sigh/developer_center.rb:52:in `initialize'
  from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.6/lib/fastlane/actions/sigh.rb:21:in `new'
  from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.6/lib/fastlane/actions/sigh.rb:21:in `run'
  from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.6/lib/fastlane/fast_file.rb:81:in `block (2 levels) in method_missing'
  from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.6/lib/fastlane/actions/actions_helper.rb:28:in `execute_action'
  from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.6/lib/fastlane/fast_file.rb:80:in `block in method_missing'
  from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.6/lib/fastlane/fast_file.rb:79:in `chdir'
  from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.6/lib/fastlane/fast_file.rb:79:in `method_missing'
  from (eval):21:in `block (2 levels) in parse'
  from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.6/lib/fastlane/runner.rb:17:in `call'
  from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.6/lib/fastlane/runner.rb:17:in `block in execute'
  from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.6/lib/fastlane/runner.rb:11:in `chdir'
  from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.6/lib/fastlane/runner.rb:11:in `execute'
  from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.6/lib/fastlane/lane_manager.rb:15:in `block in cruise_lanes'
  from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.6/lib/fastlane/lane_manager.rb:14:in `each'
  from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.6/lib/fastlane/lane_manager.rb:14:in `cruise_lanes'
  from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.6/bin/fastlane:31:in `block (2 levels) in run'
  from /Library/Ruby/Gems/2.0.0/gems/commander-4.2.0/lib/commander/command.rb:180:in `call'
  from /Library/Ruby/Gems/2.0.0/gems/commander-4.2.0/lib/commander/command.rb:180:in `call'
  from /Library/Ruby/Gems/2.0.0/gems/commander-4.2.0/lib/commander/command.rb:155:in `run'
  from /Library/Ruby/Gems/2.0.0/gems/commander-4.2.0/lib/commander/runner.rb:421:in `run_active_command'
  from /Library/Ruby/Gems/2.0.0/gems/commander-4.2.0/lib/commander/runner.rb:81:in `run!'
  from /Library/Ruby/Gems/2.0.0/gems/commander-4.2.0/lib/commander/delegates.rb:8:in `run!'
  from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.6/bin/fastlane:59:in `run'
  from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.6/bin/fastlane:63:in `<top (required)>'
  from /usr/bin/fastlane:23:in `load'
  from /usr/bin/fastlane:23:in `<main>'

**Comment by KrauseFx** [comment]
I just pushed a new version of `fastlane`: https://github.com/KrauseFx/fastlane/releases/tag/0.1.7

Could you update using `sudo gem update fastlane` and let me know if it works :+1:

**Comment by jingx23** [comment]
hmmm same problem :/

```
gem which fastlane
/Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.7/lib/fastlane.rb
```
Output:

```
fastlane beta
INFO [2015-02-04 22:31:45.23]: Driving the lane 'beta'
INFO [2015-02-04 22:31:45.23]: Step: sigh
INFO [2015-02-04 22:31:48.73]: Variable Dump:
INFO [2015-02-04 22:31:48.73]: {:LANE_NAME=>:beta, :START_TIME=>2015-02-04 22:31:45 +0100}
FATAL [2015-02-04 22:31:48.73]: uninitialized constant Sigh::DeveloperCenter::Phantomjs
FATAL [2015-02-04 22:31:48.74]: fastlane finished with errors
/Library/Ruby/Gems/2.0.0/gems/sigh-0.2.2/lib/sigh/developer_center.rb:45:in `block in initialize': uninitialized constant Sigh::DeveloperCenter::Phantomjs (NameError)
	from /Library/Ruby/Gems/2.0.0/gems/capybara-2.4.4/lib/capybara/session.rb:79:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/capybara-2.4.4/lib/capybara/session.rb:79:in `driver'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-0.2.2/lib/sigh/developer_center.rb:52:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.7/lib/fastlane/actions/sigh.rb:21:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.7/lib/fastlane/actions/sigh.rb:21:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.7/lib/fastlane/fast_file.rb:81:in `block (2 levels) in method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.7/lib/fastlane/actions/actions_helper.rb:29:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.7/lib/fastlane/fast_file.rb:80:in `block in method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.7/lib/fastlane/fast_file.rb:79:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.7/lib/fastlane/fast_file.rb:79:in `method_missing'
	from (eval):21:in `block (2 levels) in parse'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.7/lib/fastlane/runner.rb:18:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.7/lib/fastlane/runner.rb:18:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.7/lib/fastlane/runner.rb:12:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.7/lib/fastlane/runner.rb:12:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.7/lib/fastlane/lane_manager.rb:15:in `block in cruise_lanes'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.7/lib/fastlane/lane_manager.rb:14:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.7/lib/fastlane/lane_manager.rb:14:in `cruise_lanes'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.7/bin/fastlane:31:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.2.0/lib/commander/command.rb:180:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.2.0/lib/commander/command.rb:180:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.2.0/lib/commander/command.rb:155:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.2.0/lib/commander/runner.rb:421:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.2.0/lib/commander/runner.rb:81:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.2.0/lib/commander/delegates.rb:8:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.7/bin/fastlane:59:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.7/bin/fastlane:63:in `<top (required)>'
	from /usr/bin/fastlane:23:in `load'
	from /usr/bin/fastlane:23:in `<main>'
```

**Comment by KrauseFx** [comment]
Okay, I hope I fixed it now, please update `sigh` one more time and let me know if it works :+1:

**Comment by jingx23** [comment]
Ok, now the phantomjs error seems to be fixed but their seems to be another error oO.
Or should I miss something?

```
INFO [2015-02-05 09:04:48.82]: Driving the lane 'beta'
INFO [2015-02-05 09:04:48.82]: Step: sigh
INFO [2015-02-05 09:04:57.90]: Login into iOS Developer Center
INFO [2015-02-05 09:05:29.76]: Login successful
INFO [2015-02-05 09:05:29.76]: Variable Dump:
INFO [2015-02-05 09:05:29.76]: {:LANE_NAME=>:beta, :START_TIME=>2015-02-05 09:04:48 +0100}
FATAL [2015-02-05 09:05:29.76]: wrong number of arguments (2 for 4..5)
FATAL [2015-02-05 09:05:29.76]: fastlane finished with errors
/Library/Ruby/Gems/2.0.0/gems/sigh-0.2.3/lib/sigh/developer_center.rb:172:in `run': wrong number of arguments (2 for 4..5) (ArgumentError)
  from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.7/lib/fastlane/actions/sigh.rb:21:in `run'
  from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.7/lib/fastlane/fast_file.rb:81:in `block (2 levels) in method_missing'
  from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.7/lib/fastlane/actions/actions_helper.rb:29:in `execute_action'
  from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.7/lib/fastlane/fast_file.rb:80:in `block in method_missing'
  from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.7/lib/fastlane/fast_file.rb:79:in `chdir'
  from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.7/lib/fastlane/fast_file.rb:79:in `method_missing'
  from (eval):21:in `block (2 levels) in parse'
  from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.7/lib/fastlane/runner.rb:18:in `call'
  from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.7/lib/fastlane/runner.rb:18:in `block in execute'
  from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.7/lib/fastlane/runner.rb:12:in `chdir'
  from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.7/lib/fastlane/runner.rb:12:in `execute'
  from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.7/lib/fastlane/lane_manager.rb:15:in `block in cruise_lanes'
  from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.7/lib/fastlane/lane_manager.rb:14:in `each'
  from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.7/lib/fastlane/lane_manager.rb:14:in `cruise_lanes'
  from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.7/bin/fastlane:31:in `block (2 levels) in run'
  from /Library/Ruby/Gems/2.0.0/gems/commander-4.2.0/lib/commander/command.rb:180:in `call'
  from /Library/Ruby/Gems/2.0.0/gems/commander-4.2.0/lib/commander/command.rb:180:in `call'
  from /Library/Ruby/Gems/2.0.0/gems/commander-4.2.0/lib/commander/command.rb:155:in `run'
  from /Library/Ruby/Gems/2.0.0/gems/commander-4.2.0/lib/commander/runner.rb:421:in `run_active_command'
  from /Library/Ruby/Gems/2.0.0/gems/commander-4.2.0/lib/commander/runner.rb:81:in `run!'
  from /Library/Ruby/Gems/2.0.0/gems/commander-4.2.0/lib/commander/delegates.rb:8:in `run!'
  from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.7/bin/fastlane:59:in `run'
  from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.7/bin/fastlane:63:in `<top (required)>'
  from /usr/bin/fastlane:23:in `load'
  from /usr/bin/fastlane:23:in `<main>'
```

In sigh-0.2.1 the lane works as expected:
```
INFO [2015-02-05 09:17:49.20]: Driving the lane 'beta'
INFO [2015-02-05 09:17:49.20]: Step: sigh
#######################################################################
# sigh 0.2.3 is available.
# It is recommended to use the latest version.
# Update using '(sudo) gem update sigh'.
# To see what's new, open https://github.com/KrauseFx/sigh/releases.
#######################################################################
INFO [2015-02-05 09:17:55.52]: Login into iOS Developer Center
INFO [2015-02-05 09:18:08.69]: Login successful
INFO [2015-02-05 09:18:09.46]: Fetching all available provisioning profiles...
INFO [2015-02-05 09:18:10.27]: Checking if profile is available. (33 profiles found)
INFO [2015-02-05 09:18:23.34]: Downloading profile...
INFO [2015-02-05 09:18:24.57]: Successfully downloaded provisioning profile
INFO [2015-02-05 09:18:24.57]: Exported provisioning profile to '/Users/jsc/Downloads/fastlaneTest/Distribution_de.scireum.oxomi-pocket-beta.mobileprovision'
INFO [2015-02-05 09:18:24.57]: [SHELL COMMAND]: open '/Users/jsc/Downloads/fastlaneTest/Distribution_de.scireum.oxomi-pocket-beta.mobileprovision'
INFO [2015-02-05 09:18:24.98]: Step: hipchat
INFO [2015-02-05 09:18:30.23]: Step: hipchat
INFO [2015-02-05 09:18:31.00]: fastlane.tools finished successfully 🎉
```

**Comment by KrauseFx** [comment]
Fixed with https://github.com/KrauseFx/sigh/pull/38

Sorry about the troubles, please update sigh and let me know if it works :+1:

**Comment by jingx23** [comment]
Perfect this release fixed the problem :+1:

**Comment by KrauseFx** [comment]
Glad to hear, and thanks for helping fixing this problem.
