### ISSUE TITLE
s3 action failure after migrating to 1.3.0

### ISSUE THREAD

**Issue by frobichaud** [KrauseFx/fastlane#318]
Just migrated to 1.3.0, shenzhen needs to be an explicit dependency in the gem file?

```
----------------
22:50:52 [22:50:52]: --- Step: s3 ---
22:50:52 [22:50:52]: ----------------
22:50:52 [22:50:52]: ipa distribute:s3 -f "XXX.ipa" -a "XXX" -s "XXX" -b "jenkins-ios" -P "jobs/iOS-job/7/"
22:50:52 [22:50:52]: [SHELL COMMAND]: ipa distribute:s3 -f "XXX.ipa" -a "XXX" -s "XXX" -b "jenkins-ios" -P "jobs/iOS-job/7/"
22:50:54 [22:50:53]: [SHELL]: /Users/xbot/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.9.2/lib/bundler/rubygems_integration.rb:263:in `block in replace_gem': shenzhen is not part of the bundle. Add it to Gemfile. (Gem::LoadError)
22:50:54 [22:50:53]: [SHELL]: from /Users/xbot/.rbenv/versions/2.2.1/bin/ipa:22:in `<main>'
22:50:54 [22:50:53]: Exit status of command 'ipa distribute:s3 -f "XXX.ipa" -a "XXX" -s "XXX" -b "jenkins-ios" -P "jobs/iOS-job/7/"' was 256 instead of 0. 
22:50:54 /Users/xbot/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.9.2/lib/bundler/rubygems_integration.rb:263:in `block in replace_gem': shenzhen is not part of the bundle. Add it to Gemfile. (Gem::LoadError)
22:50:54 	from /Users/xbot/.rbenv/versions/2.2.1/bin/ipa:22:in `<main>'
```

**Comment by KrauseFx** [comment]
Thanks, I'll push a fix in a minute.

**Comment by frobichaud** [comment]
Thanks @KrauseFx for the quick fix, testing right now.

**Comment by KrauseFx** [comment]
One second, just uploading the new version :+1:

**Comment by KrauseFx** [comment]
It's live :rocket:

**Comment by frobichaud** [comment]
Thanks, works like a charm

**Comment by KrauseFx** [comment]
Great to hear :+1:
