### ISSUE TITLE
Trouble using fastlane / sigh on multi-user system

### ISSUE THREAD

**Issue by GeorgeMcMullen** [KrauseFx/fastlane#326]
Hello,

I'm starting to work with fastlane on a Jenkins installation. I noticed that if something fails or is still in progress with one user (AKA the jenkins user), another user (AKA my user on the same box) cannot use fastlane due to the following error:
```
/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.7.6/lib/fastlane_core/developer_center/developer_center.rb:44:in `initialize': Permission denied - /tmp/fastlane_core//poltergeist_log.txt (Errno::EACCES)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.7.6/lib/fastlane_core/developer_center/developer_center.rb:44:in `open'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.7.6/lib/fastlane_core/developer_center/developer_center.rb:44:in `block in initialize'
	from /Library/Ruby/Gems/2.0.0/gems/capybara-2.4.4/lib/capybara/session.rb:79:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/capybara-2.4.4/lib/capybara/session.rb:79:in `driver'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.7.6/lib/fastlane_core/developer_center/developer_center.rb:50:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-0.5.2/lib/sigh/manager.rb:6:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-0.5.2/lib/sigh/manager.rb:6:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-0.5.2/bin/sigh:36:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-0.5.2/bin/sigh:67:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-0.5.2/bin/sigh:74:in `<top (required)>'
	from /usr/bin/sigh:23:in `load'
	from /usr/bin/sigh:23:in `<main>'
```

The following file exists and is owned by another user:

/tmp/fastlane_core//poltergeist_log.txt

Perhaps this is a configuration problem, but it would be helpful to have some documentation around resolving that if it is.

**Comment by KrauseFx** [comment]
I haven't seen this error before. It seems to be a poltergeist error and has nothing to do with `fastlane` directly. Also, I never used `fastlane` in a multi-user environment. Let me know if you found a good solution for it.

You'll be glad to hear, within the next weeks/months `fastlane` will get rid of the `poltergeist` dependency :+1:

**Comment by nklausni** [comment]
Just remove the fastlane_core folder from temp as a superuser. It'll be rebuild. It's because you used fastlane with a different user than the jenkins user and the jenkins user has no write permissions to this folder.

**Comment by nschum** [comment]
I noticed almost the same problem with `sigh`, even if it is no longer running. `sigh` creates a file named `/tmp/spaceship.log` and when you run it again with another user, it will complain that it cannot write to that file.

The solution would be not to hardcode any `/tmp` paths but to create a unique folder in tmp (cf. `mktemp`).

**Comment by KrauseFx** [comment]
@nschum Technically it wouldn't be a problem to use a real Ruby temp file, but this wouldn't make it easy for the user to find and read it. The advantage of the current solution is that the user can just always `open /tmp/spaceship.log` and see the log lines of `spaceship`

What do you think? Maybe something like `/tmp/spaceship#{Time.now.to_s}`?

**Comment by nschum** [comment]
:+1: Maybe `Time.now.iso8601` to avoid spaces.

**Comment by KrauseFx** [comment]
@nschum sorry, I meant `Time.now.to_i` :wink: 
Would that be a reasonable solution for you?

**Comment by nschum** [comment]
Sure.

**Comment by KrauseFx** [comment]
This is now implemented and will be available with the next version :+1:

**Comment by robertjpayne** [comment]
@KrauseFx think this is still broken, I just had to clear out `/tmp/spaceship_api_key.txt` :(

**Comment by robertjpayne** [comment]
@KrauseFx this still exists, there's some issues with how the certificates are trying to be loaded on a multi-user system, I'm still getting build errors too:

```
[09:24:27]: ------------------
[09:24:27]: --- Step: sigh ---
[09:24:27]: ------------------
[09:24:27]: Starting login
[09:24:28]: Successfully logged in
[09:24:28]: Fetching profiles...
[09:24:31]: Found 1 matching profile(s)
[09:24:31]: Downloading provisioning profile...
[09:24:31]: Successfully downloaded provisioning profile...
[09:24:31]: Installing provisioning profile...
security: cert import failed: write permissions error
security: problem decoding
[09:24:31]: Variable Dump:
[09:24:31]: {:DEFAULT_PLATFORM=>:ios, :ENVIRONMENT=>nil, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios adhoc", :GIT_REPO_WAS_CLEAN_ON_START=>true}
[09:24:31]: undefined method `count' for nil:NilClass

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | ensure_git_status_clean             | 0           |
| 4    | sigh                                | 3           |
+------+-------------------------------------+-------------+

[09:24:31]: fastlane finished with errors
/Library/Ruby/Gems/2.0.0/gems/sigh-0.10.3/lib/sigh/profile_analyser.rb:7:in `run': undefined method `count' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/sigh-0.10.3/lib/sigh/manager.rb:36:in `install_profile'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-0.10.3/lib/sigh/manager.rb:20:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.14.1/lib/fastlane/actions/sigh.rb:20:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.14.1/lib/fastlane/runner.rb:142:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.14.1/lib/fastlane/actions/actions_helper.rb:62:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.14.1/lib/fastlane/runner.rb:128:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.14.1/lib/fastlane/runner.rb:127:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.14.1/lib/fastlane/runner.rb:127:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.14.1/lib/fastlane/fast_file.rb:120:in `method_missing'
	from (eval):23:in `block (3 levels) in parse'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.14.1/lib/fastlane/lane.rb:29:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.14.1/lib/fastlane/lane.rb:29:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.14.1/lib/fastlane/runner.rb:50:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.14.1/lib/fastlane/runner.rb:44:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.14.1/lib/fastlane/runner.rb:44:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.14.1/lib/fastlane/lane_manager.rb:36:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.14.1/lib/fastlane/command_line_handler.rb:31:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.14.1/bin/fastlane:35:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.14.1/bin/fastlane:124:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.14.1/bin/fastlane:130:in `<top (required)>'
	from /usr/bin/fastlane:23:in `load'
	from /usr/bin/fastlane:23:in `<main>'
```

**Comment by robertjpayne** [comment]
So the really TLDR; of this is Codesigning via Jenkins is REALLY hard to get right. It seems sometimes it'll just 'work' but most of the time it'll just fail. My solution was to:

* Ensure Jenkins is running with a user session, so default keychains are mounted
* Create a custom `codesign.keychain` in `~/Library/Keychains` and ensure this keychain is the top in the left hand list of keychains in Keychain Access.
* If you right-click on the `codesign` keychain and change settings set the Lock After to 60 minutes, save then change settings again and uncheck the Lock After.
* In Jenkins before running fastlane add below bash script:

```
# keychain
security -v list-keychains -d system -s ~/Library/Keychains/codesign.keychain
security -v unlock-keychain -p $CODESIGN_KEYCHAIN_PASSWORD ~/Library/Keychains/codesign.keychain
```

**Comment by stefreak** [comment]
@robertjpayne what does the first point mean exactly?

**Comment by stefreak** [comment]
OK I found out. for me this simply meant `mv /Library/LaunchDeamons/org.jenkins-ci.plist /Library/LaunchAgents/org.jenkins-ci.plist` and reboot (more info on this on https://nickcharlton.net/posts/installing-jenkins-osx-yosemite.html)

**Comment by TKBurner** [comment]
@stefreak Really glad to hear you got up and running! 👍
