### ISSUE TITLE
fastlane init error

### ISSUE THREAD

**Issue by HongliYu** [KrauseFx/fastlane#339]
```
Ignoring xcodeproj-0.17.0 because its extensions are not built.  Try: gem pristine xcodeproj-0.17.0
[20:22:27]: This setup will help you get up and running in no time.
[20:22:27]: First, it will move the config files from `deliver` and `snapshot`
[20:22:27]: into the subfolder `fastlane`.

[20:22:27]: fastlane will check what tools you're already using and set up
[20:22:27]: the tool automatically for you. Have fun! 
Do you want to get started? This will move your Deliverfile and Snapfile (if
they exist) (y/n)
y
 Do you have everything commited in version control? If not please do so!
(y/n)
y
 [20:22:30]: Error occured with the setup program! Reverting changes now!
/Library/Ruby/Gems/2.0.0/gems/fastlane-1.3.2/lib/fastlane/setup.rb:161:in `join': no implicit conversion of nil into String (TypeError)
 from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.3.2/lib/fastlane/setup.rb:161:in `block in restore_previous_state'
 from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.3.2/lib/fastlane/setup.rb:160:in `each'
 from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.3.2/lib/fastlane/setup.rb:160:in `restore_previous_state'
 from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.3.2/lib/fastlane/setup.rb:31:in `rescue in run'
 from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.3.2/lib/fastlane/setup.rb:17:in `run'
 from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.3.2/bin/fastlane:52:in `block (2 levels) in run'
 from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
 from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
 from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:153:in `run'
 from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/runner.rb:428:in `run_active_command'
 from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/runner.rb:68:in `run!'
 from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/delegates.rb:15:in `run!'
 from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.3.2/bin/fastlane:118:in `run'
 from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.3.2/bin/fastlane:124:in `<top (required)>'
 from /usr/bin/fastlane:23:in `load'
 from /usr/bin/fastlane:23:in `<main>'
```

**Comment by KrauseFx** [comment]
What was the issue?

**Comment by HongliYu** [comment]
I run this script in the directory under jenkins, and it's a problem of
root permission.I want to do weekly testflight on the server.I should
shutdown the jenkins at the beginning.It's OK now, thank you, and you are
awesome

——来自虞鸿礼的私人邮件

2015-06-10 0:06 GMT+08:00 Felix Krause <notifications@github.com>:

**Comment by KrauseFx** [comment]
Great to hear, thanks for letting me know :+1:
