### ISSUE TITLE
Fastlane will always failed after I changed my account password

### ISSUE THREAD

**Issue by siuying** [KrauseFx/fastlane#390]
After I changed my password, running fastlane always result in error:

```
[15:49:10]: fastlane finished with errors
/Users/siuying/.rvm/gems/ruby-2.1.5/gems/spaceship-0.0.14/lib/spaceship/client.rb:176:in `login': #<Faraday::Response:0x007fad7bb6d9d0> (Spaceship::Client::InvalidUserCredentialsError)
	from /Users/siuying/.rvm/gems/ruby-2.1.5/gems/spaceship-0.0.14/lib/spaceship/client.rb:45:in `login'
	from /Users/siuying/.rvm/gems/ruby-2.1.5/gems/spaceship-0.0.14/lib/spaceship.rb:31:in `login'
	from /Users/siuying/.rvm/gems/ruby-2.1.5/gems/sigh-0.10.0/lib/sigh/spaceship/runner.rb:11:in `run'
	from /Users/siuying/.rvm/gems/ruby-2.1.5/gems/sigh-0.10.0/lib/sigh/manager.rb:7:in `start'
	from /Users/siuying/.rvm/gems/ruby-2.1.5/gems/fastlane-1.7.0/lib/fastlane/actions/sigh.rb:20:in `run'
```

I expect fastlane to ask me to enter new password, but somehow it just crash.

Manually delete the entry 'fastlane.<account>" can workaround the issue.

**Comment by KrauseFx** [comment]
This should be improved, please submit this issue on https://github.com/fastlane/spaceship
