### ISSUE TITLE
deploygate action returns error under proxy

### ISSUE THREAD

**Issue by fumitoito** [KrauseFx/fastlane#414]
When reaching the upload to deploygate, I got following output (fastlane 1.8.0)
As seen the stacktrace, it may possibly be an issue from shenzhen.

```
[12:39:53]: ------------------------
[12:39:53]: --- Step: deploygate ---
[12:39:53]: ------------------------
[12:39:53]: Starting with ipa upload to DeployGate... this could take some time ⏳
The environment variable HTTP_PROXY is discouraged.  Use http_proxy.
[12:39:53]: Variable Dump:
[12:39:53]: {:DEFAULT_PLATFORM=>:ios, :ENVIRONMENT=>nil, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios alpha", :SIGH_PROFILE_PATH=>"/Users/newtech/Projects/way/AdHoc_com.fujitsu.way.mobileprovision", :SIGH_UDID=>"7e603d68-42ec-43f6-abff-68f9fd7431d0", :IPA_OUTPUT_PATH=>"/Users/newtech/Projects/way/way.ipa", :DSYM_OUTPUT_PATH=>"/Users/newtech/Projects/way/way.app.dSYM.zip"}
[12:39:53]: 407 "Proxy Authentication Required"
[12:39:55]: fastlane finished with errors
```

The full stack trace:
```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:119:in `error!': 407 "Proxy Authentication Required" (Faraday::ConnectionFailed)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:128:in `value'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:913:in `connect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:851:in `start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1367:in `request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:82:in `perform_request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:40:in `block in call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:32:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response/follow_redirects.rb:76:in `perform_with_redirection'
	from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response/follow_redirects.rb:64:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/request/encode_json.rb:23:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.1/lib/faraday/request/multipart.rb:14:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:139:in `build_response'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.1/lib/faraday/connection.rb:377:in `run_request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.1/lib/faraday/connection.rb:177:in `post'
	from /Library/Ruby/Gems/2.0.0/gems/krausefx-shenzhen-0.14.4/lib/shenzhen/plugins/deploygate.rb:29:in `upload_build'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.7.3/lib/fastlane/actions/deploygate.rb:34:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.7.3/lib/fastlane/fast_file.rb:114:in `block (2 levels) in method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.7.3/lib/fastlane/actions/actions_helper.rb:51:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.7.3/lib/fastlane/fast_file.rb:96:in `block in method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.7.3/lib/fastlane/fast_file.rb:95:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.7.3/lib/fastlane/fast_file.rb:95:in `method_missing'
	from (eval):53:in `block (3 levels) in parse'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.7.3/lib/fastlane/runner.rb:39:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.7.3/lib/fastlane/runner.rb:39:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.7.3/lib/fastlane/runner.rb:29:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.7.3/lib/fastlane/runner.rb:29:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.7.3/lib/fastlane/lane_manager.rb:33:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.7.3/bin/fastlane:39:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.7.3/bin/fastlane:128:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.7.3/bin/fastlane:134:in `<top (required)>'
	from /usr/bin/fastlane:23:in `load'
	from /usr/bin/fastlane:23:in `<main>'
```

**Comment by KrauseFx** [comment]
This is an issue of [shenzhen](https://github.com/nomad/shenzhen), please submit the issue there :+1:
