### ISSUE TITLE
How to get result of shell command in lane?

### ISSUE THREAD

**Issue by skywinder** [KrauseFx/fastlane#422]
Hi. I want to set tag in one of my lanes. Is it possible to save result to some variable in lanes?
I tried to create variable inside lane, but have no luck.

```
    fetched_tag = `#{agvtool what-marketing-version -terse1}`
    add_git_tag(tag: fetched_tag)
```

How can I achieve such result in lane?

**Comment by KrauseFx** [comment]
Change it to 
```ruby
fetched_tag = sh("agvtool what-marketing-version -terse1")
add_git_tag(tag: fetched_tag)
````
and it should work :+1:

**Comment by skywinder** [comment]
For your code got error:
```
[12:17:13]: Exit status of command 'agvtool what-marketing-version -terse1' was 768 instead of 0.
There are no Xcode project files in this directory.  agvtool needs a project to operate.

[12:17:13]: fastlane finished with errors
/Users/petrkorolev/.rvm/gems/ruby-2.1.5@global/gems/fastlane-1.10.0/lib/fastlane/actions/actions_helper.rb:113:in `sh_no_action': Exit status of command 'agvtool what-marketing-version -terse1' was 768 instead of 0.  (RuntimeError)
```

Then I change to:

    fetched_tag = sh("cd .. && agvtool what-marketing-version -terse1")

to run it in proper folder, then it fetch version (`5.2.0`) but still got error:

```
[12:18:54]: fastlane version valid
[12:18:54]: Driving the lane 'tag' 🚀
[12:18:54]: -------------------------------------------------------------
[12:18:54]: --- Step: cd .. && agvtool what-marketing-version -terse1 ---
[12:18:54]: -------------------------------------------------------------
[12:18:54]: [SHELL COMMAND]: cd .. && agvtool what-marketing-version -terse1
[12:18:55]: [SHELL]: 5.2.0
[12:18:55]: -------------------------
[12:18:55]: --- Step: add_git_tag ---
[12:18:55]: -------------------------
[12:18:55]: Adding git tag '5.2.0
' 🎯.
[12:18:55]: [SHELL COMMAND]: git tag "5.2.0
"
[12:18:55]: [SHELL]: fatal: '5.2.0
[12:18:55]: [SHELL]: ' is not a valid tag name.
[12:18:55]: Variable Dump:
[12:18:55]: {:ENVIRONMENT=>nil, :PLATFORM_NAME=>nil, :LANE_NAME=>"tag"}
[12:18:55]: Exit status of command 'git tag "5.2.0
"' was 32768 instead of 0.
fatal: '5.2.0
' is not a valid tag name.

[12:18:55]: fastlane finished with errors
/Users/petrkorolev/.rvm/gems/ruby-2.1.5@global/gems/fastlane-1.10.0/lib/fastlane/actions/actions_helper.rb:113:in `sh_no_action': Exit status of command 'git tag "5.2.0 (RuntimeError)
"' was 32768 instead of 0.
fatal: '5.2.0
' is not a valid tag name.
```
Seems, that problem in `\n` in the end.

**Comment by skywinder** [comment]
Ok, I fixed it by command:

        fetched_tag = sh("cd .. && agvtool what-marketing-version -terse1 | tr -d '\n'")

Thanks, @KrauseFx!

**Comment by KrauseFx** [comment]
Great to hear @skywinder :+1:
