### ISSUE TITLE
`fastlane action sigh` generates an error

### ISSUE THREAD

**Issue by jefflovejapan** [KrauseFx/fastlane#429]
Trying to read docs for the `sigh` action in 1.11.0 generates the following error:

~~~~
/usr/local/lib/ruby/gems/2.2.0/gems/credentials_manager-0.6.0/lib/credentials_manager/appfile_config.rb:26:in `eval': (eval):1: syntax error, unexpected keyword_do_block (SyntaxError)
(eval):5: syntax error, unexpected keyword_end, expecting end-of-input
	from /usr/local/lib/ruby/gems/2.2.0/gems/credentials_manager-0.6.0/lib/credentials_manager/appfile_config.rb:26:in `block in initialize'
	from /usr/local/lib/ruby/gems/2.2.0/gems/credentials_manager-0.6.0/lib/credentials_manager/appfile_config.rb:25:in `chdir'
	from /usr/local/lib/ruby/gems/2.2.0/gems/credentials_manager-0.6.0/lib/credentials_manager/appfile_config.rb:25:in `initialize'
	from /usr/local/lib/ruby/gems/2.2.0/gems/credentials_manager-0.6.0/lib/credentials_manager/appfile_config.rb:7:in `new'
	from /usr/local/lib/ruby/gems/2.2.0/gems/credentials_manager-0.6.0/lib/credentials_manager/appfile_config.rb:7:in `try_fetch_value'
	from /usr/local/lib/ruby/gems/2.2.0/gems/sigh-0.10.1/lib/sigh/options.rb:33:in `available_options'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.11.0/lib/fastlane/actions/sigh.rb:42:in `available_options'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.11.0/lib/fastlane/actions_list.rb:67:in `block in show_details'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.11.0/lib/fastlane/actions_list.rb:111:in `block in all_actions'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.11.0/lib/fastlane/actions_list.rb:108:in `each'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.11.0/lib/fastlane/actions_list.rb:108:in `all_actions'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.11.0/lib/fastlane/actions_list.rb:45:in `show_details'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.11.0/lib/fastlane/actions_list.rb:6:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.11.0/bin/fastlane:118:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.4/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.4/lib/commander/runner.rb:428:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.4/lib/commander/runner.rb:68:in `run!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.4/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.11.0/bin/fastlane:124:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.11.0/bin/fastlane:130:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
~~~~

**Comment by KrauseFx** [comment]
Can you share your `Appfile`?

**Comment by jefflovejapan** [comment]
~~~~
for_lane beta: do
	app_identifier "tktkkt"
	apple_id "tktktkt"
	team_id "tktktktk"
end

for_lane deploy: do
	app_identifier "tktktkt"
	apple_id "tktktkt"
	team_id "tktktktk"
end
~~~~

**Comment by KrauseFx** [comment]
You have 2 `:` after the lane name. You'll have to remove them. Was that somewhere in the documentation?

**Comment by jefflovejapan** [comment]
No, that's my mistake and has been removed. Sigh no longer generates the error with the properly-configured Appfile, although it is a little weird for a request for documentation to be failing because of some seemingly unrelated state. Anyway, thanks a ton for all the hard work.

**Comment by KrauseFx** [comment]
Okay, good to hear you got that resolved :+1: It was failing since the app identifier was fetched from the Appfile if not passed via the command line.
