### ISSUE TITLE
Deliver fails when using deliver_file_path option of deliver action.

### ISSUE THREAD

**Issue by ds29** [KrauseFx/fastlane#430]
When specifying deliver_file_path option of the deliver action, I always get an error returned.  Any help is appreciated.  I'm calling it via fastlane using environment files to specify necessary info:

`fastlane metadata --env MyBrandedApp`

In my case, I have numerous apps, so we've created separate Deliverfile(s) for each to automate them all.  For the metadata action, I simply want to upload metadata only.

I've also tried running deliver directly from the branded folder path and it still gives this error message.

Thanks in advance for your help/guidance. Fastlane is awesome!

----- Fastfile
```
lane :metadata do
  branded_app_path = "/Users/me/Desktop/Apps/MyCoolApp/fastlane/appstore/MyBrandedApp"
  deliver(
    metadata_only: true,
    deliver_file_path: branded_app_path
  )
end
```

------- Deliverfile
```
      email 'email@example.dev' # the login email address
      apple_id '123456789' # This is NOT your Apple login ID, but the App ID of your app

      app_identifier "dev.example.MyBrandedApp"
      version '1.2.2'

      target_dir = 'appstore'
      meta_dir = "#{target_dir}/en-US"

      title(
        'en-US' => File.read("#{meta_dir}/title.txt")
      )

      description(
        'en-US' => File.read("#{meta_dir}/description.txt")
      )

      whats_new = File.read("#{meta_dir}/version_whats_new.txt")
      unless whats_new.empty?
        changelog(
          'en-US' => whats_new
        )
      end

      keywords(
        'en-US' => File.read("#{meta_dir}/keywords.txt").split('\n')
      )

      privacy_url(
        'en-US' => File.read("#{meta_dir}/privacy_url.txt")
      )

      marketing_url(
        'en-US' => File.read("#{meta_dir}/software_url.txt")
      )

      support_url(
        'en-US' => File.read("#{meta_dir}/support_url.txt")
      )

      app_icon "#{target_dir}/MyBrandedApp.png"

      price_tier 0 # free

      copyright "#{Time.now.year} My Company"

      primary_category 'Finance'

      secondary_category 'Productivity'

      automatic_release true

      ratings_config_path 'appstore/ratings_config.json'

      app_review_information({
        first_name: 'Name',
        last_name: 'Last',
        phone_number: '555-555-5555',
        email_address: 'email@example.dev',
        demo_user: 'email@example.dev',
        demo_password: '1234',
        notes: 'A demo account is not required for app usage but can be used to login if desired.'
      })
```

---- Full trace
```
/Users/me/.rvm/gems/ruby-2.2.2@appdev/gems/deliver-0.12.0/lib/deliver/deliverfile/deliverfile.rb:29:in `eval': You have to pass either a value or a block to the given method. (Deliver::Deliverfile::Deliverfile::DSL::DeliverfileDSLError)
	from (eval):6:in `initialize'
	from /Users/me/.rvm/gems/ruby-2.2.2@appdev/gems/deliver-0.12.0/lib/deliver/deliverfile/deliverfile.rb:29:in `eval'
	from /Users/me/.rvm/gems/ruby-2.2.2@appdev/gems/deliver-0.12.0/lib/deliver/deliverfile/deliverfile.rb:29:in `initialize'
	from /Users/me/.rvm/gems/ruby-2.2.2@appdev/gems/deliver-0.12.0/lib/deliver/deliverer.rb:85:in `new'
	from /Users/me/.rvm/gems/ruby-2.2.2@appdev/gems/deliver-0.12.0/lib/deliver/deliverer.rb:85:in `initialize'
	from /Users/me/.rvm/gems/ruby-2.2.2@appdev/gems/fastlane-1.3.2/lib/fastlane/actions/deliver.rb:21:in `new'
	from /Users/me/.rvm/gems/ruby-2.2.2@appdev/gems/fastlane-1.3.2/lib/fastlane/actions/deliver.rb:21:in `block in run'
	from /Users/me/.rvm/gems/ruby-2.2.2@appdev/gems/fastlane-1.3.2/lib/fastlane/actions/deliver.rb:17:in `chdir'
	from /Users/me/.rvm/gems/ruby-2.2.2@appdev/gems/fastlane-1.3.2/lib/fastlane/actions/deliver.rb:17:in `run'
	from /Users/me/.rvm/gems/ruby-2.2.2@appdev/gems/fastlane-1.3.2/lib/fastlane/fast_file.rb:112:in `block (2 levels) in method_missing'
	from /Users/me/.rvm/gems/ruby-2.2.2@appdev/gems/fastlane-1.3.2/lib/fastlane/actions/actions_helper.rb:51:in `execute_action'
	from /Users/me/.rvm/gems/ruby-2.2.2@appdev/gems/fastlane-1.3.2/lib/fastlane/fast_file.rb:94:in `block in method_missing'
	from /Users/me/.rvm/gems/ruby-2.2.2@appdev/gems/fastlane-1.3.2/lib/fastlane/fast_file.rb:93:in `chdir'
	from /Users/me/.rvm/gems/ruby-2.2.2@appdev/gems/fastlane-1.3.2/lib/fastlane/fast_file.rb:93:in `method_missing'
	from (eval):293:in `block (2 levels) in parse'
	from /Users/me/.rvm/gems/ruby-2.2.2@appdev/gems/fastlane-1.3.2/lib/fastlane/runner.rb:35:in `call'
	from /Users/me/.rvm/gems/ruby-2.2.2@appdev/gems/fastlane-1.3.2/lib/fastlane/runner.rb:35:in `block in execute'
	from /Users/me/.rvm/gems/ruby-2.2.2@appdev/gems/fastlane-1.3.2/lib/fastlane/runner.rb:25:in `chdir'
	from /Users/me/.rvm/gems/ruby-2.2.2@appdev/gems/fastlane-1.3.2/lib/fastlane/runner.rb:25:in `execute'
	from /Users/me/.rvm/gems/ruby-2.2.2@appdev/gems/fastlane-1.3.2/lib/fastlane/lane_manager.rb:33:in `cruise_lane'
	from /Users/me/.rvm/gems/ruby-2.2.2@appdev/gems/fastlane-1.3.2/bin/fastlane:39:in `block (2 levels) in run'
	from /Users/me/.rvm/gems/ruby-2.2.2@appdev/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
	from /Users/me/.rvm/gems/ruby-2.2.2@appdev/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
	from /Users/me/.rvm/gems/ruby-2.2.2@appdev/gems/commander-4.3.4/lib/commander/command.rb:153:in `run'
	from /Users/me/.rvm/gems/ruby-2.2.2@appdev/gems/commander-4.3.4/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/me/.rvm/gems/ruby-2.2.2@appdev/gems/commander-4.3.4/lib/commander/runner.rb:68:in `run!'
	from /Users/me/.rvm/gems/ruby-2.2.2@appdev/gems/commander-4.3.4/lib/commander/delegates.rb:15:in `run!'
	from /Users/me/.rvm/gems/ruby-2.2.2@appdev/gems/fastlane-1.3.2/bin/fastlane:118:in `run'
	from /Users/me/.rvm/gems/ruby-2.2.2@appdev/gems/fastlane-1.3.2/bin/fastlane:124:in `<top (required)>'
	from /Users/me/.rvm/gems/ruby-2.2.2@appdev/bin/fastlane:23:in `load'
	from /Users/me/.rvm/gems/ruby-2.2.2@appdev/bin/fastlane:23:in `<main>'
	from /Users/me/.rvm/gems/ruby-2.2.2@appdev/bin/ruby_executable_hooks:15:in `eval'
	from /Users/me/.rvm/gems/ruby-2.2.2@appdev/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by ds29** [comment]
@KrauseFx Should I move this ticket to deliver issues?

**Comment by KrauseFx** [comment]
@ds29 yes, please :+1:

**Comment by ds29** [comment]
@KrauseFx Done! Moved to deliver [#275](https://github.com/KrauseFx/deliver/issues/275).
