### ISSUE TITLE
Changed Apple credentials + New setup

### ISSUE THREAD

**Issue by ricardopereira** [KrauseFx/fastlane#431]
Fastlane asked me: `Do you want to re-enter your username and password? (y/n)` and I say yes but it did not return to ask.

**version** fastlane 1.11.0
**ruby** ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
**command** `fastlane init`

**output:**
```bash
[10:27:53]: Created new file './fastlane/Appfile'. Edit it to manage your preferred app metadata information.
Do you want to setup 'deliver', which is used to upload app screenshots, app metadata and app updates to the App Store
or Apple TestFlight? (y/n)
y
 [10:28:06]: Loading up 'deliver', this might take a few seconds
Do you want Deliver to automatically create the Deliverfile for you based on your current app? The app has to be in
the App Store to use this feature. (y/n)
y


First, you need to login with your iTunesConnect credentials.
This is necessary to fetch the latest metadata from your app and use it to create a Deliverfile for you.
If you have previously entered your credentials already, you will not be asked again.
[10:29:43]: Going to download app metadata from iTunesConnect
[10:29:51]: [Transporter]: INFO: Transporter is searching for updated software components.
[10:29:54]: [Transporter]: INFO: Transporter has detected that new software components exist; updating.
[10:29:54]: [Transporter]: DEBUG: Analyzing remote bundle resource org.apache.httpcomponents.httpclient...
[10:29:54]: [Transporter]: DEBUG:   ... resource is same as system bundle, skipping download.
[10:29:54]: [Transporter]: DEBUG: Analyzing remote bundle resource org.apache.httpcomponents.httpcore...
[10:29:54]: [Transporter]: DEBUG:   ... resource is same as system bundle, skipping download.
[10:29:54]: [Transporter]: DEBUG: Analyzing remote bundle resource com.springsource.org.apache.commons.beanutils...
[10:29:54]: [Transporter]: DEBUG:   ... resource is same as system bundle, skipping download.
[10:29:54]: [Transporter]: DEBUG: Analyzing remote bundle resource com.springsource.org.apache.commons.codec...
[10:29:54]: [Transporter]: DEBUG:   ... resource is same as system bundle, skipping download.
[10:29:54]: [Transporter]: DEBUG: Analyzing remote bundle resource com.springsource.org.apache.commons.collections...
[10:29:54]: [Transporter]: DEBUG:   ... resource is same as system bundle, skipping download.
[10:29:54]: [Transporter]: DEBUG: Analyzing remote bundle resource com.springsource.org.apache.commons.cli...
[10:29:54]: [Transporter]: DEBUG:   ... resource is same as system bundle, skipping download.
[10:29:54]: [Transporter]: DEBUG: Analyzing remote bundle resource com.springsource.org.apache.commons.digester...
[10:29:54]: [Transporter]: DEBUG:   ... resource is same as system bundle, skipping download.
[10:29:54]: [Transporter]: DEBUG: Analyzing remote bundle resource com.springsource.org.apache.commons.discovery...
[10:29:54]: [Transporter]: DEBUG:   ... resource is same as system bundle, skipping download.
[10:29:54]: [Transporter]: DEBUG: Analyzing remote bundle resource com.springsource.org.apache.commons.io...
[10:29:54]: [Transporter]: DEBUG:   ... resource is same as system bundle, skipping download.
[10:29:54]: [Transporter]: DEBUG: Analyzing remote bundle resource com.springsource.org.apache.commons.logging...
[10:29:54]: [Transporter]: DEBUG:   ... resource is same as system bundle, skipping download.
[10:29:54]: [Transporter]: DEBUG: Analyzing remote bundle resource com.springsource.org.apache.commons.net...
[10:29:54]: [Transporter]: DEBUG:   ... resource is same as system bundle, skipping download.
[10:29:54]: [Transporter]: DEBUG: Analyzing remote bundle resource org.apache.felix.bundlerepository...
[10:29:54]: [Transporter]: DEBUG:   ... resource is same as system bundle, skipping download.
[10:29:54]: [Transporter]: DEBUG: Analyzing remote bundle resource org.apache.felix.configadmin...
[10:29:54]: [Transporter]: DEBUG:   ... resource is same as system bundle, skipping download.
[10:29:54]: [Transporter]: DEBUG: Analyzing remote bundle resource org.apache.sanselan.sanselan...
[10:29:54]: [Transporter]: DEBUG:   ... resource is same as system bundle, skipping download.
[10:29:54]: [Transporter]: DEBUG: Analyzing remote bundle resource com.springsource.org.apache.xml.resolver...
[10:29:54]: [Transporter]: DEBUG:   ... resource is same as system bundle, skipping download.
[10:29:54]: [Transporter]: DEBUG: Analyzing remote bundle resource com.asperasoft.faspmanager...
[10:29:54]: [Transporter]: DEBUG:   ... resource is same as system bundle, skipping download.
[10:29:54]: [Transporter]: DEBUG: Analyzing remote bundle resource com.apple.transporter.asperasupport...
[10:29:54]: [Transporter]: DEBUG:   ... resource is same as system bundle, skipping download.
[10:29:54]: [Transporter]: DEBUG: Analyzing remote bundle resource com.apple.transporter...
[10:29:58]: [Transporter]: DEBUG:   ... updated bundle successfully retrieved.
[10:29:58]: [Transporter]: DEBUG: Analyzing remote bundle resource com.apple.transporter.softwaresupport...
[10:30:12]: [Transporter]: DEBUG:   ... updated bundle successfully retrieved.
[10:30:12]: [Transporter]: DEBUG: Analyzing remote bundle resource com.apple.transporter.updater...
[10:30:12]: [Transporter]: DEBUG:   ... updated bundle successfully retrieved.
[10:30:12]: [Transporter]: DEBUG: Analyzing remote bundle resource com.springsource.javax.activation...
[10:30:12]: [Transporter]: DEBUG:   ... resource is same as system bundle, skipping download.
[10:30:12]: [Transporter]: DEBUG: Analyzing remote bundle resource com.springsource.javax.media.jai.core...
[10:30:12]: [Transporter]: DEBUG:   ... resource is same as system bundle, skipping download.
[10:30:12]: [Transporter]: DEBUG: Analyzing remote bundle resource com.springsource.javax.media.jai.codec...
[10:30:12]: [Transporter]: DEBUG:   ... resource is same as system bundle, skipping download.
[10:30:12]: [Transporter]: DEBUG: Analyzing remote bundle resource com.springsource.javax.mail...
[10:30:12]: [Transporter]: DEBUG:   ... resource is same as system bundle, skipping download.
[10:30:12]: [Transporter]: DEBUG: Analyzing remote bundle resource com.springsource.javax.servlet...
[10:30:12]: [Transporter]: DEBUG:   ... resource is same as system bundle, skipping download.
[10:30:12]: [Transporter]: DEBUG: Analyzing remote bundle resource com.springsource.javax.xml.soap...
[10:30:12]: [Transporter]: DEBUG:   ... resource is same as system bundle, skipping download.
[10:30:12]: [Transporter]: DEBUG: Analyzing remote bundle resource com.springsource.javax.xml.rpc...
[10:30:12]: [Transporter]: DEBUG:   ... resource is same as system bundle, skipping download.
[10:30:12]: [Transporter]: DEBUG: Analyzing remote bundle resource com.springsource.javax.xml.stream...
[10:30:12]: [Transporter]: DEBUG:   ... resource is same as system bundle, skipping download.
[10:30:12]: [Transporter]: DEBUG: Analyzing remote bundle resource com.springsource.org.jaxen...
[10:30:12]: [Transporter]: DEBUG:   ... resource is same as system bundle, skipping download.
[10:30:12]: [Transporter]: DEBUG: Analyzing remote bundle resource com.springsource.org.jdom...
[10:30:12]: [Transporter]: DEBUG:   ... resource is same as system bundle, skipping download.
[10:30:12]: [Transporter]: DEBUG: Analyzing remote bundle resource org.json.simple...
[10:30:12]: [Transporter]: DEBUG:   ... resource is same as system bundle, skipping download.
[10:30:12]: [Transporter]: DEBUG: Analyzing remote bundle resource com.apple.jingle.leghorn...
[10:32:07]: [Transporter]: DEBUG:   ... updated bundle successfully retrieved.
[10:32:07]: [Transporter]: DEBUG: Analyzing remote bundle resource org.osgi.service.obr...
[10:32:07]: [Transporter]: DEBUG:   ... resource is same as system bundle, skipping download.
[10:32:07]: [Transporter]: DEBUG: Analyzing remote bundle resource com.signiant.interactivetransfer...
[10:32:07]: [Transporter]: DEBUG:   ... resource is same as system bundle, skipping download.
[10:32:07]: [Transporter]: DEBUG: Analyzing remote bundle resource com.apple.transporter.resources...
[10:32:08]: [Transporter]: DEBUG:   ... updated bundle successfully retrieved.
[10:32:08]: [Transporter]: INFO: Transporter has been successfully updated. The updated components will be available the next time Transporter runs.
[10:32:09]: [Transporter]: INFO: Logging configured successfully.
[10:32:09]: [Transporter]: INFO: iTMSTransporter : iTunes Store Transporter [1.8.3]
[10:32:09]: [Transporter]: INFO: OS identifier: Mac OS X 10.10.4 (x86_64); jvm=24.80-b07; jre=1.7.0-internal-root_2015_01_13_21_57-b00
[10:32:09]: [Transporter]: INFO: Memory: [JVM] 55M free, 71M total, 910M max [System] (Physical) 18M free, 2048M total (Swap) 757M free, 2048M total
[10:32:09]: [Transporter]: INFO: LookupMetadata mode selected.
[10:32:09]: [Transporter]: INFO: Performing lookupMetadata request ...
[10:32:09]: [Transporter]: INFO: Looking up the metadata with the apple_id '957168333' ...
[10:32:09]: [Transporter]: DBG-X: Memory: [JVM] 55M free, 71M total, 910M max [System] (Physical) 18M free, 2048M total (Swap) 756M free, 2048M total
[10:32:09]: [Transporter]: DBG-X: Using operation named: lookupMetadataWithArguments
[10:32:09]: [Transporter]: DBG-X: Apple's web service operation input parameters:
[10:32:09]: [Transporter]: DBG-X:   parameter AppleId = 957168333
[10:32:09]: [Transporter]: DBG-X:   parameter Application = iTMSTransporter
[10:32:09]: [Transporter]: DBG-X:   parameter BaseVersion = 1.8.3
[10:32:09]: [Transporter]: DBG-X:   parameter OSIdentifier = Mac OS X 10.10.4 (x86_64); jvm=24.80-b07; jre=1.7.0-internal-root_2015_01_13_21_57-b00
[10:32:09]: [Transporter]: DBG-X:   parameter Password = **hidden value**
[10:32:09]: [Transporter]: DBG-X:   parameter TransporterArguments = -m lookupMetadata -u kjdhgksjdhfg@gmail.com -p **hidden value** -apple_id 957168333 -destination /tmp
[10:32:09]: [Transporter]: DBG-X:   parameter Username = kjdhgksjdhfg@gmail.com
[10:32:09]: [Transporter]: DBG-X:   parameter VendorId = (null)
[10:32:09]: [Transporter]: DBG-X:   parameter Version = 1.8.3
[10:32:09]: [Transporter]: INFO: id = 20150721103209-347
[10:32:10]: [Transporter]: DBG-X: Apple's web service operation return value:
[10:32:10]: [Transporter]: DBG-X:   parameter ErrorMessage = Your Apple ID or password was entered incorrectly. (-20101)
[10:32:10]: [Transporter]: DBG-X:   parameter Errors = [Your Apple ID or password was entered incorrectly. (-20101)]
[10:32:10]: [Transporter]: DBG-X:   parameter ErrorCode = -20101
[10:32:10]: [Transporter]: DBG-X:   parameter Success = false
[10:32:10]: [Transporter Error Output]: Your Apple ID or password was entered incorrectly. (-20101)
It seems like the username or password for the account 'kjdhgksjdhfg@gmail.com' is wrong.
Do you want to re-enter your username and password? (y/n)
y
 Removing keychain item: deliver.kjdhgksjdhfg@gmail.com
keychain: "/Users/kjdhgksjdhfg/Library/Keychains/login.keychain"
class: "inet"
attributes:
    0x00000007 <blob>="deliver.kjdhgksjdhfg@gmail.com"
    0x00000008 <blob>=<NULL>
    "acct"<blob>="kjdhgksjdhfg@gmail.com"
    "atyp"<blob>="dflt"
    "cdat"<timedate>=0x32303135303131353138353732395A00  "20150115185729Z\000"
    "crtr"<uint32>=<NULL>
    "cusi"<sint32>=<NULL>
    "desc"<blob>=<NULL>
    "icmt"<blob>=<NULL>
    "invi"<sint32>=<NULL>
    "mdat"<timedate>=0x32303135303131353138353732395A00  "20150115185729Z\000"
    "nega"<sint32>=<NULL>
    "path"<blob>=<NULL>
    "port"<uint32>=0x00000000
    "prot"<blob>=<NULL>
    "ptcl"<uint32>=0x00000000
    "scrp"<sint32>=<NULL>
    "sdmn"<blob>=<NULL>
    "srvr"<blob>="deliver.kjdhgksjdhfg@gmail.com"
    "type"<uint32>=<NULL>
password has been deleted.
You will have to re-run the recent command to use the new username/password.
[10:32:59]: [Transporter]: DBG-X: The error code is: -20101
[10:32:59]: Transporter transfer failed.
[10:32:59]:
[10:32:59]: Your Apple ID or password was entered incorrectly. (-20101)
[10:32:59]: Return status of iTunes Transporter was 1: Your Apple ID or password was entered incorrectly. (-20101)
[10:32:59]: Your Apple ID or password was entered incorrectly. (-20101)
Return status of iTunes Transporter was 1: Your Apple ID or password was entered incorrectly. (-20101)
[10:32:59]: Could not download metadata from iTunes Connect! It's probably related to your password or your internet connection.
[10:32:59]: Error occurred with the setup program! Reverting changes now!
[10:32:59]: Deleting the 'fastlane' folder
/Library/Ruby/Gems/2.0.0/gems/deliver-0.12.1/lib/deliver/app_metadata.rb:314:in `read': No such file or directory - /tmp/957168333.itmsp//metadata.xml (Errno::ENOENT)
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.12.1/lib/deliver/app_metadata.rb:314:in `parse_package'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.12.1/lib/deliver/app_metadata.rb:66:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.12.1/lib/deliver/app.rb:120:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.12.1/lib/deliver/app.rb:120:in `metadata'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.12.1/lib/deliver/deliverfile/deliverfile_creator.rb:59:in `create_based_on_identifier'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.12.1/lib/deliver/deliverfile/deliverfile_creator.rb:31:in `create'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.11.0/lib/fastlane/setup.rb:95:in `ask_to_enable_other_tools'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.11.0/lib/fastlane/setup.rb:22:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.11.0/bin/fastlane:48:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.11.0/bin/fastlane:124:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.11.0/bin/fastlane:130:in `<top (required)>'
	from /usr/bin/fastlane:23:in `load'
	from /usr/bin/fastlane:23:in `<main>'
```

**Comment by KrauseFx** [comment]
The easiest way it to open the Keychain and search for `deliver.` and remove the outdated entry or directly update the password there.

**Comment by ricardopereira** [comment]
Done :+1:
