### ISSUE TITLE
Sigh error

### ISSUE THREAD

**Issue by mark5422** [KrauseFx/fastlane#452]
I'm having an error when trying to use sigh within a lane. Here's the error I'm getting...

```
[21:20:05]: Starting login
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.3.2/lib/spaceship/client.rb:233:in `parse_response': {"creationTimestamp"=>"2015-07-27T20:20:07Z", "resultCode"=>0, "userLocale"=>"en_US", "protocolVersion"=>"QH65B2", "requestId"=>nil, "requestUrl"=>"https://developer.apple.com:443//services-account/QH65B2/account/listTeams.action", "responseId"=>"8ce5abe1-3e96-4103-98ab-20d3adc50605", "isAdmin"=>nil, "isMember"=>nil, "isAgent"=>nil, "pageNumber"=>nil, "pageSize"=>nil, "totalRecords"=>nil, "httpResponseHeaders"=>nil} (Spaceship::Client::UnexpectedResponse)
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.3.2/lib/spaceship/portal/portal_client.rb:53:in `teams'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.3.2/lib/spaceship/portal/ui/select_team.rb:35:in `select_team'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.3.2/lib/spaceship/portal/portal_client.rb:69:in `select_team'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.3.2/lib/spaceship/portal/spaceship.rb:37:in `select_team'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.3.2/lib/spaceship/portal/spaceship.rb:71:in `select_team'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-0.10.3/lib/sigh/spaceship/runner.rb:12:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-0.10.3/lib/sigh/manager.rb:7:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-0.10.3/bin/sigh:36:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-0.10.3/bin/sigh:88:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-0.10.3/bin/sigh:95:in `<top (required)>'
	from /usr/bin/sigh:23:in `load'
	from /usr/bin/sigh:23:in `<main>'
```

**Comment by KrauseFx** [comment]
Is it working when you run `sigh` directly from the command line? Has it worked for you before?

**Comment by mark5422** [comment]
It doesn’t work directly, nor have I had it work before.

**Comment by mark5422** [comment]
This is no longer an issue but I’m also not sure how I fixed it.

**Comment by KrauseFx** [comment]
It was probably a temporary server issue.
