### ISSUE TITLE
Build error with Jenkins

### ISSUE THREAD

**Issue by mark5422** [KrauseFx/fastlane#460]
I'm getting an error when I try and build with Jenkins. I've had it working up until I changed the settings for code signing following the guide for code signing and modifying the project.pbxproj file.

```
[23:26:08]: set -o pipefail && krausefx-ipa build -s "MyAppScheme" -m "/Users/jenkins/.jenkins/jobs/MyAppBeta/workspace/iOS/AdHoc_com.mysite.myapp-beta.mobileprovision" --verbose | xcpretty
[23:26:08]: [SHELL COMMAND]: set -o pipefail && krausefx-ipa build -s "MyAppScheme" -m "/Users/jenkins/.jenkins/jobs/MyAppBeta/workspace/iOS/AdHoc_com.mysite.myapp-beta.mobileprovision" --verbose | xcpretty
[23:26:32]: [SHELL]: 2015-07-29 23:26:32.133 xcodebuild[49686:3674967] [MT] DVTAssertions: Warning in /SourceCache/IDEFrameworks/IDEFrameworks-7703/IDEFoundation/SourceControl/Model/IDESourceControlManager.m:423
[23:26:32]: [SHELL]: Details:  Error Domain=com.apple.dt.IDESourceControlErrorDomain Code=-1 "Missing extension: public.vcs.subversion" UserInfo=0x7fc88ce6cfa0 {NSLocalizedDescription=Missing extension: public.vcs.subversion}
[23:26:32]: [SHELL]: Object:   <IDESourceControlManager: 0x7fc88ce69310>
[23:26:32]: [SHELL]: Method:   -loadRepositories
[23:26:32]: [SHELL]: Thread:   <NSThread: 0x7fc888d2e430>{number = 1, name = main}
[23:26:32]: [SHELL]: Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
[23:26:32]: [SHELL]: ▸ Cleaning MyApp/ExtensionKit [Release]
[23:26:33]: [SHELL]: ▸ Cleaning MyApp/MyAppToday [Release]
[23:26:33]: [SHELL]: /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.1.10/lib/xcpretty/parser.rb:350:in `===': invalid byte sequence in US-ASCII (ArgumentError)
[23:26:33]: [SHELL]: from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.1.10/lib/xcpretty/parser.rb:350:in `update_test_state'
[23:26:33]: [SHELL]: from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.1.10/lib/xcpretty/parser.rb:247:in `parse'
[23:26:33]: [SHELL]: from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.1.10/lib/xcpretty/formatters/formatter.rb:78:in `pretty_format'
[23:26:33]: [SHELL]: from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.1.10/lib/xcpretty/printer.rb:15:in `pretty_print'
[23:26:33]: [SHELL]: from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.1.10/bin/xcpretty:80:in `block in <top (required)>'
[23:26:33]: [SHELL]: from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.1.10/bin/xcpretty:79:in `each_line'
[23:26:33]: [SHELL]: from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.1.10/bin/xcpretty:79:in `<top (required)>'
[23:26:33]: [SHELL]: from /usr/bin/xcpretty:23:in `load'
[23:26:33]: [SHELL]: from /usr/bin/xcpretty:23:in `<main>'
[23:26:42]: [SHELL]: ** BUILD FAILED **
[23:26:42]: [SHELL]: 
[23:26:42]: [SHELL]: 
[23:26:42]: [SHELL]: The following build commands failed:
[23:26:42]: [SHELL]: Check dependencies
[23:26:42]: [SHELL]: (1 failure)
[23:26:43]: [SHELL]: ** ARCHIVE FAILED **
[23:26:43]: [SHELL]: 
[23:26:43]: [SHELL]: 
[23:26:43]: [SHELL]: The following build commands failed:
[23:26:43]: [SHELL]: Check dependencies
[23:26:43]: [SHELL]: (1 failure)
[23:26:43]: -------------------------------------------------------
[23:26:43]: Original Error:
[23:26:43]:  => Exit status of command 'set -o pipefail && krausefx-ipa build -s "MyAppScheme" -m "/Users/jenkins/.jenkins/jobs/MyAppBeta/workspace/iOS/AdHoc_com.mysite.myapp-beta.mobileprovision" --verbose | xcpretty' was 256 instead of 0. 
2015-07-29 23:26:32.133 xcodebuild[49686:3674967] [MT] DVTAssertions: Warning in /SourceCache/IDEFrameworks/IDEFrameworks-7703/IDEFoundation/SourceControl/Model/IDESourceControlManager.m:423
Details:  Error Domain=com.apple.dt.IDESourceControlErrorDomain Code=-1 "Missing extension: public.vcs.subversion" UserInfo=0x7fc88ce6cfa0 {NSLocalizedDescription=Missing extension: public.vcs.subversion}
Object:   <IDESourceControlManager: 0x7fc88ce69310>
Method:   -loadRepositories
Thread:   <NSThread: 0x7fc888d2e430>{number = 1, name = main}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
▸ Cleaning MyApp/ExtensionKit [Release]
▸ Cleaning MyApp/MyAppToday [Release]
/Library/Ruby/Gems/2.0.0/gems/xcpretty-0.1.10/lib/xcpretty/parser.rb:350:in `===': invalid byte sequence in US-ASCII (ArgumentError)
	from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.1.10/lib/xcpretty/parser.rb:350:in `update_test_state'
	from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.1.10/lib/xcpretty/parser.rb:247:in `parse'
	from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.1.10/lib/xcpretty/formatters/formatter.rb:78:in `pretty_format'
	from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.1.10/lib/xcpretty/printer.rb:15:in `pretty_print'
	from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.1.10/bin/xcpretty:80:in `block in <top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.1.10/bin/xcpretty:79:in `each_line'
	from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.1.10/bin/xcpretty:79:in `<top (required)>'
	from /usr/bin/xcpretty:23:in `load'
	from /usr/bin/xcpretty:23:in `<main>'
** BUILD FAILED **
```

**Comment by mark5422** [comment]
Fastfile - This is the lane that's being run
```
  desc "Build a new beta release"
  lane :beta do
    sigh(adhoc: true)

    # use the UDID of the newly created provisioning profile
    ENV["PROFILE_UDID"] = lane_context[SharedValues::SIGH_UDID]

    ipa(scheme: "SyncSpace")
  end
```

**Comment by mark5422** [comment]
Appfile
```
for_platform :ios do
	for_lane :beta do
		app_identifier "com.mysite.myapp-beta"
	end
end
```

**Comment by KrauseFx** [comment]
Jenkins configures your environment wrong, so you have to fix it: http://stackoverflow.com/a/17031697/445598, should be easy to do so :+1:

**Comment by mark5422** [comment]
Do I just run this directly from the command line when running as jenkins or is there some other step I need to follow or some place that this should be interred in my jenkins configurations?

**Comment by KrauseFx** [comment]
You can just add this in your `Build Step` before triggering fastlane.

**Comment by mark5422** [comment]
I added this and it didn't fix my issue. Building directly on the machine that runs Jenkins gave me a different error. It seems like it's down to an issue of sigh not finding the manually created profiles and making its own. It finds those just fine each time, just not the ones that were created for the project.

I'm having to do the signing with sigh and inject them into the project directly as it contains a Today widget which needs its own provisioning and I'm trying to get an AdHoc build created.

Is there any advice you can give me on to the sigh issue or should I add another issue within sigh for that and close this one?

Thanks.

**Comment by KrauseFx** [comment]
@mark5422 I assume you don't have the private key and certificate on your Jenkins machine installed. How does `Jenkins` run? As its own user? Did you take a look at the Jenkins guide in the docs section of this repo?

**Comment by mark5422** [comment]
Jenkins runs as its own user. I did take a look at the Jenkins guide. Everything runs so long as I don't try and use a specific profile or build using a configuration that requires one. As soon as I do either I get the problem.

What I'm seeing right now is this

Code Sign error: Provisioning profile does not match bundle identifier: The provisioning profile specified in your build settings (“SyncSpaceToday AdHoc 1438695107”) has an AppID of “com.infinitekind.whiteboard-beta.SyncSpaceToday” which does not match your bundle identifier “com.infinitekind.whiteboard.SyncSpaceToday.SyncSpaceToday”.

The profile with the number on the end is being generated when sigh cannot find the profiles. I cannot find out where the bundle identifier is coming from that it's not matching.

**Comment by sebastianmass** [comment]
Got the same issue, worked like a charm few days ago, did update and have this problem.

**Comment by sreilly** [comment]
This is a jenkins and not a fastlane issue, so it can be closed.  One solution is to set the locale environment variables at the beginning of the shell script step.

**Comment by KrauseFx** [comment]
:+1:
