### ISSUE TITLE
Sigh fails with an exception if Appfile doesn't contain credentials for the lane (Running from Jenkins)

### ISSUE THREAD

**Issue by mttlmnt** [KrauseFx/fastlane#466]
I changed my lane name, but forgot to change the for_lane section in the Apple to match.  The following happened.

```
/bin/sh -xe /var/folders/1_/vs3c7xkj74n1ktl65wq8vkl80000gn/T/hudson653614735305346618.sh
+ export PATH=/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin
+ PATH=/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin
+ export LC_ALL=en_US.UTF-8
+ LC_ALL=en_US.UTF-8
+ cd ios
+ fastlane jenkins
[14:56:08]: Driving the lane 'jenkins' 🚀
[14:56:08]: ------------------
[14:56:08]: --- Step: sigh ---
[14:56:08]: ------------------
[14:56:25]: Starting login
[14:56:25]: To not be asked about this value, you can specify it using 'username'
Your Apple ID Username: [14:56:25]: Variable Dump:
[14:56:25]: {:ENVIRONMENT=>nil, :PLATFORM_NAME=>nil, :LANE_NAME=>"jenkins"}
[14:56:25]: undefined method `strip' for nil:NilClass

+------+--------+-------------+
|      fastlane summary       |
+------+--------+-------------+
| Step | Action | Time (in s) |
+------+--------+-------------+
| 1    | sigh   | 17          |
+------+--------+-------------+

[14:56:25]: fastlane finished with errors
/Library/Ruby/Gems/2.0.0/gems/highline-1.7.2/lib/highline/question.rb:413:in `remove_whitespace': undefined method `strip' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/highline-1.7.2/lib/highline.rb:873:in `get_line'
	from /Library/Ruby/Gems/2.0.0/gems/highline-1.7.2/lib/highline.rb:891:in `get_response'
	from /Library/Ruby/Gems/2.0.0/gems/highline-1.7.2/lib/highline.rb:264:in `ask'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.11.1/lib/fastlane_core/configuration/configuration.rb:136:in `fetch'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-0.10.3/lib/sigh/spaceship/runner.rb:11:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-0.10.3/lib/sigh/manager.rb:7:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.12.0/lib/fastlane/actions/sigh.rb:20:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.12.0/lib/fastlane/runner.rb:142:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.12.0/lib/fastlane/actions/actions_helper.rb:62:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.12.0/lib/fastlane/runner.rb:128:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.12.0/lib/fastlane/runner.rb:127:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.12.0/lib/fastlane/runner.rb:127:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.12.0/lib/fastlane/fast_file.rb:120:in `method_missing'
	from (eval):3:in `block (2 levels) in parse'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.12.0/lib/fastlane/lane.rb:29:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.12.0/lib/fastlane/lane.rb:29:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.12.0/lib/fastlane/runner.rb:50:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.12.0/lib/fastlane/runner.rb:44:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.12.0/lib/fastlane/runner.rb:44:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.12.0/lib/fastlane/lane_manager.rb:36:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.12.0/lib/fastlane/command_line_handler.rb:31:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.12.0/bin/fastlane:35:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.12.0/bin/fastlane:124:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.12.0/bin/fastlane:130:in `<top (required)>'
	from /usr/bin/fastlane:23:in `load'
	from /usr/bin/fastlane:23:in `<main>'

#######################################################################
# fastlane 1.14.0 is available. You are on 1.12.0.
# It is recommended to use the latest version.
# Update using 'sudo gem update fastlane'.
# To see what's new, open https://github.com/KrauseFx/fastlane/releases.
#######################################################################
```

**Comment by KrauseFx** [comment]
Thanks, fixed :+1:
