### ISSUE TITLE
DELIVER_VERSION is sometimes an empty string

### ISSUE THREAD

**Issue by Intellicode** [KrauseFx/fastlane#467]
If `DELIVER_VERSION` is an empty string, the deliver tool will assign an empty string as version number, and thus the app store submission will fail. I'm not sure where this issue should be fixed, but I'm opening it here since this is the origin of the variable. I can fix it myself and make a pull request, but I'd like to know where the best place is to fix it or if I simply did something wrong what could have made this variable an empty string.

For now I have the following code in the deliver project that helps to resolve the issue:

https://github.com/Intellicode/deliver/commit/3814208a78899f5ef3b3e7264a0834ab7d1663dd

```
/Library/Ruby/Gems/2.0.0/gems/deliver-0.13.0/lib/deliver/app_metadata.rb:81:in `verify_version': Version mismatch: on iTunesConnect the latest version is '1.0', you specified '' (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.13.0/lib/deliver/deliver_process.rb:211:in `verify_app_on_itunesconnect'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.13.0/lib/deliver/deliver_process.rb:38:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.13.0/lib/deliver/deliverer.rb:135:in `finished_executing_deliver_file'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.13.0/lib/deliver/deliverfile/deliverfile.rb:31:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.13.0/lib/deliver/deliverer.rb:87:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.13.0/lib/deliver/deliverer.rb:87:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.13.1/lib/fastlane/actions/deliver.rb:21:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.13.1/lib/fastlane/actions/deliver.rb:21:in `block in run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.13.1/lib/fastlane/actions/deliver.rb:17:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.13.1/lib/fastlane/actions/deliver.rb:17:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.13.1/lib/fastlane/runner.rb:142:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.13.1/lib/fastlane/actions/actions_helper.rb:62:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.13.1/lib/fastlane/runner.rb:128:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.13.1/lib/fastlane/runner.rb:127:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.13.1/lib/fastlane/runner.rb:127:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.13.1/lib/fastlane/fast_file.rb:120:in `method_missing'
	from (eval):63:in `block (3 levels) in parse'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.13.1/lib/fastlane/lane.rb:29:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.13.1/lib/fastlane/lane.rb:29:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.13.1/lib/fastlane/runner.rb:50:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.13.1/lib/fastlane/runner.rb:44:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.13.1/lib/fastlane/runner.rb:44:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.13.1/lib/fastlane/lane_manager.rb:36:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.13.1/lib/fastlane/command_line_handler.rb:31:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.13.1/bin/fastlane:35:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.13.1/bin/fastlane:124:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.13.1/bin/fastlane:130:in `<top (required)>'
	from /usr/bin/fastlane:23:in `load'
	from /usr/bin/fastlane:23:in `<main>'
```

**Comment by KrauseFx** [comment]
Thanks for reporting, I already pushed a fix, this will be in the next version :+1:

**Comment by Intellicode** [comment]
Thanks a lot!

**Comment by KrauseFx** [comment]
@Intellicode over the next week probably. You can easily install it on your local computer by cloning `fastlane_core` and running `bundle install && rake install`
