### ISSUE TITLE
Blocks / loops no longer works in Appfile

### ISSUE THREAD

**Issue by bartoszj** [KrauseFx/fastlane#495]
In previous version of Fastlane (0.15.0) I was able to use blocks / loops to make something like:

```ruby
app_identifier "*"
apple_id "myAppleId@mail.com"

for_platform :ios do
  [
    :lane_name1,
    :lane_name2,
  ].each do |lane_name|
    for_lane lane_name do
      app_identifier "*"
      apple_id "otherAppleId@mail.com"
      team_id "TEAMID"
    end
  end
end
```

But since version 0.16.0 I'm receiving this error:
```
/Library/Ruby/Gems/2.0.0/gems/credentials_manager-0.7.1/lib/credentials_manager/appfile_config.rb:10:in `rescue in try_fetch_value': uninitialized constant CredentialsManager::AppfileConfig::Helper (NameError)
	from /Library/Ruby/Gems/2.0.0/gems/credentials_manager-0.7.1/lib/credentials_manager/appfile_config.rb:7:in `try_fetch_value'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-0.10.3/lib/sigh/options.rb:33:in `available_options'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.16.0/lib/fastlane/actions/sigh.rb:42:in `available_options'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.16.0/lib/fastlane/configuration_helper.rb:17:in `parse'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.16.0/lib/fastlane/runner.rb:134:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.16.0/lib/fastlane/actions/actions_helper.rb:62:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.16.0/lib/fastlane/runner.rb:128:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.16.0/lib/fastlane/runner.rb:127:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.16.0/lib/fastlane/runner.rb:127:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.16.0/lib/fastlane/fast_file.rb:120:in `method_missing'
	from (eval):67:in `block (3 levels) in parse'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.16.0/lib/fastlane/lane.rb:32:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.16.0/lib/fastlane/lane.rb:32:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.16.0/lib/fastlane/runner.rb:50:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.16.0/lib/fastlane/runner.rb:44:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.16.0/lib/fastlane/runner.rb:44:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.16.0/lib/fastlane/lane_manager.rb:36:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.16.0/lib/fastlane/command_line_handler.rb:31:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.16.0/bin/fastlane:35:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.16.0/bin/fastlane:124:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.16.0/bin/fastlane:130:in `<top (required)>'
	from /usr/bin/fastlane:23:in `load'
	from /usr/bin/fastlane:23:in `<main>'
```

**Comment by KrauseFx** [comment]
That's not good, I'll look into it as soon as possible.

**Comment by KrauseFx** [comment]
I can reproduce this issue and am working on a fix.

**Comment by bartoszj** [comment]
There is a small progress since version `0.17.0`. Now when I'm running Fastlane I'm receiving:

```
[13:22:48]: -------------------------------------------------
[13:22:48]: --- Step: Verifying required fastlane version ---
[13:22:48]: -------------------------------------------------
[13:22:48]: fastlane version valid
[13:22:48]: ------------------------------
[13:22:48]: --- Step: default_platform ---
[13:22:48]: ------------------------------
[13:22:48]: Driving the lane 'ios lane_name1' 🚀
[13:22:48]: ------------------
[13:22:48]: --- Step: sigh ---
[13:22:48]: ------------------
undefined method `call' for #<Array:0x007fad925a2ea8>
undefined method `call' for #<Array:0x007fad925ba788>
[13:22:48]: Starting login
[13:22:48]: To not be asked about this value, you can specify it using 'username'
Your Apple ID Username:
```

It is asking me for Apple ID, but I've just provided it in the Appfile.

When I remove `for_platform` and use only `each` block with `for_lane` everything starts working.

**Comment by KrauseFx** [comment]
I just pushed a new version, please update using `sudo gem update credentials_manager` :+1:

**Comment by KrauseFx** [comment]
Let me know if that works for you

**Comment by bartoszj** [comment]
Yes, it works. Thanks!

**Comment by KrauseFx** [comment]
Perfect :rocket:
