### ISSUE TITLE
'fastlane test' failing

### ISSUE THREAD

**Issue by Liquidsoul** [KrauseFx/fastlane#506]
Hi @KrauseFx !

I have this error when I run `fastlane test` in `fastlane` repository or in `gym`:

```
/Library/Ruby/Gems/2.0.0/gems/fastlane-1.17.1/lib/fastlane/actions/actions_helper.rb:113:in `sh_no_action': Exit status of command 'cd .. && rake install' was 256 instead of 0.  (RuntimeError)
fastlane 1.17.1 built to pkg/fastlane-1.17.1.gem.
rake aborted!
Couldn't install gem, run `gem install /Users/sduperron/dev/Fastlane/fastlane/pkg/fastlane-1.17.1.gem' for more detailed output
/Library/Ruby/Gems/2.0.0/gems/bundler-1.10.6/lib/bundler/gem_helper.rb:87:in `install_gem'
/Library/Ruby/Gems/2.0.0/gems/bundler-1.10.6/lib/bundler/gem_helper.rb:44:in `block in install'
Tasks: TOP => install
(See full trace by running task with --trace)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.17.1/lib/fastlane/fast_file.rb:153:in `block in sh'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.17.1/lib/fastlane/actions/actions_helper.rb:62:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.17.1/lib/fastlane/fast_file.rb:152:in `sh'
	from (eval):116:in `block (2 levels) in parse'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.17.1/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.17.1/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.17.1/lib/fastlane/runner.rb:106:in `try_switch_to_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.17.1/lib/fastlane/fast_file.rb:112:in `rescue in method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.17.1/lib/fastlane/fast_file.rb:107:in `method_missing'
	from (eval):12:in `block (2 levels) in parse'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.17.1/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.17.1/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.17.1/lib/fastlane/runner.rb:50:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.17.1/lib/fastlane/runner.rb:44:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.17.1/lib/fastlane/runner.rb:44:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.17.1/lib/fastlane/lane_manager.rb:36:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.17.1/lib/fastlane/command_line_handler.rb:31:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.17.1/bin/fastlane:35:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.17.1/bin/fastlane:124:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.17.1/bin/fastlane:130:in `<top (required)>'
	from /usr/bin/fastlane:23:in `load'
	from /usr/bin/fastlane:23:in `<main>'
```

It's a permission issue when trying to install the gem. Executing `sudo fastlane test` works.

But I'm wondering if I may be missing something else or if it could be possible for the script to ask for `su` permission when reaching this step ?

**Comment by KrauseFx** [comment]
You will need to setup `rvm` to enable the `sudo less` installation. If you don't want to install `rvm`, `sudo fastlane test` is the way to go :+1:
