### ISSUE TITLE
pilot and fastfile

### ISSUE THREAD

**Issue by mark5422** [KrauseFx/fastlane#516]
Can you tell me if pilot can be used within a fastfile? I’m seeing action not found errors when I try to do so.

**Comment by KrauseFx** [comment]
Sorry, that's not implemented yet: https://github.com/fastlane/pilot/issues/18

What would you want to use it for? Uploading builds to TestFlight?

**Comment by mark5422** [comment]
Yes, sending build to TestFlight.

At the moment I’m using the testflight command within the fastfile though the docs suggest using pilot to upload builds to testflight now which is why I was trying to use that instead.

**Comment by mark5422** [comment]
What sent me down this path was also an error I’m getting uploading a build to TestFlight that transporter claims doesn’t have the correct bundle identifier.

I have two targets in the same project that use different bundle identifiers so was hopeful that pilot would make it easier to do that or fix my issue.

**Comment by mark5422** [comment]
For reference here’s the error -

[11:06:27]: ------------------------
[11:06:27]: --- Step: testflight ---
[11:06:27]: ------------------------
[11:06:33]: Got all information needed to deploy a new update ('') for app 'com.infinitekind.sketch-to'
[11:06:33]: Beta builds don't upload new metadata to iTunesConnect
[11:06:33]: Uploading ipa file to iTunesConnect
[11:06:34]: Going to upload updated app to iTunesConnect
[11:06:34]: This might take a few minutes, please don't interrupt the script
[11:06:44]: [Transporter]: INFO: Transporter is searching for updated software components.
[11:06:47]: [Transporter]: INFO: Transporter is up-to-date.
[11:06:47]: [Transporter]: INFO: Logging configured successfully.
[11:06:47]: [Transporter]: DEBUG: Attempting refresh of configuration data from https://contentdelivery.itunes.apple.com/transporter/Defaults.properties
[11:06:47]: [Transporter]: DEBUG: Configuration refresh successful.
[11:06:47]: [Transporter]: DEBUG: Saving configuration to local path: /Users/jenkins/.itmstransporter/Defaults.properties
[11:06:47]: [Transporter]: INFO: iTMSTransporter : iTunes Store Transporter [1.8.5]
[11:06:47]: [Transporter]: INFO: OS identifier: Mac OS X 10.10.5 (x86_64); jvm=24.80-b07; jre=1.7.0-internal-root_2015_01_13_21_57-b00
[11:06:48]: [Transporter]: INFO: Memory: [JVM] 39M free, 58M total, 910M max [System] (Physical) 74M free, 8192M total (Swap) 731M free, 1024M total
[11:06:48]: [Transporter]: INFO: Upload mode selected.
[11:06:48]: [Transporter]: INFO: Examining the package at: /tmp/408672838.itmsp
[11:06:48]: [Transporter]: INFO: Ensuring that package has well formed metadata file...
[11:06:48]: [Transporter]: DEBUG: Getting case-sensitive metadata xml filename...
[11:06:48]: [Transporter]: INFO: Gathering the list of valid files from the package ...
[11:06:48]: [Transporter]: DEBUG:   1de4bdf4d901b040b5c85cc685e3b9fd.ipa will be verified by Apple's web service to determine if it is a valid file.
[11:06:48]: [Transporter]: DEBUG:   ba7ee484ac257a85aecbfd9b357aecec.ipa will be verified by Apple's web service to determine if it is a valid file.
[11:06:48]: [Transporter]: DEBUG:   ce9e2f2ab38d74ffeace3c742bbce2c2.ipa will be verified by Apple's web service to determine if it is a valid file.
[11:06:48]: [Transporter]: DEBUG:   metadata.xml will be verified by Apple's web service to determine if it is a valid file.
[11:06:48]: [Transporter]: INFO: Finished gathering the list of valid files from the package.
[11:06:48]: [Transporter]: DEBUG:   Case-sensitive metadata filename is: metadata.xml
[11:06:48]: [Transporter]: INFO: Performing authentication of package 408672838.itmsp ...
[11:06:48]: [Transporter]: DBG-X: Memory: [JVM] 12M free, 58M total, 910M max [System] (Physical) 53M free, 8192M total (Swap) 731M free, 1024M total
[11:06:48]: [Transporter]: DBG-X: Memory: [JVM] 12M free, 58M total, 910M max [System] (Physical) 53M free, 8192M total (Swap) 731M free, 1024M total
[11:06:48]: [Transporter]: DBG-X: Using operation named: authenticateForSession
[11:06:48]: [Transporter]: DBG-X: Apple's web service operation input parameters:
[11:06:48]: [Transporter]: DBG-X:   parameter Application = iTMSTransporter
[11:06:48]: [Transporter]: DBG-X:   parameter BaseVersion = 1.8.3
[11:06:48]: [Transporter]: DBG-X:   parameter OSIdentifier = Mac OS X 10.10.5 (x86_64); jvm=24.80-b07; jre=1.7.0-internal-root_2015_01_13_21_57-b00
[11:06:48]: [Transporter]: DBG-X:   parameter Password = **hidden value**
[11:06:48]: [Transporter]: DBG-X:   parameter TransporterArguments = -m upload -u s@seanreilly.com -p **hidden value** -f /tmp//408672838.itmsp -t Signiant -k 100000
[11:06:48]: [Transporter]: DBG-X:   parameter Username = s@seanreilly.com
[11:06:48]: [Transporter]: DBG-X:   parameter Version = 1.8.5
[11:06:48]: [Transporter]: INFO: id = 20150820110648-596
[11:06:49]: [Transporter]: DBG-X: Apple's web service operation return value:
[11:06:49]: [Transporter]: DBG-X:   parameter SessionId = CKSmDBIQr//g/kzCT72lQO1ztF/DXA==
[11:06:49]: [Transporter]: DBG-X:   parameter SharedSecret = 73039599-62b8-4e86-b755-f51a773b88f1
[11:06:49]: [Transporter]: DBG-X: Deflated 432 bytes to 376
[11:06:49]: [Transporter]: DBG-X: Using operation named: validateMetadata
[11:06:49]: [Transporter]: DBG-X: Apple's web service operation input parameters:
[11:06:49]: [Transporter]: DBG-X:   parameter Application = iTMSTransporter
[11:06:49]: [Transporter]: DBG-X:   parameter BaseVersion = 1.8.3
[11:06:49]: [Transporter]: DBG-X:   parameter Files = [1de4bdf4d901b040b5c85cc685e3b9fd.ipa, ba7ee484ac257a85aecbfd9b357aecec.ipa, ce9e2f2ab38d74ffeace3c742bbce2c2.ipa, metadata.xml]
[11:06:49]: [Transporter]: DBG-X:   parameter Metadata = <?xml version="1.0" encoding="UTF-8"?>
[11:06:49]: [Transporter]: DBG-X:   parameter MetadataChecksum = e64f621e4d330c6435ce77e53babda84
[11:06:49]: [Transporter]: DBG-X:   parameter MetadataCompressed = (suppressed)
[11:06:49]: [Transporter]: DBG-X:   parameter OSIdentifier = Mac OS X 10.10.5 (x86_64); jvm=24.80-b07; jre=1.7.0-internal-root_2015_01_13_21_57-b00
[11:06:49]: [Transporter]: DBG-X:   parameter PackageName = 408672838.itmsp
[11:06:49]: [Transporter]: DBG-X:   parameter PackageSize = 45561913
[11:06:49]: [Transporter]: DBG-X:   parameter Throttle = 100000
[11:06:49]: [Transporter]: DBG-X:   parameter TransporterArguments = -m upload -u s@seanreilly.com -p **hidden value** -f /tmp//408672838.itmsp -t Signiant -k 100000
[11:06:49]: [Transporter]: DBG-X:   parameter Username = s@seanreilly.com
[11:06:49]: [Transporter]: DBG-X:   parameter Version = 1.8.5
[11:06:49]: [Transporter]: INFO: id = 20150820110649-153
[11:06:50]: [Transporter]: DBG-X: Apple's web service operation return value:
[11:06:50]: [Transporter]: DBG-X:   parameter CPUToken = 0329bb51-c8e9-4b7a-b9eb-4a306eba1404/1440065210062
[11:06:50]: [Transporter]: DBG-X:   parameter AssetsToDescribe = [{UTI=com.apple.ipa, Role=source, ShouldDescribeAsset=true, Filename=1de4bdf4d901b040b5c85cc685e3b9fd.ipa}]
[11:06:50]: [Transporter]: DBG-X:   parameter FileSizes = {1de4bdf4d901b040b5c85cc685e3b9fd.ipa=15187146}
[11:06:50]: [Transporter]: DBG-X:   parameter Checksums = {1de4bdf4d901b040b5c85cc685e3b9fd.ipa=840c430cd1422f9bb2694f3b34e42d3e}
[11:06:50]: [Transporter]: DBG-X:   parameter Success = true
[11:06:50]: [Transporter]: DBG-X:   parameter FilesToUpload = [metadata.xml, 1de4bdf4d901b040b5c85cc685e3b9fd.ipa]
[11:06:50]: [Transporter]: DBG-X:   parameter MinimumFileSizeThresholdForCheckum = 104857600
[11:06:50]: [Transporter]: DBG-X:   parameter ProviderNameForToken = SeanReilly9388939
[11:06:50]: [Transporter]: INFO: The list of files requested for upload by Apple is: [metadata.xml, 1de4bdf4d901b040b5c85cc685e3b9fd.ipa].  These are the files that will be uploaded.
[11:06:50]: [Transporter]: INFO: Starting media analysis of assets
[11:06:51]: [Transporter]: DEBUG: Handling asset: filename=1de4bdf4d901b040b5c85cc685e3b9fd.ipa,uti=com.apple.ipa,role=source,describe=true
[11:06:51]: [Transporter]: DEBUG: Using container type tool name and version: iOS App Describer:1.24
[11:06:51]: [Transporter]: DEBUG: Using path: /tmp/408672838.itmsp/1de4bdf4d901b040b5c85cc685e3b9fd.ipa
[11:06:57]: [Transporter]: DEBUG: Asset successfully described: com.apple.jingle.leghorn.software.AbstractSoftwareDescriber$1@434bc639
[11:06:57]: [Transporter]: INFO: Asset media analysis has completed
[11:06:57]: [Transporter]: DBG-X: Memory: [JVM] 23M free, 64M total, 910M max [System] (Physical) 70M free, 8192M total (Swap) 731M free, 1024M total
[11:06:57]: [Transporter]: DBG-X: Using operation named: lookupTransportDiagnostic
[11:06:57]: [Transporter]: DBG-X: Apple's web service operation input parameters:
[11:06:57]: [Transporter]: DBG-X:   parameter Application = iTMSTransporter
[11:06:57]: [Transporter]: DBG-X:   parameter BaseVersion = 1.8.3
[11:06:57]: [Transporter]: DBG-X:   parameter OSIdentifier = Mac OS X 10.10.5 (x86_64); jvm=24.80-b07; jre=1.7.0-internal-root_2015_01_13_21_57-b00
[11:06:57]: [Transporter]: DBG-X:   parameter TransporterArguments = -m upload -u s@seanreilly.com -p **hidden value** -f /tmp//408672838.itmsp -t Signiant -k 100000
[11:06:57]: [Transporter]: DBG-X:   parameter Username = s@seanreilly.com
[11:06:57]: [Transporter]: DBG-X:   parameter Version = 1.8.5
[11:06:57]: [Transporter]: INFO: id = 20150820110657-351
[11:06:58]: [Transporter]: DBG-X: Apple's web service operation return value:
[11:06:58]: [Transporter]: DBG-X:   parameter SigniantLoggingLevel = OFF
[11:06:58]: [Transporter]: DBG-X:   parameter AsperaLoggingLevel = OFF
[11:06:59]: [Transporter]: INFO: Signiant TransferEngine build 10.6.0.59156
[11:06:59]: [Transporter]: INFO: Using Signiant UDP transport
[11:06:59]: [Transporter]: DBG-X: Setting the target rate to 15000001 bytes per second.
[11:06:59]: [Transporter]: DBG-X: Setting the throttle to 12500000 bytes per second.
[11:06:59]: [Transporter]: INFO: Transfer engine: 10.6.0.59156
[11:06:59]: [Transporter]: INFO: The Signiant transfer engine's status is DISCONNECTED
[11:06:59]: [Transporter]: INFO: The Signiant transfer engine's status is CONNECTING
[11:06:59]: [Transporter]: INFO: Processing URL list: mxwan://sgr203.apple.com:44001/
[11:06:59]: [Transporter]: INFO: Trying UDP sgr203.apple.com/17.152.249.103:44001...
[11:07:01]: [Transporter]: INFO: Connected to UDP sgr203.apple.com/17.152.249.103:44001
[11:07:01]: [Transporter]: INFO: Authenticating
[11:07:03]: [Transporter]: INFO: The Signiant transfer engine's status is AWAITING_DATA_STREAMS
[11:07:03]: [Transporter]: INFO: Setting up data streams
[11:07:07]: [Transporter]: INFO: The Signiant transfer engine's status is CONNECTED
[11:07:07]: [Transporter]: INFO: Connected using WAN accelerator
[11:07:08]: [Transporter]: INFO:      File: 2c77d2cf-d788-4022-89f8-87a6e0f16dbb618618902551440959.txt 11/11, 100% completed
[11:07:08]: [Transporter]: DBG-X: The status for the file, 2c77d2cf-d788-4022-89f8-87a6e0f16dbb618618902551440959.txt, is TRANSFERRED.
[11:07:09]: [Transporter]: INFO: The Signiant transfer engine's status is DISCONNECTED
[11:07:10]: [Transporter]: INFO: The Signiant transfer engine's status is DISCONNECTED
[11:07:10]: [Transporter]: INFO: The Signiant transfer engine's status is DISCONNECTED
[11:07:10]: [Transporter]: DEBUG: An error has occurred during the upload.
[11:07:10]: [Transporter]: DEBUG: An exception has occurred: Scheduling automatic restart in 1 minute
[11:07:10]: [Transporter]: DEBUG: Transfer warning: Scheduling automatic restart in 1 minute
[11:07:10]: [Transporter]: DEBUG: Received failed transfer notification; aborting
[11:07:10]: [Transporter]: INFO: Scheduling automatic restart in 1 minute
[11:07:10]: [Transporter]: INFO: The Signiant transport is encountering difficulties with the upload. This may be caused by a firewall or network configuration preventing access.
[11:07:10]: [Transporter]: INFO: Signiant TransferEngine build 10.6.0.59156
[11:07:10]: [Transporter]: INFO: Using Signiant UDP transport
[11:07:10]: [Transporter]: DBG-X: Setting the target rate to 15000001 bytes per second.
[11:07:10]: [Transporter]: DBG-X: Setting the throttle to 12500000 bytes per second.
[11:07:10]: [Transporter]: INFO: Transfer engine: 10.6.0.59156
[11:07:10]: [Transporter]: INFO: Signiant TransferEngine build 10.6.0.59156
[11:07:10]: [Transporter]: INFO: Using Signiant UDP transport
[11:07:10]: [Transporter]: DBG-X: Setting the target rate to 15000001 bytes per second.
[11:07:10]: [Transporter]: DBG-X: Setting the throttle to 12500000 bytes per second.
[11:07:10]: [Transporter]: INFO: The Signiant transfer engine's status is CONNECTING
[11:07:10]: [Transporter]: INFO: The Signiant transfer engine's status is DISCONNECTED
[11:07:11]: [Transporter]: INFO: Signiant TransferEngine build 10.6.0.59156
[11:07:11]: [Transporter]: INFO: Using Signiant UDP transport
[11:07:11]: [Transporter]: DBG-X: Setting the target rate to 15000001 bytes per second.
[11:07:11]: [Transporter]: DBG-X: Setting the throttle to 12500000 bytes per second.
[11:07:11]: [Transporter]: INFO: Signiant TransferEngine build 10.6.0.59156
[11:07:11]: [Transporter]: INFO: Using Signiant UDP transport
[11:07:11]: [Transporter]: DBG-X: Setting the target rate to 15000001 bytes per second.
[11:07:11]: [Transporter]: DBG-X: Setting the throttle to 12500000 bytes per second.
[11:07:11]: [Transporter]: INFO: The Signiant transfer engine's status is DISCONNECTED
[11:07:11]: [Transporter]: INFO: The Signiant transfer engine's status is CONNECTING
[11:07:11]: [Transporter]: INFO: Processing URL list: mxwan://sgr203.apple.com:44001/
[11:07:11]: [Transporter]: INFO: Trying UDP sgr203.apple.com/17.152.249.103:44001...
[11:07:12]: [Transporter]: INFO: Connected to UDP sgr203.apple.com/17.152.249.103:44001
[11:07:12]: [Transporter]: INFO: Authenticating
[11:07:14]: [Transporter]: INFO: The Signiant transfer engine's status is AWAITING_DATA_STREAMS
[11:07:14]: [Transporter]: INFO: Setting up data streams
[11:07:16]: [Transporter]: INFO: The Signiant transfer engine's status is CONNECTED
[11:07:16]: [Transporter]: INFO: Connected using WAN accelerator
[11:07:16]: [Transporter]: INFO:      File: 44c4f00f-91bf-4be9-ac7e-b9f69f426bbf2427304190663371438.txt 11/11, 100% completed
[11:07:16]: [Transporter]: DBG-X: The status for the file, 44c4f00f-91bf-4be9-ac7e-b9f69f426bbf2427304190663371438.txt, is TRANSFERRED.
[11:07:17]: [Transporter]: INFO: The Signiant transfer engine's status is DISCONNECTED
[11:07:17]: [Transporter]: INFO: The Signiant transfer engine's status is DISCONNECTED
[11:07:17]: [Transporter]: DEBUG: Using token file path /Users/jenkins/.itmstransporter/UploadTokens/vegas.infinitekind.com_SeanReilly9388939_408672838.itmsp.token
[11:07:17]: [Transporter]: DEBUG: Attempting exclusive file lock on token file
[11:07:17]: [Transporter]: DEBUG: Token exists, examining
[11:07:17]: [Transporter]: DEBUG: Token pid: 63094, found process = false; my pid: 5214
[11:07:17]: [Transporter]: DEBUG: Reusing existing token: a420f80c-ba8f-4810-9d2b-2d0642165ce4/1439859763239
[11:07:17]: [Transporter]: DEBUG: Set token: a420f80c-ba8f-4810-9d2b-2d0642165ce4/1439859763239
[11:07:17]: [Transporter]: DBG-X: Memory: [JVM] 110M free, 156M total, 910M max [System] (Physical) 120M free, 8192M total (Swap) 731M free, 1024M total
[11:07:17]: [Transporter]: DBG-X: Deflated 432 bytes to 376
[11:07:18]: [Transporter]: DBG-X: Deflated 895233 bytes to 87992
[11:07:18]: [Transporter]: DBG-X: Using operation named: validateAssets
[11:07:18]: [Transporter]: DBG-X: Apple's web service operation input parameters:
[11:07:18]: [Transporter]: DBG-X:   parameter Application = iTMSTransporter
[11:07:18]: [Transporter]: DBG-X:   parameter BaseVersion = 1.8.3
[11:07:18]: [Transporter]: DBG-X:   parameter CPUToken = a420f80c-ba8f-4810-9d2b-2d0642165ce4/1439859763239
[11:07:18]: [Transporter]: DBG-X:   parameter Files = [1de4bdf4d901b040b5c85cc685e3b9fd.ipa, ba7ee484ac257a85aecbfd9b357aecec.ipa, ce9e2f2ab38d74ffeace3c742bbce2c2.ipa, metadata.xml]
[11:07:18]: [Transporter]: DBG-X:   parameter MetadataChecksum = e64f621e4d330c6435ce77e53babda84
[11:07:18]: [Transporter]: DBG-X:   parameter MetadataCompressed = (suppressed)
[11:07:18]: [Transporter]: DBG-X:   parameter OSIdentifier = Mac OS X 10.10.5 (x86_64); jvm=24.80-b07; jre=1.7.0-internal-root_2015_01_13_21_57-b00
[11:07:18]: [Transporter]: DBG-X:   parameter PackageName = 408672838.itmsp
[11:07:18]: [Transporter]: DBG-X:   parameter PackageSize = 15187578
[11:07:18]: [Transporter]: DBG-X:   parameter Throttle = 100000
[11:07:18]: [Transporter]: DBG-X:   parameter Transport = Signiant
[11:07:18]: [Transporter]: DBG-X:   parameter TransporterArguments = -m upload -u s@seanreilly.com -p **hidden value** -f /tmp//408672838.itmsp -t Signiant -k 100000
[11:07:18]: [Transporter]: DBG-X:   parameter Username = s@seanreilly.com
[11:07:18]: [Transporter]: DBG-X:   parameter Version = 1.8.5
[11:07:18]: [Transporter]: INFO: id = 20150820110718-237
[11:07:23]: [Transporter]: DBG-X: Apple's web service operation return value:
[11:07:23]: [Transporter]: DBG-X:   parameter ErrorMessage = ERROR ITMS-90054: "This bundle is invalid. The bundle identifier cannot be changed from the previous version. If you want to change your bundle identifier, you will need to create a new application in iTunes Connect."
[11:07:23]: [Transporter]: DBG-X:   parameter CPUToken = a420f80c-ba8f-4810-9d2b-2d0642165ce4/1439859763239
[11:07:23]: [Transporter]: DBG-X:   parameter AssetsToDescribe = [{UTI=com.apple.ipa, Role=source, ShouldDescribeAsset=true, Filename=1de4bdf4d901b040b5c85cc685e3b9fd.ipa}]
[11:07:23]: [Transporter]: DBG-X:   parameter FileSizes = {1de4bdf4d901b040b5c85cc685e3b9fd.ipa=15187146}
[11:07:23]: [Transporter]: DBG-X:   parameter Checksums = {1de4bdf4d901b040b5c85cc685e3b9fd.ipa=840c430cd1422f9bb2694f3b34e42d3e}
[11:07:23]: [Transporter]: DBG-X:   parameter Errors = [ERROR ITMS-90054: "This bundle is invalid. The bundle identifier cannot be changed from the previous version. If you want to change your bundle identifier, you will need to create a new application in iTunes Connect.", ERROR ITMS-90062: "This bundle is invalid. The value for key CFBundleShortVersionString [2.3] in the Info.plist file must contain a higher version than that of the previously approved version [5.4]."]
[11:07:23]: [Transporter]: DBG-X:   parameter ErrorCode = 1102
[11:07:23]: [Transporter]: DBG-X:   parameter Success = false
[11:07:23]: [Transporter]: DBG-X:   parameter FilesToUpload = [metadata.xml, 1de4bdf4d901b040b5c85cc685e3b9fd.ipa]
[11:07:23]: [Transporter]: DBG-X:   parameter MinimumFileSizeThresholdForCheckum = 104857600
[11:07:23]: [Transporter Error Output]: ERROR ITMS-90054: "This bundle is invalid. The bundle identifier cannot be changed from the previous version. If you want to change your bundle identifier, you will need to create a new application in iTunes Connect."

[11:07:23]: [Transporter Error Output]: ERROR ITMS-90062: "This bundle is invalid. The value for key CFBundleShortVersionString [2.3] in the Info.plist file must contain a higher version than that of the previously approved version [5.4]."

[11:07:23]: [Transporter]: DBG-X: The error code is: 1102
[11:07:23]: [Transporter]: INFO: Done performing authentication.
[11:07:23]: Transporter transfer failed.
[11:07:23]: 
[11:07:23]: ERROR ITMS-90054: "This bundle is invalid. The bundle identifier cannot be changed from the previous version. If you want to change your bundle identifier, you will need to create a new application in iTunes Connect."
ERROR ITMS-90062: "This bundle is invalid. The value for key CFBundleShortVersionString [2.3] in the Info.plist file must contain a higher version than that of the previously approved version [5.4]."

[11:07:23]: Return status of iTunes Transporter was 1: ERROR ITMS-90054: "This bundle is invalid. The bundle identifier cannot be changed from the previous version. If you want to change your bundle identifier, you will need to create a new application in iTunes Connect."
\nERROR ITMS-90062: "This bundle is invalid. The value for key CFBundleShortVersionString [2.3] in the Info.plist file must contain a higher version than that of the previously approved version [5.4]."

[11:07:23]: ERROR ITMS-90054: "This bundle is invalid. The bundle identifier cannot be changed from the previous version. If you want to change your bundle identifier, you will need to create a new application in iTunes Connect."
ERROR ITMS-90062: "This bundle is invalid. The value for key CFBundleShortVersionString [2.3] in the Info.plist file must contain a higher version than that of the previously approved version [5.4]."
Return status of iTunes Transporter was 1: ERROR ITMS-90054: "This bundle is invalid. The bundle identifier cannot be changed from the previous version. If you want to change your bundle identifier, you will need to create a new application in iTunes Connect."
\nERROR ITMS-90062: "This bundle is invalid. The value for key CFBundleShortVersionString [2.3] in the Info.plist file must contain a higher version than that of the previously approved version [5.4]."


#######################################################################
# deliver 0.13.1 is available. You are on 0.13.0.
# It is recommended to use the latest version.
# Update using 'sudo gem update deliver'.
# To see what's new, open https://github.com/KrauseFx/deliver/releases.
#######################################################################
[11:07:23]: Variable Dump:
[11:07:23]: {:DEFAULT_PLATFORM=>:ios, :ENVIRONMENT=>nil, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios sketchto_testflight", :SIGH_PROFILE_PATH=>"/tmp/AppStore_com.infinitekind.sketch-to.mobileprovision", :SIGH_UDID=>"c4a69ce0-7f60-4276-9c96-10ceb8fd0948", :IPA_OUTPUT_PATH=>"/Users/jenkins/.jenkins/jobs/SyncSpaceBeta/workspace/iOS/Sketch To.ipa", :DSYM_OUTPUT_PATH=>"/Users/jenkins/.jenkins/jobs/SyncSpaceBeta/workspace/iOS/Sketch To.app.dSYM.zip"}
[11:07:23]: Error uploading ipa file
+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | sigh                                | 30          |
| 4    | sigh                                | 11          |
| 5    | ipa                                 | 229         |
| 6    | testflight                          | 55          |
+------+-------------------------------------+-------------+

[11:07:23]: fastlane finished with errors
/Library/Ruby/Gems/2.0.0/gems/deliver-0.13.0/lib/deliver/deliver_process.rb:387:in `trigger_ipa_upload': Error uploading ipa file (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.13.0/lib/deliver/deliver_process.rb:48:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.13.0/lib/deliver/deliverer.rb:135:in `finished_executing_deliver_file'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.13.0/lib/deliver/deliverfile/deliverfile.rb:31:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.13.0/lib/deliver/deliverer.rb:87:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.13.0/lib/deliver/deliverer.rb:87:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.18.0/lib/fastlane/actions/deliver.rb:21:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.18.0/lib/fastlane/actions/deliver.rb:21:in `block in run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.18.0/lib/fastlane/actions/deliver.rb:17:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.18.0/lib/fastlane/actions/deliver.rb:17:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.18.0/lib/fastlane/actions/testflight.rb:13:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.18.0/lib/fastlane/runner.rb:142:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.18.0/lib/fastlane/actions/actions_helper.rb:62:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.18.0/lib/fastlane/runner.rb:128:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.18.0/lib/fastlane/runner.rb:127:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.18.0/lib/fastlane/runner.rb:127:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.18.0/lib/fastlane/fast_file.rb:120:in `method_missing'
	from (eval):134:in `block (3 levels) in parse'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.18.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.18.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.18.0/lib/fastlane/runner.rb:50:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.18.0/lib/fastlane/runner.rb:44:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.18.0/lib/fastlane/runner.rb:44:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.18.0/lib/fastlane/lane_manager.rb:36:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.18.0/lib/fastlane/command_line_handler.rb:31:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.18.0/bin/fastlane:35:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.18.0/bin/fastlane:124:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.18.0/bin/fastlane:130:in `<top (required)>'
	from /usr/bin/fastlane:23:in `load'
	from /usr/bin/fastlane:23:in `<main>'
Process leaked file descriptors. See http://wiki.jenkins-ci.org/display/JENKINS/Spawning+processes+from+build for more information

**Comment by mark5422** [comment]
My error was having the apple_id specified incorrectly and I see that pilot is now usable in fastlane so closing this issue. Thanks
