### ISSUE TITLE
getaddrinfo: nodename nor servname provided, or not known

### ISSUE THREAD

**Issue by moses-gangipogu** [KrauseFx/fastlane#538]
Sorry, we have to wait for iTunesConnect, since it's still processing the uploaded ipa file
If this takes longer than 45 minutes, you have to re-upload the ipa file again.
You can always open the browser page yourself: 'https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/ra/ng/app/appid/pre/builds'
Passed time: ~6 minute(s)

[10:26:55]: getaddrinfo: nodename nor servname provided, or not known (SocketError)

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | gym                                 | 723         |
| 4    | sigh                                | 29          |
| 5    | deliver                             | 849         |
+------+-------------------------------------+-------------+

[10:26:55]: fastlane finished with errors

```
/Library/Ruby/Gems/2.0.0/gems/excon-0.45.4/lib/excon/socket.rb:108:in `getaddrinfo': getaddrinfo: nodename nor servname provided, or not known (SocketError) (Excon::Errors::SocketError)
	from /Library/Ruby/Gems/2.0.0/gems/excon-0.45.4/lib/excon/socket.rb:108:in `connect'
	from /Library/Ruby/Gems/2.0.0/gems/excon-0.45.4/lib/excon/ssl_socket.rb:148:in `connect'
	from /Library/Ruby/Gems/2.0.0/gems/excon-0.45.4/lib/excon/socket.rb:28:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/excon-0.45.4/lib/excon/ssl_socket.rb:8:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/excon-0.45.4/lib/excon/connection.rb:387:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/excon-0.45.4/lib/excon/connection.rb:387:in `socket'
	from /Library/Ruby/Gems/2.0.0/gems/excon-0.45.4/lib/excon/connection.rb:106:in `request_call'
	from /Library/Ruby/Gems/2.0.0/gems/excon-0.45.4/lib/excon/middlewares/mock.rb:47:in `request_call'
	from /Library/Ruby/Gems/2.0.0/gems/excon-0.45.4/lib/excon/middlewares/instrumentor.rb:22:in `request_call'
	from /Library/Ruby/Gems/2.0.0/gems/excon-0.45.4/lib/excon/middlewares/base.rb:15:in `request_call'
	from /Library/Ruby/Gems/2.0.0/gems/excon-0.45.4/lib/excon/middlewares/base.rb:15:in `request_call'
	from /Library/Ruby/Gems/2.0.0/gems/excon-0.45.4/lib/excon/middlewares/base.rb:15:in `request_call'
	from /Library/Ruby/Gems/2.0.0/gems/excon-0.45.4/lib/excon/connection.rb:233:in `request'
	from /Library/Ruby/Gems/2.0.0/gems/excon-0.45.4/lib/excon.rb:229:in `get'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.13.1/lib/deliver/itunes_connect/itunes_connect_submission.rb:27:in `block in put_build_into_beta_testing!'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.13.1/lib/deliver/itunes_connect/itunes_connect_submission.rb:26:in `loop'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.13.1/lib/deliver/itunes_connect/itunes_connect_submission.rb:26:in `put_build_into_beta_testing!'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.13.1/lib/deliver/ipa_uploader.rb:113:in `publish_beta_build'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.13.1/lib/deliver/ipa_uploader.rb:93:in `publish_on_itunes_connect'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.13.1/lib/deliver/ipa_uploader.rb:77:in `upload!'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.13.1/lib/deliver/deliver_process.rb:386:in `trigger_ipa_upload'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.13.1/lib/deliver/deliver_process.rb:48:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.13.1/lib/deliver/deliverer.rb:135:in `finished_executing_deliver_file'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.13.1/lib/deliver/deliverfile/deliverfile.rb:31:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.13.1/lib/deliver/deliverer.rb:87:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.13.1/lib/deliver/deliverer.rb:87:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.19.0/lib/fastlane/actions/deliver.rb:21:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.19.0/lib/fastlane/actions/deliver.rb:21:in `block in run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.19.0/lib/fastlane/actions/deliver.rb:17:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.19.0/lib/fastlane/actions/deliver.rb:17:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.19.0/lib/fastlane/runner.rb:142:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.19.0/lib/fastlane/actions/actions_helper.rb:62:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.19.0/lib/fastlane/runner.rb:128:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.19.0/lib/fastlane/runner.rb:127:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.19.0/lib/fastlane/runner.rb:127:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.19.0/lib/fastlane/fast_file.rb:120:in `method_missing'
	from (eval):48:in `block (3 levels) in parse'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.19.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.19.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.19.0/lib/fastlane/runner.rb:50:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.19.0/lib/fastlane/runner.rb:44:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.19.0/lib/fastlane/runner.rb:44:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.19.0/lib/fastlane/lane_manager.rb:36:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.19.0/lib/fastlane/command_line_handler.rb:31:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.19.0/bin/fastlane:35:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.19.0/bin/fastlane:124:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.19.0/bin/fastlane:130:in `<top (required)>'
	from /usr/bin/fastlane:23:in `load'
	from /usr/bin/fastlane:23:in `<main>'
```

**Comment by sneps85** [comment]
I have exactly the same problem

**Comment by sneps85** [comment]
Seems that itunesconnect.apple.com was down...

**Comment by KrauseFx** [comment]
Thanks for letting me know :+1:

**Comment by pedro380085** [comment]
@sneps85 'was' is only temporary with Apple haha; it's offline again now.
