### ISSUE TITLE
After installing Xcode 7 Beta 6 fastlane won't run

### ISSUE THREAD

**Issue by barrettj** [KrauseFx/fastlane#546]
I get the following:

```
barretts-mbp:GoWorksheet barrettjacobsen$ fastlane
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:959:in `read': Permission denied - /Library/Ruby/Gems/2.0.0/specifications/aws-sdk-2.1.16.gemspec (Errno::EACCES)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:959:in `load'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:644:in `block (2 levels) in each_spec'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:643:in `each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:643:in `block in each_spec'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:642:in `each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:642:in `each_spec'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:658:in `each_normal'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:669:in `_all'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:822:in `each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb:253:in `find_all'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb:253:in `matching_specs'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb:277:in `to_specs'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb:307:in `to_spec'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_gem.rb:47:in `gem'
	from /usr/bin/fastlane:22:in `<main>'
````

**Comment by edwardvalentini** [comment]
i dont have this exact problem - but the problem I get now with Xcode7 beta 6 is that fastlane can't login to itunesconnect anymore when i am trying to deploy a beta app to testflight:

```
[14:05:02]: Couldn't find element '.ng-scope' after waiting for quite some time
[14:05:02]: Could not find Apple ID based on the app identifier in the US App Store. Maybe the app is not yet in the store?
[14:05:02]: You can provide the Apple ID of your app using `apple_id '974739333'` in your `Deliverfile`

Apple ID of your app (e.g. 284882215):
```

also fastlane displays this error photo:  

![error1440623102](https://cloud.githubusercontent.com/assets/1571326/9506254/da02a450-4bfb-11e5-8f98-9fe51522bbfd.png)

**Comment by barrettj** [comment]
My issue may be the result of files (selected apparently at random) on my system having their owner chanted to root and no longer being world accessible.  I'm guessing it might have been some random HFS+ corruption or something.

**Comment by edwardvalentini** [comment]
answering my own question - using pilot instead of deliver fixes this problem for me.

**Comment by KrauseFx** [comment]
@edwardvalentini You have a different error, I just pushed an update of deliver, please update to `deliver` 0.13.2 using `sudo gem update deliver`

**Comment by KrauseFx** [comment]
@barrettj Is your permission issue resolved?

**Comment by barrettj** [comment]
Yeah, if no one else had this issue when they installed beta 6 then it was likely just coincidental timing with my permissions issue.
