### ISSUE TITLE
Can't login to itunes connect, password is bad.

### ISSUE THREAD

**Issue by bmctigue** [KrauseFx/fastlane#561]
Fastlane gets all the way through uploading my app except when the deliver tries login to itunesconnect. I have the password set in the DELIVER_PASSWORD env and I know it's correct. I ran deliver init separately and have the same issue. Here's the complete output from running deliver init.:

```
Bruces-MacBook-Pro:fastlane bmctigue$ deliver init
Do you want Deliver to automatically create the Deliverfile for you based on your current app? The app has to be in the App Store to use this feature. (y/n)
y


First, you need to login with your iTunesConnect credentials. 
This is necessary to fetch the latest metadata from your app and use it to create a Deliverfile for you.
If you have previously entered your credentials already, you will not be asked again.
[17:39:42]: Going to download app metadata from iTunesConnect
[17:39:46]: [Transporter]: INFO: Transporter is skipping bundle update check: Already checked recently.
[17:39:47]: [Transporter]: INFO: Logging configured successfully.
[17:39:47]: [Transporter]: INFO: iTMSTransporter : iTunes Store Transporter [1.8.5]
[17:39:47]: [Transporter]: INFO: OS identifier: Mac OS X 10.10.5 (x86_64); jvm=24.80-b07; jre=1.7.0-internal-root_2015_01_13_21_57-b00
[17:39:47]: [Transporter]: INFO: Memory: [JVM] 33M free, 56M total, 910M max [System] (Physical) 762M free, 8192M total (Swap) 985M free, 1024M total
[17:39:47]: [Transporter]: INFO: LookupMetadata mode selected.
[17:39:47]: [Transporter]: INFO: Performing lookupMetadata request ...
[17:39:47]: [Transporter]: INFO: Looking up the metadata with the apple_id '963755876' ...
[17:39:47]: [Transporter]: DBG-X: Memory: [JVM] 33M free, 56M total, 910M max [System] (Physical) 762M free, 8192M total (Swap) 985M free, 1024M total
[17:39:47]: [Transporter]: DBG-X: Memory: [JVM] 33M free, 56M total, 910M max [System] (Physical) 762M free, 8192M total (Swap) 985M free, 1024M total
[17:39:47]: [Transporter]: DBG-X: Using operation named: authenticateForSession
[17:39:47]: [Transporter]: DBG-X: Apple's web service operation input parameters:
[17:39:47]: [Transporter]: DBG-X:   parameter Application = iTMSTransporter
[17:39:47]: [Transporter]: DBG-X:   parameter BaseVersion = 1.8.3
[17:39:47]: [Transporter]: DBG-X:   parameter OSIdentifier = Mac OS X 10.10.5 (x86_64); jvm=24.80-b07; jre=1.7.0-internal-root_2015_01_13_21_57-b00
[17:39:47]: [Transporter]: DBG-X:   parameter Password = **hidden value**
[17:39:47]: [Transporter]: DBG-X:   parameter TransporterArguments = -m lookupMetadata -u bruce@betterup.co -p **hidden value** -apple_id 963755876 -destination /tmp
[17:39:47]: [Transporter]: DBG-X:   parameter Username = bruce@betterup.co
[17:39:47]: [Transporter]: DBG-X:   parameter Version = 1.8.5
[17:39:47]: [Transporter]: INFO: id = 20150902173947-622
[17:39:48]: [Transporter]: DBG-X: Apple's web service operation return value:
[17:39:48]: [Transporter]: DBG-X:   parameter SessionId = CKWmDBIQbXxTsyZGR2WgA+VZPeBV+Q==
[17:39:48]: [Transporter]: DBG-X:   parameter SharedSecret = b5886827-b164-4588-8d70-363b32d1b924
[17:39:48]: [Transporter]: DBG-X: Using operation named: lookupMetadataWithArguments
[17:39:48]: [Transporter]: DBG-X: Apple's web service operation input parameters:
[17:39:48]: [Transporter]: DBG-X:   parameter AppleId = 963755876
[17:39:48]: [Transporter]: DBG-X:   parameter Application = iTMSTransporter
[17:39:48]: [Transporter]: DBG-X:   parameter BaseVersion = 1.8.3
[17:39:48]: [Transporter]: DBG-X:   parameter OSIdentifier = Mac OS X 10.10.5 (x86_64); jvm=24.80-b07; jre=1.7.0-internal-root_2015_01_13_21_57-b00
[17:39:48]: [Transporter]: DBG-X:   parameter TransporterArguments = -m lookupMetadata -u bruce@betterup.co -p **hidden value** -apple_id 963755876 -destination /tmp
[17:39:48]: [Transporter]: DBG-X:   parameter Username = bruce@betterup.co
[17:39:48]: [Transporter]: DBG-X:   parameter VendorId = (null)
[17:39:48]: [Transporter]: DBG-X:   parameter Version = 1.8.5
[17:39:48]: [Transporter]: INFO: id = 20150902173948-033
[17:39:49]: [Transporter]: DBG-X: Apple's web service operation return value:
[17:39:49]: [Transporter]: DBG-X:   parameter Success = true
[17:39:49]: [Transporter]: DBG-X: Inflated 2860 bytes to 8539
[17:39:49]: [Transporter]: INFO: Creating the stub package directory ...
[17:39:49]: [Transporter]: INFO: Created the stub package directory: /tmp/963755876.itmsp
[17:39:49]: [Transporter]: INFO: Writing out the metadata file ...
[17:39:49]: [Transporter]: INFO: Finished writing out the metadata file.
[17:39:49]: iTunes Transporter successfully finished its job
[17:39:49]: [Transporter]: DBG-X: Returning 0
[17:39:49]: Successfully downloaded the latest package from iTunesConnect.
[17:39:49]: Modifying version '1.0.7' of app co.betterup.betterup
[17:39:49]: Successfully downloaded existing metadata for language en-US
Successfully created new configuration files at './metadata'
[17:39:49]: Downloading all previously used app screenshots.
[17:39:51]: Logging into iTunesConnect
[17:40:20]: ["/Users/bmctigue/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/fastlane_core-0.11.1/lib/fastlane_core/itunes_connect/itunes_connect_login.rb:41:in `login'", "/Users/bmctigue/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/fastlane_core-0.11.1/lib/fastlane_core/itunes_connect/itunes_connect.rb:62:in `initialize'", "/Users/bmctigue/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/deliver-0.13.0/lib/deliver/deliverfile/deliverfile_creator.rb:70:in `new'", "/Users/bmctigue/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/deliver-0.13.0/lib/deliver/deliverfile/deliverfile_creator.rb:70:in `create_based_on_identifier'", "/Users/bmctigue/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/deliver-0.13.0/lib/deliver/deliverfile/deliverfile_creator.rb:31:in `create'", "/Users/bmctigue/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/deliver-0.13.0/lib/deliver/commands_generator.rb:77:in `block (2 levels) in run'", "/Users/bmctigue/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'", "/Users/bmctigue/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'", "/Users/bmctigue/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/commander-4.3.4/lib/commander/command.rb:153:in `run'", "/Users/bmctigue/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/commander-4.3.4/lib/commander/runner.rb:428:in `run_active_command'", "/Users/bmctigue/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/commander-4.3.4/lib/commander/runner.rb:68:in `run!'", "/Users/bmctigue/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/commander-4.3.4/lib/commander/delegates.rb:15:in `run!'", "/Users/bmctigue/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/deliver-0.13.0/lib/deliver/commands_generator.rb:140:in `run'", "/Users/bmctigue/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/deliver-0.13.0/lib/deliver/commands_generator.rb:14:in `start'", "/Users/bmctigue/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/deliver-0.13.0/bin/deliver:5:in `<top (required)>'", "/Users/bmctigue/.rvm/gems/ruby-2.2.1/bin/deliver:23:in `load'", "/Users/bmctigue/.rvm/gems/ruby-2.2.1/bin/deliver:23:in `<main>'", "/Users/bmctigue/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'", "/Users/bmctigue/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'"]
[17:40:41]: ["/Users/bmctigue/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/fastlane_core-0.11.1/lib/fastlane_core/itunes_connect/itunes_connect_login.rb:42:in `login'", "/Users/bmctigue/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/fastlane_core-0.11.1/lib/fastlane_core/itunes_connect/itunes_connect.rb:62:in `initialize'", "/Users/bmctigue/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/deliver-0.13.0/lib/deliver/deliverfile/deliverfile_creator.rb:70:in `new'", "/Users/bmctigue/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/deliver-0.13.0/lib/deliver/deliverfile/deliverfile_creator.rb:70:in `create_based_on_identifier'", "/Users/bmctigue/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/deliver-0.13.0/lib/deliver/deliverfile/deliverfile_creator.rb:31:in `create'", "/Users/bmctigue/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/deliver-0.13.0/lib/deliver/commands_generator.rb:77:in `block (2 levels) in run'", "/Users/bmctigue/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'", "/Users/bmctigue/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'", "/Users/bmctigue/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/commander-4.3.4/lib/commander/command.rb:153:in `run'", "/Users/bmctigue/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/commander-4.3.4/lib/commander/runner.rb:428:in `run_active_command'", "/Users/bmctigue/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/commander-4.3.4/lib/commander/runner.rb:68:in `run!'", "/Users/bmctigue/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/commander-4.3.4/lib/commander/delegates.rb:15:in `run!'", "/Users/bmctigue/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/deliver-0.13.0/lib/deliver/commands_generator.rb:140:in `run'", "/Users/bmctigue/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/deliver-0.13.0/lib/deliver/commands_generator.rb:14:in `start'", "/Users/bmctigue/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/deliver-0.13.0/bin/deliver:5:in `<top (required)>'", "/Users/bmctigue/.rvm/gems/ruby-2.2.1/bin/deliver:23:in `load'", "/Users/bmctigue/.rvm/gems/ruby-2.2.1/bin/deliver:23:in `<main>'", "/Users/bmctigue/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'", "/Users/bmctigue/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'"]
[17:40:41]: Couldn't find element '.ng-scope' after waiting for quite some time
[17:40:41]: Error logging in user bruce@betterup.co with the given password. Make sure you entered them correctly.
[17:40:41]: Couldn't download already existing screenshots from iTunesConnect. You have to add them manually!
[17:40:41]: Successfully created new Deliverfile at './Deliverfile'
```
Thanks for the help.

**Comment by KrauseFx** [comment]
Sorry, this part of `fastlane` wasn't yet updated to use `spaceship`. I'm very actively working on it. 

This issue is just a time-out, have you tried running it again?

**Comment by bmctigue** [comment]
yep, it fails every time now. thanks for the reply. Anything I can do?

**Comment by sfransen** [comment]
I had this problem with codes but sudo gem update fastlane_core solved my problem
You can try that

**Comment by bmctigue** [comment]
Thx for the suggestion! I updated the core gem, but the problem persists. I appreciate the help.

**Comment by KrauseFx** [comment]
@bmctigue 

I see you're using `fastlane_core 0.11.1`. Do you have a `Gemfile`?

**Comment by KrauseFx** [comment]
Please also update `deliver`

**Comment by bmctigue** [comment]
Thanks guys, I needed to delete the Gemfile.lock and run bundle install. The gems looks correct now and I was able to run deliver init with no problems. No issue logging into itunesconnect. Thanks for the help and sorry about the false alarm.

**Comment by KrauseFx** [comment]
Great, thanks for letting me know :+1:
