### ISSUE TITLE
update_project_provisioning action says undefined method `product_type'

### ISSUE THREAD

**Issue by forhot2000** [KrauseFx/fastlane#589]
I have used [Mogenerator](https://github.com/rentzsch/mogenerator) to generate entity classes, and it added a target named Mogenerator in project, but it not have productType. So, when I use target_filter, it is failed to update project provisioning profile.

Part of my Fastfile:

```ruby
update_project_provisioning(
      xcodeproj: "Prometheus.xcodeproj",
      profile: "../PrometheusWatchkitextensionAdhoc.mobileprovision",
      target_filter: "^PrometheusWatchKitExtension$",
      build_configuration: "Release",
    )
```

Error report:

```
/Library/Ruby/Gems/2.0.0/gems/fastlane-1.25.1/lib/fastlane/actions/update_project_provisioning.rb:46:in `block in run': undefined method `product_type' for #<Xcodeproj::Project::Object::PBXAggregateTarget:0x007fd2eebe04d8> (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.25.1/lib/fastlane/actions/update_project_provisioning.rb:45:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.25.1/lib/fastlane/actions/update_project_provisioning.rb:45:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.25.1/lib/fastlane/runner.rb:142:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.25.1/lib/fastlane/actions/actions_helper.rb:37:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.25.1/lib/fastlane/runner.rb:128:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.25.1/lib/fastlane/runner.rb:127:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.25.1/lib/fastlane/runner.rb:127:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.25.1/lib/fastlane/fast_file.rb:124:in `method_missing'
```

**Comment by KrauseFx** [comment]
It is recommended to use the new solution for code signing: https://github.com/KrauseFx/fastlane/blob/master/docs/CodeSigning.md

**Comment by KrauseFx** [comment]
Could you switch to the recommended way? Or is there a reason you're using `update_project_provisioning`?

**Comment by forhot2000** [comment]
Hi, KrauseFx
I used update_project_provisioning in Travis-CI. I don't like to set my apple account in travis, it not very safe for account security, so I can't use sigh command here.

**Comment by KrauseFx** [comment]
You don't have to run `sigh`, you can just use this action:
```ruby
ENV["PROFILE_UDID"] = "abcabc..."
gym
```

instead of using `update_project_provisioning`

**Comment by forhot2000** [comment]
good, it is solved my problem, thanks @KrauseFx
