### ISSUE TITLE
undefined method `classify' for custom action

### ISSUE THREAD

**Issue by XBeg9** [KrauseFx/fastlane#59]
```ruby
module Fastlane
  module Actions
    module SharedValues
      ARCHIVE_DIR = :ARCHIVE_DIR
    end

    class ArchiveAction
      def self.run(params)
        raise "Workspace is not set".red unless ENV['WORKSPACE']
        raise "Scheme is not set".red unless ENV['SCHEME']

        Actions.sh("xcodebuild -workspace #{ENV['WORKSPACE']} -scheme #{ENV['SCHEME']} -configuration Debug -destination generic/platform=iOS archive -archivePath #{ENV['SCHEME']}.xcarchive | xcpretty -c")
        Actions.sh("xcodebuild -exportArchive -archivePath #{ENV['SCHEME']}.xcarchive -exportPath #{ENV['SCHEME']} -exportFormat ipa | xcpretty -c")

        ipa_file = "./#{ENV['SCHEME']}.ipa"

        raise "No ipa file found in #{ipa_file}".red unless File.exist?(ipa_file)

        Actions.lane_context[SharedValues::ARCHIVE_DIR] = ipa_file
      end
    end
  end
end
```

After update to latest fasten, I got this:
```
lib/fastlane/actions/actions_helper.rb:93:in `block in load_external_actions': undefined method `classify' for "archive":String (NoMethodError)
```

**Comment by KrauseFx** [comment]
Could you run `sudo gem update fastlane_core` and see if that fixes the problem?

**Comment by XBeg9** [comment]
@KrauseFx 
```
sudo gem update fastlane_core
Updating installed gems
Nothing to update
```
current version is fastlane-0.1.9

**Comment by KrauseFx** [comment]
I just copied your action and it's working fine. Could you post the full stack trace?

**Comment by XBeg9** [comment]
@KrauseFx 
Sure,
```
/Users/skitsko/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/fastlane-0.1.9/lib/fastlane/actions/actions_helper.rb:93:in `block in load_external_actions': undefined method `classify' for "archive":String (NoMethodError)
	from /Users/skitsko/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/fastlane-0.1.9/lib/fastlane/actions/actions_helper.rb:88:in `each'
	from /Users/skitsko/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/fastlane-0.1.9/lib/fastlane/actions/actions_helper.rb:88:in `load_external_actions'
	from /Users/skitsko/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/fastlane-0.1.9/lib/fastlane.rb:26:in `<module:Fastlane>'
	from /Users/skitsko/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/fastlane-0.1.9/lib/fastlane.rb:17:in `<top (required)>'
	from /Users/skitsko/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/fastlane-0.1.9/bin/fastlane:5:in `require'
	from /Users/skitsko/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/fastlane-0.1.9/bin/fastlane:5:in `<top (required)>'
	from /Users/skitsko/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bin/fastlane:23:in `load'
	from /Users/skitsko/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bin/fastlane:23:in `<main>'
```

**Comment by KrauseFx** [comment]
Great, that helped. I pushed a fix. Please install it using `sudo bundle install && sudo rake install` and let me know if that fixes your problem :+1: 

Also, would you like to submit your action as official `fastlane` action?

**Comment by XBeg9** [comment]
@KrauseFx yes, thanks for fast fix. I like xcpretty more than xctool, so yes, we can publish it. But first I think we need to polish it a bit.

**Comment by KrauseFx** [comment]
Just published a release: https://github.com/KrauseFx/fastlane/releases

That sounds interesting. If you don't mind sharing them, I'd be happy to include them in `fastlane`.
