### ISSUE TITLE
Error after upgrading to fastlane 

### ISSUE THREAD

**Issue by hufkens** [KrauseFx/fastlane#606]
After upgrading I get this error and can't submit Test Flight and Crashlytics builds.

```
[10:39:27]: fastlane finished with errors
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1551:in `block in fu_each_src_dest': same file: /tmp/1442651948/MyIpa.ipa and /tmp/1442651948/MyIpa.ipa (ArgumentError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1568:in `fu_each_src_dest0'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1550:in `fu_each_src_dest'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:508:in `mv'
	from /Library/Ruby/Gems/2.0.0/gems/gym-0.6.2/lib/gym/generators/package_command_generator_xcode7.rb:44:in `ipa_path'
	from /Library/Ruby/Gems/2.0.0/gems/gym-0.6.2/lib/gym/generators/package_command_generator.rb:20:in `ipa_path'
	from /Library/Ruby/Gems/2.0.0/gems/gym-0.6.2/lib/gym/runner.rb:128:in `move_ipa'
	from /Library/Ruby/Gems/2.0.0/gems/gym-0.6.2/lib/gym/runner.rb:19:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/gym-0.6.2/lib/gym/manager.rb:8:in `work'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.27.0/lib/fastlane/actions/gym.rb:20:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.27.0/lib/fastlane/runner.rb:142:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.27.0/lib/fastlane/actions/actions_helper.rb:37:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.27.0/lib/fastlane/runner.rb:128:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.27.0/lib/fastlane/runner.rb:127:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.27.0/lib/fastlane/runner.rb:127:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.27.0/lib/fastlane/fast_file.rb:134:in `method_missing'
	from (eval):73:in `block (3 levels) in parse'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.27.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.27.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.27.0/lib/fastlane/runner.rb:51:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.27.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.27.0/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.27.0/lib/fastlane/lane_manager.rb:43:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.27.0/lib/fastlane/command_line_handler.rb:31:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.27.0/bin/fastlane:36:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.27.0/bin/fastlane:127:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.27.0/bin/fastlane:133:in `<top (required)>'
	from /usr/bin/fastlane:23:in `load'
	from /usr/bin/fastlane:23:in `<main>'
```

**Comment by DigitalRogues** [comment]
I'm seeing this error also, with version 1.27.0 and I have multiple targets, ios app with a watchOS 2 app/extension.

**Comment by KrauseFx** [comment]
I just pushed a fix, please update and let me know if that works for you :rocket: https://github.com/fastlane/gym/releases/tag/0.7.0

**Comment by hufkens** [comment]
Yes, it's working again. Thanks

**Comment by DigitalRogues** [comment]
working for me also, thanks a bunch @KrauseFx !

**Comment by KrauseFx** [comment]
Yeah, great to hear :rocket:
