### ISSUE TITLE
gym randomly works

### ISSUE THREAD

**Issue by omartin** [KrauseFx/fastlane#646]
Hi there,

Very strange issue, when I launch the command gym it **sometimes** work, like for instance :

### first fail
```
[~/dev/mdf-develop] gym
/Library/Ruby/Gems/2.0.0/gems/gym-0.8.3/lib/gym/detect_values.rb:16:in `set_additional_default_values': No project/workspace found in the current directory. (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/gym-0.8.3/lib/gym.rb:26:in `config='
	from /Library/Ruby/Gems/2.0.0/gems/gym-0.8.3/lib/gym/manager.rb:4:in `work'
	from /Library/Ruby/Gems/2.0.0/gems/gym-0.8.3/lib/gym/commands_generator.rb:41:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/gym-0.8.3/lib/gym/commands_generator.rb:58:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/gym-0.8.3/lib/gym/commands_generator.rb:14:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/gym-0.8.3/bin/gym:6:in `<top (required)>'
	from /usr/bin/gym:23:in `load'
	from /usr/bin/gym:23:in `<main>'
```

### Second fail
```
[~/dev/mdf-develop] gym
/Library/Ruby/Gems/2.0.0/gems/gym-0.8.3/lib/gym/detect_values.rb:16:in `set_additional_default_values': No project/workspace found in the current directory. (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/gym-0.8.3/lib/gym.rb:26:in `config='
	from /Library/Ruby/Gems/2.0.0/gems/gym-0.8.3/lib/gym/manager.rb:4:in `work'
	from /Library/Ruby/Gems/2.0.0/gems/gym-0.8.3/lib/gym/commands_generator.rb:41:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/gym-0.8.3/lib/gym/commands_generator.rb:58:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/gym-0.8.3/lib/gym/commands_generator.rb:14:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/gym-0.8.3/bin/gym:6:in `<top (required)>'
	from /usr/bin/gym:23:in `load'
	from /usr/bin/gym:23:in `<main>'
```

### This time it works, I changed nothing
```
[~/dev/mdf-develop] gym
[16:35:01]: Installing provisioning profile...
[16:35:01]: xcrun xcodebuild -list -project './MDF.xcodeproj'
[16:35:02]: xcrun xcodebuild -showBuildSettings -scheme 'MDF' -project './MDF.xcodeproj'
```

Sys info :
gym 0.8.3
fastlane 1.30.1
ruby 2.0.0p481

**Comment by KrauseFx** [comment]
I'm really sorry about this. Your issue seems to be caused by a release yesterday which had a race condition in [fastlane_core](https://github.com/fastlane/fastlane_core). Could you please update using `sudo gem update fastlane_core` and let me know if this fixes your issue? 

Sorry again for the troubles.

**Comment by DigitalRogues** [comment]
I just wanted to report, I had this issue also and updating fastlane-core seems to have fixed the issue, thanks!

**Comment by omartin** [comment]
Yes that fixed it thanks!
