### ISSUE TITLE
fastlane fails when doing sigh action

### ISSUE THREAD

**Issue by davidattias** [KrauseFx/fastlane#648]
I am unable to finish my Fastlane lane as it exits with error while starting a sigh action:

```
[11:46:25]: fastlane finished with errors
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.10.2/lib/spaceship/client.rb:244:in `parse_response': {"creationTimestamp"=>"2015-10-01T09:46:24Z", "resultCode"=>0, "userLocale"=>"en_US", "protocolVersion"=>"QH65B2", "requestId"=>nil, "requestUrl"=>"https://developer.apple.com:443//services-account/QH65B2/account/listTeams.action", "responseId"=>"248f52ed-c370-44e7-85d8-19f7be7755d8", "isAdmin"=>nil, "isMember"=>nil, "isAgent"=>nil, "pageNumber"=>nil, "pageSize"=>nil, "totalRecords"=>nil, "httpResponseHeaders"=>nil} (Spaceship::Client::UnexpectedResponse)
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.10.2/lib/spaceship/portal/portal_client.rb:52:in `teams'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.10.2/lib/spaceship/portal/ui/select_team.rb:35:in `select_team'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.10.2/lib/spaceship/portal/portal_client.rb:68:in `select_team'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.10.2/lib/spaceship/portal/spaceship.rb:37:in `select_team'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.10.2/lib/spaceship/portal/spaceship.rb:81:in `select_team'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-0.10.8/lib/sigh/runner.rb:12:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-0.10.8/lib/sigh/manager.rb:7:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/lib/fastlane/actions/sigh.rb:22:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/lib/fastlane/runner.rb:142:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/lib/fastlane/actions/actions_helper.rb:37:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/lib/fastlane/runner.rb:128:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/lib/fastlane/runner.rb:127:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/lib/fastlane/runner.rb:127:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/lib/fastlane/fast_file.rb:137:in `method_missing'
	from (eval):37:in `block (3 levels) in parse'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/lib/fastlane/runner.rb:109:in `try_switch_to_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/lib/fastlane/fast_file.rb:129:in `rescue in method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/lib/fastlane/fast_file.rb:124:in `method_missing'
	from (eval):63:in `block (3 levels) in parse'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/lib/fastlane/runner.rb:51:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/lib/fastlane/lane_manager.rb:43:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/lib/fastlane/command_line_handler.rb:31:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/bin/fastlane:36:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/bin/fastlane:127:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/bin/fastlane:133:in `<top (required)>'
	from /usr/bin/fastlane:23:in `load'
	from /usr/bin/fastlane:23:in `<main>'
```

**Comment by davidattias** [comment]
Find out the account I configured had an iTunesConnect account but NOT a Developer Program account.

**Comment by KrauseFx** [comment]
:+1:
