### ISSUE TITLE
gym fails with error: You can only pass either a workspace or a project path, not both

### ISSUE THREAD

**Issue by toshi0383** [KrauseFx/fastlane#659]
If you have `App.xcworkspace/` directory in your workspace, gym fails with error like below.

```
[11:20:59]: fastlane finished with errors
/Library/Ruby/Gems/2.0.0/gems/gym-0.8.4/lib/gym/detect_values.rb:12:in `set_additional_default_values': You can only pass either a workspace or a project path, not both (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/gym-0.8.4/lib/gym.rb:26:in `config='
	from /Library/Ruby/Gems/2.0.0/gems/gym-0.8.4/lib/gym/manager.rb:4:in `work'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/lib/fastlane/actions/gym.rb:22:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/lib/fastlane/runner.rb:142:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/lib/fastlane/actions/actions_helper.rb:37:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/lib/fastlane/runner.rb:128:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/lib/fastlane/runner.rb:127:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/lib/fastlane/runner.rb:127:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/lib/fastlane/fast_file.rb:137:in `method_missing'
	from (eval):61:in `inhouse'
	from (eval):136:in `block (3 levels) in parse'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/lib/fastlane/runner.rb:51:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/lib/fastlane/lane_manager.rb:43:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/lib/fastlane/command_line_handler.rb:31:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/bin/fastlane:36:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/bin/fastlane:127:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/bin/fastlane:133:in `<top (required)>'
	from /usr/bin/fastlane:23:in `load'
	from /usr/bin/fastlane:23:in `<main>'
```

Fastfile
```
platform :ios do
  lane :beta do |options|
    gym(
      scheme:  "Xcode6ScreenRect",
      output_name: "Xcode6ScreenRect.ipa",
      silent:  false,
      xcconfig: "Xcode6ScreenRect/Config.xcconfig",
      clean:   true,
    )
  end
end
```

Project Tree
```
Xcode6ScreenRect $ tree
.
├── Xcode6ScreenRect
│   ├── AppDelegate.swift
│   ├── Base.lproj
│   │   ├── LaunchScreen.xib
│   │   └── Main.storyboard
│   ├── Config.xcconfig
│   ├── Images.xcassets
│   │   └── AppIcon.appiconset
│   │       └── Contents.json
│   ├── Info.plist
│   ├── UIView+ViewFrame.swift
│   └── ViewController.swift
├── Xcode6ScreenRect.xcodeproj
│   ├── project.pbxproj
│   ├── project.xcworkspace
│   │   ├── contents.xcworkspacedata
│   │   └── xcuserdata
│   │       └── toshi0383.xcuserdatad
│   │           └── UserInterfaceState.xcuserstate
│   ├── xcshareddata
│   │   └── xcschemes
│   │       └── Xcode6ScreenRect.xcscheme
│   └── xcuserdata
│       └── toshi0383.xcuserdatad
│           ├── xcdebugger
│           │   └── Breakpoints_v2.xcbkptlist
│           └── xcschemes
│               └── xcschememanagement.plist
├── Xcode6ScreenRect.xcworkspace
├── Xcode6ScreenRectTests
│   ├── Info.plist
│   └── Xcode6ScreenRectTests.swift
└── fastlane
    ├── Fastfile
    └── report.xml

17 directories, 18 files

```

**Comment by toshi0383** [comment]
fastlane 1.30.2

**Comment by toshi0383** [comment]
here is my .env file.

```
Xcode6ScreenRect $ cat fastlane/.env
GYM_PROJECT=Xcode6ScreenRect.xcodeproj
GYM_BUILDLOG_PATH=./gym.log
GYM_INCLUDE_SYMBOLS=true
GYM_INCLUDE_BITCODE=false
GYM_USE_LEGACY_BUILD_API=true

```

**Comment by KrauseFx** [comment]
That makes sense and really is a bug, thanks for reporting, I'll see what I can do.

**Comment by KrauseFx** [comment]
Please update `gym` and let me know if that works for you

**Comment by toshi0383** [comment]
It works fine in 1.32.0 👍 Thanks for quick fix 😀

**Comment by KrauseFx** [comment]
:rocket:
