### ISSUE TITLE
verify_xcode error

### ISSUE THREAD

**Issue by pzbyszynski** [KrauseFx/fastlane#661]
Hi,

verify_xcode action rises following error:

```
/Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/lib/fastlane/actions/verify_xcode.rb:56:in `verify': undefined method `show_and_raise_error' for Fastlane::Actions::VerifyXcodeAction:Class (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/lib/fastlane/actions/verify_xcode.rb:23:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/lib/fastlane/runner.rb:142:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/lib/fastlane/actions/actions_helper.rb:37:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/lib/fastlane/runner.rb:128:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/lib/fastlane/runner.rb:127:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/lib/fastlane/runner.rb:127:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/lib/fastlane/fast_file.rb:137:in `method_missing'
	from (eval):35:in `block (3 levels) in parse'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/lib/fastlane/runner.rb:51:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/lib/fastlane/lane_manager.rb:43:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/lib/fastlane/command_line_handler.rb:31:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/bin/fastlane:36:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/bin/fastlane:127:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/bin/fastlane:133:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

**Comment by KrauseFx** [comment]
Nice catch, thanks. I'm fixing it right now and push a new release.

**Comment by pzbyszynski** [comment]
Great, and thanks for your work!

**Comment by KrauseFx** [comment]
Please update to https://github.com/KrauseFx/fastlane/releases/tag/1.31.0 and let me know if that works. It looks like you got an issue with your Xcode installation though

**Comment by pzbyszynski** [comment]
Everything seems to be fine now, thx for your help ;)

**Comment by KrauseFx** [comment]
Did you get an error? Is your Xcode installation valid?

**Comment by pzbyszynski** [comment]
I did get an error message that my Xcode installation may be corrupted (it was Xcode version installed from ADC). I have downloaded and installed clean version from MAS and then validation passed without any errors.

**Comment by samdmarshall** [comment]
I am seeing this as well, Xcode 7.0.1 from ADC using fastlane 1.32.1. running spctl and codesign independently will both pass successfully.

**Comment by KrauseFx** [comment]
@samdmarshall Could you share the output when running 

```
codesign --display --verbose=4 'your path here'
```

```
/usr/sbin/spctl --assess --verbose  'your path here'
```

**Comment by samdmarshall** [comment]
```
$ xcodebuild -version
Xcode 7.0.1
Build version 7A1001
```

```
$ spctl --assess /Applications/Xcode.app/ --verbose
/Applications/Xcode.app/: accepted
source=Apple System
```

```
$ codesign --display --verbose=4 '/Applications/Xcode.app'
Executable=/Applications/Xcode.app/Contents/MacOS/Xcode
Identifier=com.apple.dt.Xcode
Format=bundle with Mach-O thin (x86_64)
CodeDirectory v=20100 size=307 flags=0x0(none) hashes=7+5 location=embedded
Hash type=sha1 size=20
CDHash=8d9f4a4d5ef2d4508ea1024e85c03ab4abb41e64
Signature size=4105
Authority=Software Signing
Authority=Apple Code Signing Certification Authority
Authority=Apple Root CA
Info.plist entries=34
TeamIdentifier=not set
Sealed Resources version=2 rules=12 files=306123
Internal requirements count=1 size=68
```

**Comment by KrauseFx** [comment]
These are the values the `verify_xcode` action looks for:

```ruby
        must_includes = [
          "Identifier=com.apple.dt.Xcode",
          "Authority=Apple Mac OS Application Signing",
          "Authority=Apple Worldwide Developer Relations Certification Authority",
          "Authority=Apple Root CA",
          "TeamIdentifier=59GAB85EFG"
        ]
```

It looks like yours is signed differently. I'll take a closer look and update the `verify_xcode` action

**Comment by GabrielCartier** [comment]
Not sure if it is related to that problem, if not, feel free to let me know and I'll make another PR. Anyway, I installed the new xcode on our build machine (jenkins) and here's the verify_xcode output:

```
Executable=/Applications/Xcode-7.1.app/Contents/MacOS/Xcode
Identifier=com.apple.dt.Xcode
Format=bundle with Mach-O thin (x86_64)
CodeDirectory v=20100 size=307 flags=0x0(none) hashes=7+5 location=embedded
Hash type=sha1 size=20
CDHash=f5f515a9261f02532df8fec0b0ac273d13ca96e8
Signature size=4105
Authority=Software Signing
Authority=Apple Code Signing Certification Authority
Authority=Apple Root CA
Info.plist entries=34
TeamIdentifier=not set
Sealed Resources version=2 rules=12 files=378646
Internal requirements count=1 size=68
Attention: Your Xcode Installation might be hacked.[0m
This might be a false alarm, if so, please submit an issue on GitHub[0m
The following information couldn't be found:[0m
Authority=Apple Mac OS Application Signing
Authority=Apple Worldwide Developer Relations Certification Authority
TeamIdentifier=59GAB85EFG
```
