### ISSUE TITLE
Can't always run fastlane actions without a lane

### ISSUE THREAD

**Issue by akofman** [KrauseFx/fastlane#669]
This is the first time I'm using Fastlane so maybe I'm doing something wrong.
Just tried this new feature : 
```
$ fastlane run say "cool"
```
but got this error  : 

```
/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.31.0/lib/fastlane/actions/say.rb:5:in `run': undefined method `join' for #<FastlaneCore::Configuration:0x007fcaa91a7540> (NoMethodError)
	from /Users/kushi/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.31.0/lib/fastlane/runner.rb:142:in `block (2 levels) in execute_action'
	from /Users/kushi/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.31.0/lib/fastlane/actions/actions_helper.rb:37:in `execute_action'
	from /Users/kushi/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.31.0/lib/fastlane/runner.rb:128:in `block in execute_action'
	from /Users/kushi/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.31.0/lib/fastlane/runner.rb:127:in `chdir'
	from /Users/kushi/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.31.0/lib/fastlane/runner.rb:127:in `execute_action'
	from /Users/kushi/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.31.0/lib/fastlane/one_off.rb:31:in `execute'
	from /Users/kushi/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.31.0/bin/fastlane:109:in `block (2 levels) in run'
	from /Users/kushi/.rvm/gems/ruby-2.2.1@global/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/kushi/.rvm/gems/ruby-2.2.1@global/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/kushi/.rvm/gems/ruby-2.2.1@global/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/kushi/.rvm/gems/ruby-2.2.1@global/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/kushi/.rvm/gems/ruby-2.2.1@global/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Users/kushi/.rvm/gems/ruby-2.2.1@global/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/kushi/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.31.0/bin/fastlane:136:in `run'
	from /Users/kushi/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.31.0/bin/fastlane:142:in `<top (required)>'
	from /Users/kushi/.rvm/rubies/ruby-2.2.1/bin/fastlane:23:in `load'
	from /Users/kushi/.rvm/rubies/ruby-2.2.1/bin/fastlane:23:in `<main>'
	from /Users/kushi/.rvm/gems/ruby-2.2.1@global/bin/ruby_executable_hooks:15:in `eval'
	from /Users/kushi/.rvm/gems/ruby-2.2.1@global/bin/ruby_executable_hooks:15:in `<main>'
```

Also I tried 

````
$fastlane run get_version_number xcodeproj:"pathto.xcodeproj"
```

and got 

````
[21:28:21]: You passed invalid parameters to 'get_version_number'.
```

Otherwise,
```
fastlane run update_fastlane
```
Works well :+1:

**Comment by KrauseFx** [comment]
Thanks for submitting this issue. The error messages a very unclear, you're right. I'll improve this, I'll update the issue in a few minutes.

**Comment by KrauseFx** [comment]
```
 ~  Developer  fastlane  fastlane  feature/enhancements  3  $  ./bin/fastlane run get_version_number xcodeproj:"pathto.xcodeproj"
[15:53:03]: Using xcodeproj: pathto.xcodeproj
[15:53:03]: --------------------------------
[15:53:03]: --- Step: get_version_number ---
[15:53:03]: --------------------------------
[15:53:03]: Error setting value 'pathto.xcodeproj' for option 'xcodeproj'
[15:53:03]: You passed invalid parameters to 'get_version_number'.
[15:53:03]: Check out the error below and available options by running `fastlane action get_version_number`
/Users/fkrause/Developer/fastlane/fastlane/lib/fastlane/actions/get_version_number.rb:63:in `block in available_options': Could not find Xcode project (RuntimeError)
```
This looks like a clear error message, the xcode project can't be found.

**Comment by KrauseFx** [comment]
`say` doesn't work, you're right, I'll add a proper warning. Besides that, most other actions should work. Please let me know if you find something else.

**Comment by akofman** [comment]
Thx ! 
Actually even if my path to xcodeproj seems to be good I have this error msg :(

```
[22:02:46]: Using xcodeproj: pathto.xcodeproj
[22:02:46]: --------------------------------
[22:02:46]: --- Step: get_version_number ---
[22:02:46]: --------------------------------
[22:02:46]: Error setting value 'pathto.xcodeproj' for option 'xcodeproj'
[22:02:46]: You passed invalid parameters to 'get_version_number'.
[22:02:46]: Check out the error below and available options by running `fastlane action get_version_number`
$/fastlane-1.31.0/lib/fastlane/actions/get_version_number.rb:63:in `block in available_options': Could not find Xcode project (RuntimeError)
```

It looks like it can"t find Xcode project because of this invalid parameter error.

**Comment by KrauseFx** [comment]
Interesting, maybe it's running in the wrong folder context...

**Comment by KrauseFx** [comment]
Yes, that's it, I'll push a fix :+1:

**Comment by KrauseFx** [comment]
Please update to the latest version, this should work now :+1:

**Comment by akofman** [comment]
I just test another custom action, sorry I'm not used to dev with ruby so I inspired by your other actions: 

```
module Fastlane
  module Actions
    class GitLastCommitHashAction < Action
      def self.run(params)
        command = [
          'git',
          'rev-parse',
          'HEAD'
        ]

        value = Actions.sh(command.join(' '))
        Helper.log.info 'Retrieve the hash for the current commit.'

        return value
      end

      def self.description
        "Executes git rev-parse HEAD"
      end

      def self.available_options
        [
        ]
      end

      def self.author
        "Alexis Kofman"
      end

      def self.is_supported?(platform)
        true
      end
    end
  end
end
```

Also If I fastlane run it, it doesn't recognize my project as a git repository. It looks like the same issue with the bad context ?

**Comment by akofman** [comment]
Ok I didn't see your previous messagge ! I'll test right now :)

**Comment by akofman** [comment]
````
$fastlane -v
fastlane 1.32.0
```
```
fastlane run git_last_commit_hash
[00:00:54]: Successfully loaded custom action '/fastlane/actions/git_last_commit_hash.rb'.
[00:00:54]: ----------------------------------
[00:00:54]: --- Step: git_last_commit_hash ---
[00:00:54]: ----------------------------------
[00:00:54]: [SHELL COMMAND]: git rev-parse HEAD
[00:00:54]: [SHELL]: 740733e0696112d56284b23a5bf4278282b340aa
[00:00:54]: Retrieve the hash of the last commit.
```

:+1: Thanks :)

**Comment by KrauseFx** [comment]
Cool. What do you plan on using it for? :+1:

**Comment by akofman** [comment]
Actually I'm used to build Adhoc ipa with the hash of the last commit in its name.
It happens that I have to deliver several Adhoc bundles in the same day and this info can be useful sometimes. 

So now I'm using  gym with the good output name :)

**Comment by akofman** [comment]
And the One-Off feature is just a convenient way to test it.
