### ISSUE TITLE
Creation of apps of this type is not available

### ISSUE THREAD

**Issue by jacao** [KrauseFx/fastlane#674]
Getting the following issue during produce. Produce works when using one itunes connect account, but a different itunes connect account I get the following issue 'Creation of apps of this type is not available'.

Not sure if this is some sort of configuration issue for the itunes connect account

````
[37m[15:36:40]: [0m{:PLATFORM_NAME=>nil, :LANE_NAME=>"deploy", :BUILD_NUMBER=>"There does not seem to be a CURRENT_PROJECT_VERSION key set for this project.  Add this key to your target's expert build settings."}
[1m[31m[15:36:40]: [0m[0m{"data"=>nil, "messages"=>{"warn"=>nil, "info"=>nil, "error"=>["Creation of apps of this type is not available"]}, "statusCode"=>"ERROR"}

+------+-------------------------------------+-------------+
|                     [32mfastlane summary[0m                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | increment_build_number              | 0           |
| 3    | produce                             | 14          |
+------+-------------------------------------+-------------+

[1m[31m[15:36:40]: [0m[0m[31mfastlane finished with errors[0m
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.11.2/lib/spaceship/client.rb:244:in `parse_response': {"data"=>nil, "messages"=>{"warn"=>nil, "info"=>nil, "error"=>["Creation of apps of this type is not available"]}, "statusCode"=>"ERROR"} (Spaceship::Client::UnexpectedResponse)
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.11.2/lib/spaceship/tunes/tunes_client.rb:197:in `create_application!'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.11.2/lib/spaceship/tunes/application.rb:86:in `create!'
	from /Library/Ruby/Gems/2.0.0/gems/produce-0.6.5/lib/produce/itunes_connect.rb:24:in `create_new_app'
	from /Library/Ruby/Gems/2.0.0/gems/produce-0.6.5/lib/produce/itunes_connect.rb:11:in `run'
````

**Comment by jacao** [comment]
Had to agree new terms and conditions in the itunes connect account, my bad.

**Comment by KrauseFx** [comment]
:+1:

**Comment by ssteinerx** [comment]
I'm having the same issue, but there are no new terms or conditions.  First time trying fastlane, existing dev account on which we have published apps (MacOS only).

**Comment by TKBurner** [comment]
Hi @ssteinerx! Thanks for reaching out. Really glad you are trying out Fastlane. Can you go to https://appleid.apple.com/ and sign in and then try again? Sometimes this fixes issues with Spaceship. 

Thanks!
