### ISSUE TITLE
Failed to setup snapshot

### ISSUE THREAD

**Issue by bjornoss** [KrauseFx/fastlane#724]
Hi. Just tried to use fastlane for the first time today. 
During `fastlane init` the setup failed to setup snapshot.
I had to change two lines in the setup_ios.rb file: 

    require 'snapshot/setup'
    Snapshot::Setup.create(folder)

ErrorLog
```
[12:49:37]: Error occurred with the setup program! Reverting changes now!
[12:49:37]: Deleting the 'fastlane' folder
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:121:in `require': cannot load such file -- snapshot/snapfile_creator (LoadError)
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:121:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.34.0/lib/fastlane/setup/setup_ios.rb:108:in `ask_to_enable_other_tools'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.34.0/lib/fastlane/setup/setup_ios.rb:24:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.34.0/lib/fastlane/setup/setup.rb:19:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.34.0/bin/fastlane:48:in `block (2 levels) in run'
```

**Comment by KrauseFx** [comment]
Wow, nice catch, thanks! :+1:
