### ISSUE TITLE
Fastlane init failed on Snapshot Setup

### ISSUE THREAD

**Issue by DouglasHennrich** [KrauseFx/fastlane#728]
~~~
[21:19:35]: Loading up 'snapshot', this might take a few seconds
[21:19:36]: Error occurred with the setup program! Reverting changes now!
[21:19:36]: Moving './fastlane/Deliverfile' to 'Deliverfile'
[21:19:36]: Moving './fastlane/screenshots' to 'screenshots'
[21:19:36]: Deleting the 'fastlane' folder
/usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require': cannot load such file -- snapshot/snapfile_creator (LoadError)
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from /Users/DHennrich/.gems/gems/fastlane-1.34.0/lib/fastlane/setup/setup_ios.rb:108:in `ask_to_enable_other_tools'
	from /Users/DHennrich/.gems/gems/fastlane-1.34.0/lib/fastlane/setup/setup_ios.rb:24:in `run'
	from /Users/DHennrich/.gems/gems/fastlane-1.34.0/lib/fastlane/setup/setup.rb:19:in `run'
	from /Users/DHennrich/.gems/gems/fastlane-1.34.0/bin/fastlane:48:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/DHennrich/.gems/gems/fastlane-1.34.0/bin/fastlane:152:in `run'
	from /Users/DHennrich/.gems/gems/fastlane-1.34.0/bin/fastlane:158:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
~~~

**Comment by KrauseFx** [comment]
Sorry about this, it should be fixed in the latest release :+1: Let me know if that works for you
