### ISSUE TITLE
Extension Support

### ISSUE THREAD

**Issue by bassrock** [KrauseFx/fastlane#76]
I finally got to getting fasten setup for my Xcode project properly. However when I have the following lane defined: 

```
lane :beta do  
   cert
   sigh :force
   ipa({
  		workspace: "DemoApp.xcworkspace",
  		configuration: "Release",
  		scheme: "DemoApp",
	})
  deliver :skip_deploy, :force  #skip_deploy => don't submit the app for review (works with both App Store and beta builds)
end
```

Sigh does not download and install the provisioning profiles for my Today View Extension. I had to manually set up the provisioning profile for it and then it would build with fastlane on my local machine.

Is this expected behavior and is it possible to have fastlane make sigh download the provisioning profiles for an app extension?

**Comment by bassrock** [comment]
Correction to the above: It does not work after getting the provisioning profile manually.

I am getting an error with the validate step of the build process:

```
The following build commands failed:
INFO [2015-02-23 23:33:32.26]: [SHELL OUTPUT]: ValidateEmbeddedBinary /Users/daniel/Library/Developer/Xcode/DerivedData/Demo-hjdhmoxqwxxmxtguevgikvldevvj/Build/Products/Release-iphoneos/Demo.app/PlugIns/DemoTodayExtension.appex
```

```
from /Users/daniel/Documents/Work/DemoApp/vendor/bundle/ruby/2.2.0/gems/fastlane-0.1.12/lib/fastlane/actions/actions_helper.rb:49:in `sh'
	from /Users/daniel/Documents/Work/DemoApp/vendor/bundle/ruby/2.2.0/gems/fastlane-0.1.12/lib/fastlane/actions/ipa.rb:73:in `run'
	from /Users/daniel/Documents/Work/DemoApp/vendor/bundle/ruby/2.2.0/gems/fastlane-0.1.12/lib/fastlane/fast_file.rb:80:in `block (2 levels) in method_missing'
	from /Users/daniel/Documents/Work/DemoApp/vendor/bundle/ruby/2.2.0/gems/fastlane-0.1.12/lib/fastlane/actions/actions_helper.rb:28:in `execute_action'
	from /Users/daniel/Documents/Work/DemoApp/vendor/bundle/ruby/2.2.0/gems/fastlane-0.1.12/lib/fastlane/fast_file.rb:79:in `block in method_missing'
	from /Users/daniel/Documents/Work/DemoApp/vendor/bundle/ruby/2.2.0/gems/fastlane-0.1.12/lib/fastlane/fast_file.rb:78:in `chdir'
	from /Users/daniel/Documents/Work/DemoApp/vendor/bundle/ruby/2.2.0/gems/fastlane-0.1.12/lib/fastlane/fast_file.rb:78:in `method_missing'
	from (eval):38:in `block (2 levels) in parse'
	from /Users/daniel/Documents/Work/DemoApp/vendor/bundle/ruby/2.2.0/gems/fastlane-0.1.12/lib/fastlane/runner.rb:16:in `call'
	from /Users/daniel/Documents/Work/DemoApp/vendor/bundle/ruby/2.2.0/gems/fastlane-0.1.12/lib/fastlane/runner.rb:16:in `block in execute'
	from /Users/daniel/Documents/Work/DemoApp/vendor/bundle/ruby/2.2.0/gems/fastlane-0.1.12/lib/fastlane/runner.rb:10:in `chdir'
	from /Users/daniel/Documents/Work/DemoApp/vendor/bundle/ruby/2.2.0/gems/fastlane-0.1.12/lib/fastlane/runner.rb:10:in `execute'
	from /Users/daniel/Documents/Work/DemoApp/vendor/bundle/ruby/2.2.0/gems/fastlane-0.1.12/lib/fastlane/lane_manager.rb:15:in `block in cruise_lanes'
	from /Users/daniel/Documents/Work/DemoApp/vendor/bundle/ruby/2.2.0/gems/fastlane-0.1.12/lib/fastlane/lane_manager.rb:14:in `each'
	from /Users/daniel/Documents/Work/DemoApp/vendor/bundle/ruby/2.2.0/gems/fastlane-0.1.12/lib/fastlane/lane_manager.rb:14:in `cruise_lanes'
	from /Users/daniel/Documents/Work/DemoApp/vendor/bundle/ruby/2.2.0/gems/fastlane-0.1.12/bin/fastlane:30:in `block (2 levels) in run'
	from /Users/daniel/Documents/Work/DemoApp/vendor/bundle/ruby/2.2.0/gems/commander-4.3.0/lib/commander/command.rb:179:in `call'
	from /Users/daniel/Documents/Work/DemoApp/vendor/bundle/ruby/2.2.0/gems/commander-4.3.0/lib/commander/command.rb:179:in `call'
	from /Users/daniel/Documents/Work/DemoApp/vendor/bundle/ruby/2.2.0/gems/commander-4.3.0/lib/commander/command.rb:154:in `run'
	from /Users/daniel/Documents/Work/DemoApp/vendor/bundle/ruby/2.2.0/gems/commander-4.3.0/lib/commander/runner.rb:421:in `run_active_command'
	from /Users/daniel/Documents/Work/DemoApp/vendor/bundle/ruby/2.2.0/gems/commander-4.3.0/lib/commander/runner.rb:81:in `run!'
	from /Users/daniel/Documents/Work/DemoApp/vendor/bundle/ruby/2.2.0/gems/commander-4.3.0/lib/commander/delegates.rb:15:in `run!'
	from /Users/daniel/Documents/Work/DemoApp/vendor/bundle/ruby/2.2.0/gems/fastlane-0.1.12/bin/fastlane:58:in `run'
	from /Users/daniel/Documents/Work/DemoApp/vendor/bundle/ruby/2.2.0/gems/fastlane-0.1.12/bin/fastlane:62:in `<top (required)>'
	from /Users/daniel/Documents/Work/DemoApp/vendor/bundle/ruby/2.2.0/bin/fastlane:23:in `load'
	from /Users/daniel/Documents/Work/DemoApp/vendor/bundle/ruby/2.2.0/bin/fastlane:23:in `<main>'
```

**Comment by bassrock** [comment]
Ok weird. something was resetting the CodeSign Identity of the extension and now it has stopped and builds. 

Also got the provision profile for the extension installed by:

```
sh "bundle exec sigh -a com.demo.app.TodayExtension -u test@test.com"
```

Still a way without sh to sigh would be cool! Great job on the tools!

**Comment by KrauseFx** [comment]
Why do you need to run `sh` for the last posted code snippet?

If it's just because you want a different app identifier, use:

```ruby
ENV["SIGH_APP_IDENTIFIER"] = "com.demo.app.TodayExtension"
sigh
ENV["SIGH_APP_IDENTIFIER"] = "your real identifier"
```

Does that help?

**Comment by bassrock** [comment]
Ah did not realize I could do it like that. Thanks!

**Comment by pronebird** [comment]
So how do you code sign both app and extension at the same time?

**Comment by TKBurner** [comment]
Hi @pronebird You are going to need to run sigh twice, once for each target.
