### ISSUE TITLE
Dependency issues when calling produce and sigh in a loop.

### ISSUE THREAD

**Issue by jhuggart** [KrauseFx/fastlane#91]
First, the issue:

I have an array of clients. Each have different assets, bundle id, and app name. The lane that I'm working in looks like this:

```
@clients.each do |client|

    configure client #copies assets

    ipa({configuration: "Release"})

    produce({
      produce_app_identifier: client[:bundle_id], 
      produce_app_name: client[:app_name],
      produce_language: 'English',
      produce_version: '1.0'
    })

    sigh

    deliver :skip_deploy, :force
end
```

The first time through the loop, everything runs beautifully. However, the second time through the loop, I get: 

```
my_ruby_path/gems/sigh-0.3.5/lib/sigh/developer_center.rb:14:in `run': wrong number of arguments (1 for 2..4) (ArgumentError)
        from my_ruby_path/gems/produce-0.1.5/lib/produce/manager.rb:7:in `start_producing'
        from my_ruby_path/gems/fastlane-0.1.14/lib/fastlane/actions/produce.rb:26:in `block in run'
        from my_ruby_path/gems/fastlane-0.1.14/lib/fastlane/actions/produce.rb:20:in `chdir'
        from my_ruby_path/gems/fastlane-0.1.14/lib/fastlane/actions/produce.rb:20:in `run'
        from my_ruby_path/gems/fastlane-0.1.14/lib/fastlane/fast_file.rb:83:in `block (2 levels) in method_missing'
        from my_ruby_path/gems/fastlane-0.1.14/lib/fastlane/actions/actions_helper.rb:28:in `execute_action'
        from my_ruby_path/gems/fastlane-0.1.14/lib/fastlane/fast_file.rb:82:in `block in method_missing'
        from my_ruby_path/gems/fastlane-0.1.14/lib/fastlane/fast_file.rb:81:in `chdir'
        from my_ruby_path/gems/fastlane-0.1.14/lib/fastlane/fast_file.rb:81:in `method_missing'
        from (eval):54:in `block (3 levels) in parse'
        from (eval):44:in `each'
        from (eval):44:in `block (2 levels) in parse'
        from my_ruby_path/gems/fastlane-0.1.14/lib/fastlane/runner.rb:16:in `call'
        from my_ruby_path/gems/fastlane-0.1.14/lib/fastlane/runner.rb:16:in `block in execute'
        from my_ruby_path/gems/fastlane-0.1.14/lib/fastlane/runner.rb:10:in `chdir'
        from my_ruby_path/gems/fastlane-0.1.14/lib/fastlane/runner.rb:10:in `execute'
        from my_ruby_path/gems/fastlane-0.1.14/lib/fastlane/lane_manager.rb:15:in `block in cruise_lanes'
        from my_ruby_path/gems/fastlane-0.1.14/lib/fastlane/lane_manager.rb:14:in `each'
        from my_ruby_path/gems/fastlane-0.1.14/lib/fastlane/lane_manager.rb:14:in `cruise_lanes'
        from my_ruby_path/gems/fastlane-0.1.14/bin/fastlane:30:in `block (2 levels) in run'
        from my_ruby_path/gems/commander-4.3.0/lib/commander/command.rb:179:in `call'
        from my_ruby_path/gems/commander-4.3.0/lib/commander/command.rb:179:in `call'
        from my_ruby_path/gems/commander-4.3.0/lib/commander/command.rb:154:in `run'
        from my_ruby_path/gems/commander-4.3.0/lib/commander/runner.rb:421:in `run_active_command'
        from my_ruby_path/gems/commander-4.3.0/lib/commander/runner.rb:81:in `run!'
        from my_ruby_path/gems/commander-4.3.0/lib/commander/delegates.rb:15:in `run!'
        from my_ruby_path/gems/fastlane-0.1.14/bin/fastlane:58:in `run'
        from my_ruby_path/gems/fastlane-0.1.14/bin/fastlane:62:in `<top (required)>'
        from my_ruby_path/bin/fastlane:23:in `load'
        from my_ruby_path/bin/fastlane:23:in `<main>'
        from my_ruby_path/bin/ruby_executable_hooks:15:in `eval'
        from my_ruby_path/bin/ruby_executable_hooks:15:in `<main>'
```

The problem is that `FastlaneCore::DeveloperCenter` exists in both `sigh` and `produce` and, as you can see from the stack trace, `Produce::Manager.start_producing` is calling the `FastlaneCore::DeveloperCenter` in the `sigh` library.

There may be a better way to solve the problem that I'm working on. The .env stuff that @joshdholtz has been working on looks good. But I don't want to have to call `fastlane deploy --env [environment_name]` for each client. 

Do you have any suggestions?

**Comment by joshdholtz** [comment]
@KrauseFx It appears all code in each tool should be completely wrapped in a separate module so that there is no overlapping in namespacing?

I haven't touched this part of the toolchain yet but it seems like we could do something like this?

### Example for sigh
```ruby
module Sigh
  module FastlaneCore
    class DeveloperCenter

      # Do stuff here
    
    end
  end
end
```

**Comment by jhuggart** [comment]
@joshdholtz That's what I was thinking. But wasn't sure if it would break anything or not.

**Comment by joshdholtz** [comment]
@jhuggart Only one way to find out!

@KrauseFx Do you want to give that shot? Or should I? I haven't touched `product` or `sigh` but this seems like an alright time to do that probably :grin:

**Comment by KrauseFx** [comment]
Just a little background information why this was implemented like this:

There are a lot of helper methods and initialisation in the `DeveloperCenter` class. I guess I got the basic architecture wrong, since I always just include the `DeveloperCenter` from `fastlane_core` when I need it.

I don't know if and how it works if we use a sub-module? Can we still access the helper methods?

**Comment by joshdholtz** [comment]
@KrauseFx Should be able to... I can play with it later tonight though

**Comment by KrauseFx** [comment]
This would really help. If you got it to run for one of the tools (`sigh`, `PEM` or `produce`) that would really help :+1: 

:rocket:

**Comment by joshdholtz** [comment]
@KrauseFx Which one has the best unit tests? :innocent: Cause that is the one I will do first

**Comment by KrauseFx** [comment]
Uiiii :see_no_evil: All the tools which only do web scripting don't have unit tests at all :see_no_evil:

**Comment by joshdholtz** [comment]
`sigh` it is!

**Comment by jhuggart** [comment]
@joshdholtz @KrauseFx Thanks for the quick replies. Let me know if I can help out at all.

**Comment by joshdholtz** [comment]
@jhuggart @KrauseFx I was able to replicate with the `Fastfile` and stacktrace below... So now I can begin to debug/fix it :grin: :tada: 

```ruby
lane :loop_issue do

  (1..4).each do |i|
    puts "Try number #{i}"
    produce
    sigh
  end

end
```

```sh
--- iOS/BanditTheCat ‹master* MD?› » fastlane sigh_bug
INFO [2015-03-04 21:54:21.31]: Driving the lane 'sigh_bug'
Try number 1
INFO [2015-03-04 21:54:21.31]: ---------------------
INFO [2015-03-04 21:54:21.31]: --- Step: produce ---
INFO [2015-03-04 21:54:21.31]: ---------------------
INFO [2015-03-04 21:54:27.59]: Login into iOS Developer Center
INFO [2015-03-04 21:54:38.81]: Login successful
INFO [2015-03-04 21:54:39.32]: App 'Bandit The Cat' already exists, nothing to do on the Dev Center
INFO [2015-03-04 21:54:39.32]: Logging into iTunesConnect
INFO [2015-03-04 21:54:49.94]: Successfully logged into iTunesConnect
INFO [2015-03-04 21:55:08.12]: App 'Bandit The Cat' exists already, nothing to do on iTunes Connect
INFO [2015-03-04 21:55:19.20]: Found Apple ID 963991661
INFO [2015-03-04 21:55:19.20]: ------------------
INFO [2015-03-04 21:55:19.20]: --- Step: sigh ---
INFO [2015-03-04 21:55:19.20]: ------------------
INFO [2015-03-04 21:55:19.82]: Login into iOS Developer Center
INFO [2015-03-04 21:55:22.05]: Fetching all available provisioning profiles...
INFO [2015-03-04 21:55:22.42]: Checking if profile is available. (47 profiles found)
INFO [2015-03-04 21:55:25.53]: Downloading profile...
INFO [2015-03-04 21:55:25.97]: Successfully downloaded provisioning profile
INFO [2015-03-04 21:55:26.07]: Provisioning profile of app 'Bandit The Cat' with the name 'Bandit The Cat App Store' successfully generated and analysed.
INFO [2015-03-04 21:55:26.07]: Exported provisioning profile to '/Users/josh/iOS/BanditTheCat/Distribution_com.banditthecat.BanditTheCat.mobileprovision'
INFO [2015-03-04 21:55:26.07]: [SHELL COMMAND]: open '/Users/josh/iOS/BanditTheCat/Distribution_com.banditthecat.BanditTheCat.mobileprovision'
Try number 2
INFO [2015-03-04 21:55:26.15]: ---------------------
INFO [2015-03-04 21:55:26.15]: --- Step: produce ---
INFO [2015-03-04 21:55:26.15]: ---------------------
INFO [2015-03-04 21:55:26.16]: Login into iOS Developer Center
INFO [2015-03-04 21:55:26.70]: Variable Dump:
INFO [2015-03-04 21:55:26.70]: {:LANE_NAME=>:sigh_bug, :PRODUCE_APPLE_ID=>"963991661", :SIGH_PROFILE_PATH=>"/Users/josh/iOS/BanditTheCat/Distribution_com.banditthecat.BanditTheCat.mobileprovision", :SIGH_UDID=>"69f76e22-ea6d-4beb-a142-d1ae0486be25"}
FATAL [2015-03-04 21:55:26.70]: wrong number of arguments (1 for 2..4)
FATAL [2015-03-04 21:55:26.70]: fastlane finished with errors
/Users/josh/.rvm/gems/ruby-2.0.0-p481@global/gems/sigh-0.3.5/lib/sigh/developer_center.rb:14:in `run': wrong number of arguments (1 for 2..4) (ArgumentError)
	from /Users/josh/.rvm/gems/ruby-2.0.0-p481@global/gems/produce-0.1.5/lib/produce/manager.rb:7:in `start_producing'
	from /Users/josh/.rvm/gems/ruby-2.0.0-p481/gems/fastlane-0.1.14/lib/fastlane/actions/produce.rb:26:in `block in run'
	from /Users/josh/.rvm/gems/ruby-2.0.0-p481/gems/fastlane-0.1.14/lib/fastlane/actions/produce.rb:20:in `chdir'
	from /Users/josh/.rvm/gems/ruby-2.0.0-p481/gems/fastlane-0.1.14/lib/fastlane/actions/produce.rb:20:in `run'
	from /Users/josh/.rvm/gems/ruby-2.0.0-p481/gems/fastlane-0.1.14/lib/fastlane/fast_file.rb:83:in `block (2 levels) in met
```

**Comment by joshdholtz** [comment]
@jhuggart @KrauseFx I got my above example to loop through four times and pass (see output below). What I ended up doing was instead of modifying the `fastlane_core` classes, I created classes under the tools' modules (`FastlaneCore::DeveloperCenter` became `Produce::DeveloperCenter`) and extended them with the `fastlane_core` classes (see below)

```ruby
module Produce
  class DeveloperCenter < FastlaneCore::DeveloperCenter
```

## Pull Requests
- `fastlane` PR - https://github.com/KrauseFx/fastlane/pull/92
- `sgh` PR - https://github.com/KrauseFx/fastlane/pull/92
- `produce` PR - https://github.com/KrauseFx/produce/pull/18

## Output
```sh
--- iOS/BanditTheCat ‹master* MD?› » bundle exec fastlane loop_issue                                                                                                                         1 ↵
INFO [2015-03-04 22:33:51.42]: Driving the lane 'loop_issue'
Try number 1
INFO [2015-03-04 22:33:51.42]: ---------------------
INFO [2015-03-04 22:33:51.42]: --- Step: produce ---
INFO [2015-03-04 22:33:51.42]: ---------------------
INFO [2015-03-04 22:33:57.97]: Login into iOS Developer Center
INFO [2015-03-04 22:34:08.71]: Login successful
INFO [2015-03-04 22:34:09.15]: App 'Bandit The Cat' already exists, nothing to do on the Dev Center
INFO [2015-03-04 22:34:09.15]: Logging into iTunesConnect
INFO [2015-03-04 22:34:18.53]: Successfully logged into iTunesConnect
INFO [2015-03-04 22:34:36.72]: App 'Bandit The Cat' exists already, nothing to do on iTunes Connect
INFO [2015-03-04 22:34:47.76]: Found Apple ID 963991661
INFO [2015-03-04 22:34:47.76]: ------------------
INFO [2015-03-04 22:34:47.76]: --- Step: sigh ---
INFO [2015-03-04 22:34:47.76]: ------------------
INFO [2015-03-04 22:34:48.03]: Login into iOS Developer Center
INFO [2015-03-04 22:34:50.41]: Fetching all available provisioning profiles...
INFO [2015-03-04 22:34:50.75]: Checking if profile is available. (47 profiles found)
INFO [2015-03-04 22:34:53.87]: Downloading profile...
INFO [2015-03-04 22:34:54.25]: Successfully downloaded provisioning profile
INFO [2015-03-04 22:34:54.38]: Provisioning profile of app 'Bandit The Cat' with the name 'Bandit The Cat App Store' successfully generated and analysed.
INFO [2015-03-04 22:34:54.38]: Exported provisioning profile to '/Users/josh/iOS/BanditTheCat/Distribution_com.banditthecat.BanditTheCat.mobileprovision'
INFO [2015-03-04 22:34:54.38]: [SHELL COMMAND]: open '/Users/josh/iOS/BanditTheCat/Distribution_com.banditthecat.BanditTheCat.mobileprovision'
Try number 2
INFO [2015-03-04 22:34:54.47]: ---------------------
INFO [2015-03-04 22:34:54.47]: --- Step: produce ---
INFO [2015-03-04 22:34:54.47]: ---------------------
INFO [2015-03-04 22:34:54.48]: Login into iOS Developer Center
INFO [2015-03-04 22:34:55.79]: App 'Bandit The Cat' already exists, nothing to do on the Dev Center
INFO [2015-03-04 22:34:55.79]: Logging into iTunesConnect
INFO [2015-03-04 22:35:17.97]: App 'Bandit The Cat' exists already, nothing to do on iTunes Connect
INFO [2015-03-04 22:35:28.89]: Found Apple ID 963991661
INFO [2015-03-04 22:35:28.89]: ------------------
INFO [2015-03-04 22:35:28.89]: --- Step: sigh ---
INFO [2015-03-04 22:35:28.89]: ------------------
INFO [2015-03-04 22:35:28.90]: Login into iOS Developer Center
INFO [2015-03-04 22:35:29.82]: Fetching all available provisioning profiles...
INFO [2015-03-04 22:35:30.20]: Checking if profile is available. (47 profiles found)
INFO [2015-03-04 22:35:33.42]: Downloading profile...
INFO [2015-03-04 22:35:33.79]: Successfully downloaded provisioning profile
INFO [2015-03-04 22:35:33.92]: Provisioning profile of app 'Bandit The Cat' with the name 'Bandit The Cat App Store' successfully generated and analysed.
INFO [2015-03-04 22:35:33.92]: Exported provisioning profile to '/Users/josh/iOS/BanditTheCat/Distribution_com.banditthecat.BanditTheCat.mobileprovision'
INFO [2015-03-04 22:35:33.92]: [SHELL COMMAND]: open '/Users/josh/iOS/BanditTheCat/Distribution_com.banditthecat.BanditTheCat.mobileprovision'
Try number 3
INFO [2015-03-04 22:35:34.00]: ---------------------
INFO [2015-03-04 22:35:34.01]: --- Step: produce ---
INFO [2015-03-04 22:35:34.01]: ---------------------
INFO [2015-03-04 22:35:34.01]: Login into iOS Developer Center
INFO [2015-03-04 22:35:35.06]: App 'Bandit The Cat' already exists, nothing to do on the Dev Center
INFO [2015-03-04 22:35:35.06]: Logging into iTunesConnect
INFO [2015-03-04 22:35:56.74]: App 'Bandit The Cat' exists already, nothing to do on iTunes Connect
INFO [2015-03-04 22:36:07.62]: Found Apple ID 963991661
INFO [2015-03-04 22:36:07.62]: ------------------
INFO [2015-03-04 22:36:07.62]: --- Step: sigh ---
INFO [2015-03-04 22:36:07.62]: ------------------
INFO [2015-03-04 22:36:07.63]: Login into iOS Developer Center
INFO [2015-03-04 22:36:08.66]: Fetching all available provisioning profiles...
INFO [2015-03-04 22:36:09.07]: Checking if profile is available. (47 profiles found)
INFO [2015-03-04 22:36:12.27]: Downloading profile...
INFO [2015-03-04 22:36:12.72]: Successfully downloaded provisioning profile
INFO [2015-03-04 22:36:12.80]: Provisioning profile of app 'Bandit The Cat' with the name 'Bandit The Cat App Store' successfully generated and analysed.
INFO [2015-03-04 22:36:12.80]: Exported provisioning profile to '/Users/josh/iOS/BanditTheCat/Distribution_com.banditthecat.BanditTheCat.mobileprovision'
INFO [2015-03-04 22:36:12.80]: [SHELL COMMAND]: open '/Users/josh/iOS/BanditTheCat/Distribution_com.banditthecat.BanditTheCat.mobileprovision'
Try number 4
INFO [2015-03-04 22:36:12.84]: ---------------------
INFO [2015-03-04 22:36:12.84]: --- Step: produce ---
INFO [2015-03-04 22:36:12.84]: ---------------------
INFO [2015-03-04 22:36:12.85]: Login into iOS Developer Center
INFO [2015-03-04 22:36:14.00]: App 'Bandit The Cat' already exists, nothing to do on the Dev Center
INFO [2015-03-04 22:36:14.01]: Logging into iTunesConnect
INFO [2015-03-04 22:36:35.70]: App 'Bandit The Cat' exists already, nothing to do on iTunes Connect
INFO [2015-03-04 22:36:46.73]: Found Apple ID 963991661
INFO [2015-03-04 22:36:46.73]: ------------------
INFO [2015-03-04 22:36:46.73]: --- Step: sigh ---
INFO [2015-03-04 22:36:46.73]: ------------------
INFO [2015-03-04 22:36:46.73]: Login into iOS Developer Center
INFO [2015-03-04 22:36:47.92]: Fetching all available provisioning profiles...
INFO [2015-03-04 22:36:48.29]: Checking if profile is available. (47 profiles found)
INFO [2015-03-04 22:36:51.47]: Downloading profile...
INFO [2015-03-04 22:36:51.85]: Successfully downloaded provisioning profile
INFO [2015-03-04 22:36:51.94]: Provisioning profile of app 'Bandit The Cat' with the name 'Bandit The Cat App Store' successfully generated and analysed.
INFO [2015-03-04 22:36:51.94]: Exported provisioning profile to '/Users/josh/iOS/BanditTheCat/Distribution_com.banditthecat.BanditTheCat.mobileprovision'
INFO [2015-03-04 22:36:51.94]: [SHELL COMMAND]: open '/Users/josh/iOS/BanditTheCat/Distribution_com.banditthecat.BanditTheCat.mobileprovision'
INFO [2015-03-04 22:36:52.00]: fastlane.tools finished successfully 🎉
```

**Comment by jhuggart** [comment]
:+1: Nice work @joshdholtz

**Comment by KrauseFx** [comment]
Thank you @joshdholtz for finding a great and very simple solution :rocket: 

I updated the remaining tools as well:

- https://github.com/KrauseFx/cert/commit/a5972ef454a6f195fe612a1e8c41b4ffdcdb0849
- https://github.com/KrauseFx/codes/commit/300061ab5cd0a2e9852c6abf050a038ddaef98ac
- https://github.com/KrauseFx/deliver/commit/97e0b9926c88a96c523599125f15d41d687c2dfc

I'll release a new version of all tools later today :+1:
